/*
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration};

/// struct for passing parameters to the method [`api_keys_period_create_api_key`]
#[derive(Clone, Debug)]
pub struct ApiKeysPeriodCreateApiKeyParams {
    /// tenant_id
    pub tenant_id: String,
    /// project_id
    pub project_id: String,
    /// environment_id
    pub environment_id: String,
    pub create_api_key_http_request: models::CreateApiKeyHttpRequest,
    /// Bearer API token for strict auth
    pub authorization: Option<String>,
    /// API key alternative for strict auth
    pub x_beater_api_key: Option<String>,
    /// Strict-auth project scope
    pub x_beater_project_id: Option<String>,
    /// Strict-auth environment scope
    pub x_beater_environment_id: Option<String>
}

/// struct for passing parameters to the method [`api_keys_period_revoke_api_key`]
#[derive(Clone, Debug)]
pub struct ApiKeysPeriodRevokeApiKeyParams {
    /// tenant_id
    pub tenant_id: String,
    /// project_id
    pub project_id: String,
    /// environment_id
    pub environment_id: String,
    /// api_key_id
    pub api_key_id: String,
    /// Bearer API token for strict auth
    pub authorization: Option<String>,
    /// API key alternative for strict auth
    pub x_beater_api_key: Option<String>,
    /// Strict-auth project scope
    pub x_beater_project_id: Option<String>,
    /// Strict-auth environment scope
    pub x_beater_environment_id: Option<String>
}


/// struct for typed errors of method [`api_keys_period_create_api_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiKeysPeriodCreateApiKeyError {
    Status400(models::ErrorResponse),
    Status401(models::ErrorResponse),
    Status403(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`api_keys_period_revoke_api_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiKeysPeriodRevokeApiKeyError {
    Status400(models::ErrorResponse),
    Status401(models::ErrorResponse),
    Status403(models::ErrorResponse),
    Status404(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}


pub async fn api_keys_period_create_api_key(configuration: &configuration::Configuration, params: ApiKeysPeriodCreateApiKeyParams) -> Result<models::ApiKeyCreatedResponse, Error<ApiKeysPeriodCreateApiKeyError>> {

    let uri_str = format!("{}/v1/api-keys/{tenant_id}/{project_id}/{environment_id}", configuration.base_path, tenant_id=crate::apis::urlencode(params.tenant_id), project_id=crate::apis::urlencode(params.project_id), environment_id=crate::apis::urlencode(params.environment_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.authorization {
        req_builder = req_builder.header("authorization", param_value.to_string());
    }
    if let Some(param_value) = params.x_beater_api_key {
        req_builder = req_builder.header("x-beater-api-key", param_value.to_string());
    }
    if let Some(param_value) = params.x_beater_project_id {
        req_builder = req_builder.header("x-beater-project-id", param_value.to_string());
    }
    if let Some(param_value) = params.x_beater_environment_id {
        req_builder = req_builder.header("x-beater-environment-id", param_value.to_string());
    }
    req_builder = req_builder.json(&params.create_api_key_http_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        serde_json::from_str(&content).map_err(Error::from)
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiKeysPeriodCreateApiKeyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn api_keys_period_revoke_api_key(configuration: &configuration::Configuration, params: ApiKeysPeriodRevokeApiKeyParams) -> Result<models::RevokedApiKey, Error<ApiKeysPeriodRevokeApiKeyError>> {

    let uri_str = format!("{}/v1/api-keys/{tenant_id}/{project_id}/{environment_id}/{api_key_id}/revoke", configuration.base_path, tenant_id=crate::apis::urlencode(params.tenant_id), project_id=crate::apis::urlencode(params.project_id), environment_id=crate::apis::urlencode(params.environment_id), api_key_id=crate::apis::urlencode(params.api_key_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.authorization {
        req_builder = req_builder.header("authorization", param_value.to_string());
    }
    if let Some(param_value) = params.x_beater_api_key {
        req_builder = req_builder.header("x-beater-api-key", param_value.to_string());
    }
    if let Some(param_value) = params.x_beater_project_id {
        req_builder = req_builder.header("x-beater-project-id", param_value.to_string());
    }
    if let Some(param_value) = params.x_beater_environment_id {
        req_builder = req_builder.header("x-beater-environment-id", param_value.to_string());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        serde_json::from_str(&content).map_err(Error::from)
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiKeysPeriodRevokeApiKeyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

