# coding: utf-8

"""
    Beater API

    Agent observability, evaluation, gating, and human-review APIs for Beater

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from beater_client.api.archive_api import ArchiveApi


class TestArchiveApi(unittest.TestCase):
    """ArchiveApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ArchiveApi()

    def tearDown(self) -> None:
        pass

    def test_archive_archive_trace(self) -> None:
        """Test case for archive_archive_trace

        """
        pass

    def test_archive_query_archive_spans(self) -> None:
        """Test case for archive_query_archive_spans

        """
        pass


if __name__ == '__main__':
    unittest.main()
