# coding: utf-8

"""
    Beater API

    Agent observability, evaluation, gating, and human-review APIs for Beater

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from beater_client.models.canonical_span import CanonicalSpan

class TestCanonicalSpan(unittest.TestCase):
    """CanonicalSpan unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CanonicalSpan:
        """Test CanonicalSpan
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CanonicalSpan`
        """
        model = CanonicalSpan()
        if include_optional:
            return CanonicalSpan(
                attributes = {
                    'key' : null
                    },
                cost = beater_client.models.money.Money(
                    amount_micros = 56, 
                    currency = 'USD', ),
                end_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                environment_id = '',
                input_ref = beater_client.models.artifact_ref.ArtifactRef(
                    artifact_id = '', 
                    mime_type = '', 
                    redaction_class = 'public', 
                    sha256 = '', 
                    size_bytes = 0, 
                    uri = '', ),
                kind = '',
                model = beater_client.models.model_ref.ModelRef(
                    name = '', 
                    provider = '', ),
                name = '',
                normalizer_version = '',
                output_ref = beater_client.models.artifact_ref.ArtifactRef(
                    artifact_id = '', 
                    mime_type = '', 
                    redaction_class = 'public', 
                    sha256 = '', 
                    size_bytes = 0, 
                    uri = '', ),
                parent_span_id = '',
                project_id = '',
                raw_ref = beater_client.models.artifact_ref.ArtifactRef(
                    artifact_id = '', 
                    mime_type = '', 
                    redaction_class = 'public', 
                    sha256 = '', 
                    size_bytes = 0, 
                    uri = '', ),
                schema_version = 0,
                seq = 0,
                span_id = '',
                start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = 'ok',
                tenant_id = '',
                tokens = beater_client.models.token_counts.TokenCounts(
                    cache_read = 0, 
                    input = 0, 
                    output = 0, 
                    reasoning = 0, ),
                trace_id = '',
                unmapped_attrs = None
            )
        else:
            return CanonicalSpan(
                attributes = {
                    'key' : null
                    },
                environment_id = '',
                kind = '',
                name = '',
                normalizer_version = '',
                project_id = '',
                raw_ref = beater_client.models.artifact_ref.ArtifactRef(
                    artifact_id = '', 
                    mime_type = '', 
                    redaction_class = 'public', 
                    sha256 = '', 
                    size_bytes = 0, 
                    uri = '', ),
                schema_version = 0,
                seq = 0,
                span_id = '',
                start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = 'ok',
                tenant_id = '',
                trace_id = '',
                unmapped_attrs = None,
        )
        """

    def testCanonicalSpan(self):
        """Test CanonicalSpan"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
