# coding: utf-8

"""
    Beater API

    Agent observability, evaluation, gating, and human-review APIs for Beater

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from beater_client.api.connect_api import ConnectApi


class TestConnectApi(unittest.TestCase):
    """ConnectApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConnectApi()

    def tearDown(self) -> None:
        pass

    def test_connect_get_palette_connect_status(self) -> None:
        """Test case for connect_get_palette_connect_status

        """
        pass


if __name__ == '__main__':
    unittest.main()
