/* tslint:disable */
/* eslint-disable */
/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PromptTemplate } from './PromptTemplate';
import {
    PromptTemplateFromJSON,
    PromptTemplateFromJSONTyped,
    PromptTemplateToJSON,
    PromptTemplateToJSONTyped,
} from './PromptTemplate';

/**
 * Request body for `addPromptVersion`: a new immutable template revision.
 * @export
 * @interface AddPromptVersionRequest
 */
export interface AddPromptVersionRequest {
    /**
     * 
     * @type {string}
     * @memberof AddPromptVersionRequest
     */
    createdBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddPromptVersionRequest
     */
    message?: string | null;
    /**
     * 
     * @type {PromptTemplate}
     * @memberof AddPromptVersionRequest
     */
    template: PromptTemplate;
}

/**
 * Check if a given object implements the AddPromptVersionRequest interface.
 */
export function instanceOfAddPromptVersionRequest(value: object): value is AddPromptVersionRequest {
    if (!('template' in value) || value['template'] === undefined) return false;
    return true;
}

export function AddPromptVersionRequestFromJSON(json: any): AddPromptVersionRequest {
    return AddPromptVersionRequestFromJSONTyped(json, false);
}

export function AddPromptVersionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddPromptVersionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'message': json['message'] == null ? undefined : json['message'],
        'template': PromptTemplateFromJSON(json['template']),
    };
}

export function AddPromptVersionRequestToJSON(json: any): AddPromptVersionRequest {
    return AddPromptVersionRequestToJSONTyped(json, false);
}

export function AddPromptVersionRequestToJSONTyped(value?: AddPromptVersionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_by': value['createdBy'],
        'message': value['message'],
        'template': PromptTemplateToJSON(value['template']),
    };
}

