/* tslint:disable */
/* eslint-disable */
/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Money } from './Money';
import {
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
    MoneyToJSONTyped,
} from './Money';
import type { TokenCounts } from './TokenCounts';
import {
    TokenCountsFromJSON,
    TokenCountsFromJSONTyped,
    TokenCountsToJSON,
    TokenCountsToJSONTyped,
} from './TokenCounts';
import type { ModelRef } from './ModelRef';
import {
    ModelRefFromJSON,
    ModelRefFromJSONTyped,
    ModelRefToJSON,
    ModelRefToJSONTyped,
} from './ModelRef';
import type { SpanStatus } from './SpanStatus';
import {
    SpanStatusFromJSON,
    SpanStatusFromJSONTyped,
    SpanStatusToJSON,
    SpanStatusToJSONTyped,
} from './SpanStatus';
import type { ArtifactRef } from './ArtifactRef';
import {
    ArtifactRefFromJSON,
    ArtifactRefFromJSONTyped,
    ArtifactRefToJSON,
    ArtifactRefToJSONTyped,
} from './ArtifactRef';

/**
 * 
 * @export
 * @interface CanonicalSpan
 */
export interface CanonicalSpan {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CanonicalSpan
     */
    attributes: { [key: string]: any; };
    /**
     * 
     * @type {Money}
     * @memberof CanonicalSpan
     */
    cost?: Money | null;
    /**
     * 
     * @type {Date}
     * @memberof CanonicalSpan
     */
    endTime?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof CanonicalSpan
     */
    environmentId: string;
    /**
     * 
     * @type {ArtifactRef}
     * @memberof CanonicalSpan
     */
    inputRef?: ArtifactRef | null;
    /**
     * Canonical agent span kind such as agent.run or llm.call
     * @type {string}
     * @memberof CanonicalSpan
     */
    kind: string;
    /**
     * 
     * @type {ModelRef}
     * @memberof CanonicalSpan
     */
    model?: ModelRef | null;
    /**
     * 
     * @type {string}
     * @memberof CanonicalSpan
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CanonicalSpan
     */
    normalizerVersion: string;
    /**
     * 
     * @type {ArtifactRef}
     * @memberof CanonicalSpan
     */
    outputRef?: ArtifactRef | null;
    /**
     * 
     * @type {string}
     * @memberof CanonicalSpan
     */
    parentSpanId?: string;
    /**
     * 
     * @type {string}
     * @memberof CanonicalSpan
     */
    projectId: string;
    /**
     * 
     * @type {ArtifactRef}
     * @memberof CanonicalSpan
     */
    rawRef: ArtifactRef;
    /**
     * 
     * @type {number}
     * @memberof CanonicalSpan
     */
    schemaVersion: number;
    /**
     * 
     * @type {number}
     * @memberof CanonicalSpan
     */
    seq: number;
    /**
     * 
     * @type {string}
     * @memberof CanonicalSpan
     */
    spanId: string;
    /**
     * 
     * @type {Date}
     * @memberof CanonicalSpan
     */
    startTime: Date;
    /**
     * 
     * @type {SpanStatus}
     * @memberof CanonicalSpan
     */
    status: SpanStatus;
    /**
     * 
     * @type {string}
     * @memberof CanonicalSpan
     */
    tenantId: string;
    /**
     * 
     * @type {TokenCounts}
     * @memberof CanonicalSpan
     */
    tokens?: TokenCounts | null;
    /**
     * 
     * @type {string}
     * @memberof CanonicalSpan
     */
    traceId: string;
    /**
     * 
     * @type {any}
     * @memberof CanonicalSpan
     */
    unmappedAttrs: any | null;
}



/**
 * Check if a given object implements the CanonicalSpan interface.
 */
export function instanceOfCanonicalSpan(value: object): value is CanonicalSpan {
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    if (!('environmentId' in value) || value['environmentId'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('normalizerVersion' in value) || value['normalizerVersion'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('rawRef' in value) || value['rawRef'] === undefined) return false;
    if (!('schemaVersion' in value) || value['schemaVersion'] === undefined) return false;
    if (!('seq' in value) || value['seq'] === undefined) return false;
    if (!('spanId' in value) || value['spanId'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('traceId' in value) || value['traceId'] === undefined) return false;
    if (!('unmappedAttrs' in value) || value['unmappedAttrs'] === undefined) return false;
    return true;
}

export function CanonicalSpanFromJSON(json: any): CanonicalSpan {
    return CanonicalSpanFromJSONTyped(json, false);
}

export function CanonicalSpanFromJSONTyped(json: any, ignoreDiscriminator: boolean): CanonicalSpan {
    if (json == null) {
        return json;
    }
    return {
        
        'attributes': json['attributes'],
        'cost': json['cost'] == null ? undefined : MoneyFromJSON(json['cost']),
        'endTime': json['end_time'] == null ? undefined : (new Date(json['end_time'])),
        'environmentId': json['environment_id'],
        'inputRef': json['input_ref'] == null ? undefined : ArtifactRefFromJSON(json['input_ref']),
        'kind': json['kind'],
        'model': json['model'] == null ? undefined : ModelRefFromJSON(json['model']),
        'name': json['name'],
        'normalizerVersion': json['normalizer_version'],
        'outputRef': json['output_ref'] == null ? undefined : ArtifactRefFromJSON(json['output_ref']),
        'parentSpanId': json['parent_span_id'] == null ? undefined : json['parent_span_id'],
        'projectId': json['project_id'],
        'rawRef': ArtifactRefFromJSON(json['raw_ref']),
        'schemaVersion': json['schema_version'],
        'seq': json['seq'],
        'spanId': json['span_id'],
        'startTime': (new Date(json['start_time'])),
        'status': SpanStatusFromJSON(json['status']),
        'tenantId': json['tenant_id'],
        'tokens': json['tokens'] == null ? undefined : TokenCountsFromJSON(json['tokens']),
        'traceId': json['trace_id'],
        'unmappedAttrs': json['unmapped_attrs'],
    };
}

export function CanonicalSpanToJSON(json: any): CanonicalSpan {
    return CanonicalSpanToJSONTyped(json, false);
}

export function CanonicalSpanToJSONTyped(value?: CanonicalSpan | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attributes': value['attributes'],
        'cost': MoneyToJSON(value['cost']),
        'end_time': value['endTime'] == null ? undefined : ((value['endTime'] as any).toISOString()),
        'environment_id': value['environmentId'],
        'input_ref': ArtifactRefToJSON(value['inputRef']),
        'kind': value['kind'],
        'model': ModelRefToJSON(value['model']),
        'name': value['name'],
        'normalizer_version': value['normalizerVersion'],
        'output_ref': ArtifactRefToJSON(value['outputRef']),
        'parent_span_id': value['parentSpanId'],
        'project_id': value['projectId'],
        'raw_ref': ArtifactRefToJSON(value['rawRef']),
        'schema_version': value['schemaVersion'],
        'seq': value['seq'],
        'span_id': value['spanId'],
        'start_time': ((value['startTime']).toISOString()),
        'status': SpanStatusToJSON(value['status']),
        'tenant_id': value['tenantId'],
        'tokens': TokenCountsToJSON(value['tokens']),
        'trace_id': value['traceId'],
        'unmapped_attrs': value['unmappedAttrs'],
    };
}

