/* tslint:disable */
/* eslint-disable */
/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProviderSecretHttpRequest
 */
export interface CreateProviderSecretHttpRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateProviderSecretHttpRequest
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProviderSecretHttpRequest
     */
    provider: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProviderSecretHttpRequest
     */
    secretValue: string;
}

/**
 * Check if a given object implements the CreateProviderSecretHttpRequest interface.
 */
export function instanceOfCreateProviderSecretHttpRequest(value: object): value is CreateProviderSecretHttpRequest {
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('secretValue' in value) || value['secretValue'] === undefined) return false;
    return true;
}

export function CreateProviderSecretHttpRequestFromJSON(json: any): CreateProviderSecretHttpRequest {
    return CreateProviderSecretHttpRequestFromJSONTyped(json, false);
}

export function CreateProviderSecretHttpRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProviderSecretHttpRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['display_name'],
        'provider': json['provider'],
        'secretValue': json['secret_value'],
    };
}

export function CreateProviderSecretHttpRequestToJSON(json: any): CreateProviderSecretHttpRequest {
    return CreateProviderSecretHttpRequestToJSONTyped(json, false);
}

export function CreateProviderSecretHttpRequestToJSONTyped(value?: CreateProviderSecretHttpRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'display_name': value['displayName'],
        'provider': value['provider'],
        'secret_value': value['secretValue'],
    };
}

