/* tslint:disable */
/* eslint-disable */
/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EvalReproducibility
 */
export interface EvalReproducibility {
    /**
     * 
     * @type {string}
     * @memberof EvalReproducibility
     */
    agentReleaseId: string;
    /**
     * 
     * @type {string}
     * @memberof EvalReproducibility
     */
    codeHash?: string;
    /**
     * 
     * @type {string}
     * @memberof EvalReproducibility
     */
    datasetCaseId: string;
    /**
     * 
     * @type {string}
     * @memberof EvalReproducibility
     */
    datasetVersionId: string;
    /**
     * 
     * @type {string}
     * @memberof EvalReproducibility
     */
    evaluatorVersionId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof EvalReproducibility
     */
    inputArtifactHashes: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof EvalReproducibility
     */
    judgeModelId?: string | null;
    /**
     * 
     * @type {any}
     * @memberof EvalReproducibility
     */
    judgeParameters: any | null;
    /**
     * 
     * @type {string}
     * @memberof EvalReproducibility
     */
    judgeProvider?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EvalReproducibility
     */
    judgeRubricVersion?: string | null;
    /**
     * 
     * @type {number}
     * @memberof EvalReproducibility
     */
    judgeSeed?: number | null;
    /**
     * 
     * @type {string}
     * @memberof EvalReproducibility
     */
    normalizerVersion: string;
    /**
     * 
     * @type {string}
     * @memberof EvalReproducibility
     */
    promptVersionId?: string;
    /**
     * 
     * @type {number}
     * @memberof EvalReproducibility
     */
    traceSchemaVersion: number;
    /**
     * 
     * @type {string}
     * @memberof EvalReproducibility
     */
    wasiAbiVersion?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EvalReproducibility
     */
    wasmHash?: string;
}

/**
 * Check if a given object implements the EvalReproducibility interface.
 */
export function instanceOfEvalReproducibility(value: object): value is EvalReproducibility {
    if (!('agentReleaseId' in value) || value['agentReleaseId'] === undefined) return false;
    if (!('datasetCaseId' in value) || value['datasetCaseId'] === undefined) return false;
    if (!('datasetVersionId' in value) || value['datasetVersionId'] === undefined) return false;
    if (!('evaluatorVersionId' in value) || value['evaluatorVersionId'] === undefined) return false;
    if (!('inputArtifactHashes' in value) || value['inputArtifactHashes'] === undefined) return false;
    if (!('judgeParameters' in value) || value['judgeParameters'] === undefined) return false;
    if (!('normalizerVersion' in value) || value['normalizerVersion'] === undefined) return false;
    if (!('traceSchemaVersion' in value) || value['traceSchemaVersion'] === undefined) return false;
    return true;
}

export function EvalReproducibilityFromJSON(json: any): EvalReproducibility {
    return EvalReproducibilityFromJSONTyped(json, false);
}

export function EvalReproducibilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvalReproducibility {
    if (json == null) {
        return json;
    }
    return {
        
        'agentReleaseId': json['agent_release_id'],
        'codeHash': json['code_hash'] == null ? undefined : json['code_hash'],
        'datasetCaseId': json['dataset_case_id'],
        'datasetVersionId': json['dataset_version_id'],
        'evaluatorVersionId': json['evaluator_version_id'],
        'inputArtifactHashes': json['input_artifact_hashes'],
        'judgeModelId': json['judge_model_id'] == null ? undefined : json['judge_model_id'],
        'judgeParameters': json['judge_parameters'],
        'judgeProvider': json['judge_provider'] == null ? undefined : json['judge_provider'],
        'judgeRubricVersion': json['judge_rubric_version'] == null ? undefined : json['judge_rubric_version'],
        'judgeSeed': json['judge_seed'] == null ? undefined : json['judge_seed'],
        'normalizerVersion': json['normalizer_version'],
        'promptVersionId': json['prompt_version_id'] == null ? undefined : json['prompt_version_id'],
        'traceSchemaVersion': json['trace_schema_version'],
        'wasiAbiVersion': json['wasi_abi_version'] == null ? undefined : json['wasi_abi_version'],
        'wasmHash': json['wasm_hash'] == null ? undefined : json['wasm_hash'],
    };
}

export function EvalReproducibilityToJSON(json: any): EvalReproducibility {
    return EvalReproducibilityToJSONTyped(json, false);
}

export function EvalReproducibilityToJSONTyped(value?: EvalReproducibility | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agent_release_id': value['agentReleaseId'],
        'code_hash': value['codeHash'],
        'dataset_case_id': value['datasetCaseId'],
        'dataset_version_id': value['datasetVersionId'],
        'evaluator_version_id': value['evaluatorVersionId'],
        'input_artifact_hashes': value['inputArtifactHashes'],
        'judge_model_id': value['judgeModelId'],
        'judge_parameters': value['judgeParameters'],
        'judge_provider': value['judgeProvider'],
        'judge_rubric_version': value['judgeRubricVersion'],
        'judge_seed': value['judgeSeed'],
        'normalizer_version': value['normalizerVersion'],
        'prompt_version_id': value['promptVersionId'],
        'trace_schema_version': value['traceSchemaVersion'],
        'wasi_abi_version': value['wasiAbiVersion'],
        'wasm_hash': value['wasmHash'],
    };
}

