/* tslint:disable */
/* eslint-disable */
/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PaletteConnectStatus = {
    Connected: 'connected',
    WaitingForTrace: 'waiting_for_trace',
    WaitingForEval: 'waiting_for_eval',
    Misconfigured: 'misconfigured'
} as const;
export type PaletteConnectStatus = typeof PaletteConnectStatus[keyof typeof PaletteConnectStatus];


export function instanceOfPaletteConnectStatus(value: any): boolean {
    for (const key in PaletteConnectStatus) {
        if (Object.prototype.hasOwnProperty.call(PaletteConnectStatus, key)) {
            if (PaletteConnectStatus[key as keyof typeof PaletteConnectStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PaletteConnectStatusFromJSON(json: any): PaletteConnectStatus {
    return PaletteConnectStatusFromJSONTyped(json, false);
}

export function PaletteConnectStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaletteConnectStatus {
    return json as PaletteConnectStatus;
}

export function PaletteConnectStatusToJSON(value?: PaletteConnectStatus | null): any {
    return value as any;
}

export function PaletteConnectStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): PaletteConnectStatus {
    return value as PaletteConnectStatus;
}

