/* tslint:disable */
/* eslint-disable */
/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GatePolicy } from './GatePolicy';
import {
    GatePolicyFromJSON,
    GatePolicyFromJSONTyped,
    GatePolicyToJSON,
    GatePolicyToJSONTyped,
} from './GatePolicy';
import type { CaseOutputOverrideRequest } from './CaseOutputOverrideRequest';
import {
    CaseOutputOverrideRequestFromJSON,
    CaseOutputOverrideRequestFromJSONTyped,
    CaseOutputOverrideRequestToJSON,
    CaseOutputOverrideRequestToJSONTyped,
} from './CaseOutputOverrideRequest';
import type { EvaluatorKind } from './EvaluatorKind';
import {
    EvaluatorKindFromJSON,
    EvaluatorKindFromJSONTyped,
    EvaluatorKindToJSON,
    EvaluatorKindToJSONTyped,
} from './EvaluatorKind';

/**
 * 
 * @export
 * @interface RunExperimentRequest
 */
export interface RunExperimentRequest {
    /**
     * 
     * @type {Array<CaseOutputOverrideRequest>}
     * @memberof RunExperimentRequest
     */
    baselineOutputs: Array<CaseOutputOverrideRequest>;
    /**
     * 
     * @type {string}
     * @memberof RunExperimentRequest
     */
    baselineReleaseId: string;
    /**
     * 
     * @type {Array<CaseOutputOverrideRequest>}
     * @memberof RunExperimentRequest
     */
    candidateOutputs: Array<CaseOutputOverrideRequest>;
    /**
     * 
     * @type {string}
     * @memberof RunExperimentRequest
     */
    candidateReleaseId: string;
    /**
     * 
     * @type {string}
     * @memberof RunExperimentRequest
     */
    evaluatorId: string;
    /**
     * 
     * @type {string}
     * @memberof RunExperimentRequest
     */
    evaluatorVersionId: string;
    /**
     * 
     * @type {GatePolicy}
     * @memberof RunExperimentRequest
     */
    gatePolicy?: GatePolicy | null;
    /**
     * 
     * @type {EvaluatorKind}
     * @memberof RunExperimentRequest
     */
    kind: EvaluatorKind;
}

/**
 * Check if a given object implements the RunExperimentRequest interface.
 */
export function instanceOfRunExperimentRequest(value: object): value is RunExperimentRequest {
    if (!('baselineOutputs' in value) || value['baselineOutputs'] === undefined) return false;
    if (!('baselineReleaseId' in value) || value['baselineReleaseId'] === undefined) return false;
    if (!('candidateOutputs' in value) || value['candidateOutputs'] === undefined) return false;
    if (!('candidateReleaseId' in value) || value['candidateReleaseId'] === undefined) return false;
    if (!('evaluatorId' in value) || value['evaluatorId'] === undefined) return false;
    if (!('evaluatorVersionId' in value) || value['evaluatorVersionId'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    return true;
}

export function RunExperimentRequestFromJSON(json: any): RunExperimentRequest {
    return RunExperimentRequestFromJSONTyped(json, false);
}

export function RunExperimentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunExperimentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'baselineOutputs': ((json['baseline_outputs'] as Array<any>).map(CaseOutputOverrideRequestFromJSON)),
        'baselineReleaseId': json['baseline_release_id'],
        'candidateOutputs': ((json['candidate_outputs'] as Array<any>).map(CaseOutputOverrideRequestFromJSON)),
        'candidateReleaseId': json['candidate_release_id'],
        'evaluatorId': json['evaluator_id'],
        'evaluatorVersionId': json['evaluator_version_id'],
        'gatePolicy': json['gate_policy'] == null ? undefined : GatePolicyFromJSON(json['gate_policy']),
        'kind': EvaluatorKindFromJSON(json['kind']),
    };
}

export function RunExperimentRequestToJSON(json: any): RunExperimentRequest {
    return RunExperimentRequestToJSONTyped(json, false);
}

export function RunExperimentRequestToJSONTyped(value?: RunExperimentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'baseline_outputs': ((value['baselineOutputs'] as Array<any>).map(CaseOutputOverrideRequestToJSON)),
        'baseline_release_id': value['baselineReleaseId'],
        'candidate_outputs': ((value['candidateOutputs'] as Array<any>).map(CaseOutputOverrideRequestToJSON)),
        'candidate_release_id': value['candidateReleaseId'],
        'evaluator_id': value['evaluatorId'],
        'evaluator_version_id': value['evaluatorVersionId'],
        'gate_policy': GatePolicyToJSON(value['gatePolicy']),
        'kind': EvaluatorKindToJSON(value['kind']),
    };
}

