/* tslint:disable */
/* eslint-disable */
/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SamplingReason = {
    ErrorTrace: 'error_trace',
    SlowTrace: 'slow_trace',
    HighCostTrace: 'high_cost_trace',
    RoutineSampled: 'routine_sampled',
    RoutineDropped: 'routine_dropped'
} as const;
export type SamplingReason = typeof SamplingReason[keyof typeof SamplingReason];


export function instanceOfSamplingReason(value: any): boolean {
    for (const key in SamplingReason) {
        if (Object.prototype.hasOwnProperty.call(SamplingReason, key)) {
            if (SamplingReason[key as keyof typeof SamplingReason] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SamplingReasonFromJSON(json: any): SamplingReason {
    return SamplingReasonFromJSONTyped(json, false);
}

export function SamplingReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): SamplingReason {
    return json as SamplingReason;
}

export function SamplingReasonToJSON(value?: SamplingReason | null): any {
    return value as any;
}

export function SamplingReasonToJSONTyped(value: any, ignoreDiscriminator: boolean): SamplingReason {
    return value as SamplingReason;
}

