/* tslint:disable */
/* eslint-disable */
/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenCounts
 */
export interface TokenCounts {
    /**
     * 
     * @type {number}
     * @memberof TokenCounts
     */
    cacheRead: number;
    /**
     * 
     * @type {number}
     * @memberof TokenCounts
     */
    input: number;
    /**
     * 
     * @type {number}
     * @memberof TokenCounts
     */
    output: number;
    /**
     * 
     * @type {number}
     * @memberof TokenCounts
     */
    reasoning: number;
}

/**
 * Check if a given object implements the TokenCounts interface.
 */
export function instanceOfTokenCounts(value: object): value is TokenCounts {
    if (!('cacheRead' in value) || value['cacheRead'] === undefined) return false;
    if (!('input' in value) || value['input'] === undefined) return false;
    if (!('output' in value) || value['output'] === undefined) return false;
    if (!('reasoning' in value) || value['reasoning'] === undefined) return false;
    return true;
}

export function TokenCountsFromJSON(json: any): TokenCounts {
    return TokenCountsFromJSONTyped(json, false);
}

export function TokenCountsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenCounts {
    if (json == null) {
        return json;
    }
    return {
        
        'cacheRead': json['cache_read'],
        'input': json['input'],
        'output': json['output'],
        'reasoning': json['reasoning'],
    };
}

export function TokenCountsToJSON(json: any): TokenCounts {
    return TokenCountsToJSONTyped(json, false);
}

export function TokenCountsToJSONTyped(value?: TokenCounts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cache_read': value['cacheRead'],
        'input': value['input'],
        'output': value['output'],
        'reasoning': value['reasoning'],
    };
}

