/*
Beater API

Testing ReviewsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package beaterclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID/beaterclient"
)

func Test_beaterclient_ReviewsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ReviewsAPIService CreateReviewQueue", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string
		var projectId string

		resp, httpRes, err := apiClient.ReviewsAPI.CreateReviewQueue(context.Background(), tenantId, projectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ReviewsAPIService EnqueueReviewTaskFromTrace", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string
		var projectId string
		var queueId string

		resp, httpRes, err := apiClient.ReviewsAPI.EnqueueReviewTaskFromTrace(context.Background(), tenantId, projectId, queueId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ReviewsAPIService ListReviewTasks", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string
		var projectId string
		var queueId string

		resp, httpRes, err := apiClient.ReviewsAPI.ListReviewTasks(context.Background(), tenantId, projectId, queueId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ReviewsAPIService PromoteReviewAnnotation", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string
		var projectId string
		var queueId string
		var taskId string
		var annotationId string

		resp, httpRes, err := apiClient.ReviewsAPI.PromoteReviewAnnotation(context.Background(), tenantId, projectId, queueId, taskId, annotationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ReviewsAPIService SubmitReviewAnnotation", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string
		var projectId string
		var queueId string
		var taskId string

		resp, httpRes, err := apiClient.ReviewsAPI.SubmitReviewAnnotation(context.Background(), tenantId, projectId, queueId, taskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
