/*
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Beater.Client.Client.FileParameter;
using OpenAPIDateConverter = Beater.Client.Client.OpenAPIDateConverter;

namespace Beater.Client.Model
{
    /// <summary>
    /// CreateApiKeyHttpRequest
    /// </summary>
    [DataContract(Name = "CreateApiKeyHttpRequest")]
    public partial class CreateApiKeyHttpRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateApiKeyHttpRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateApiKeyHttpRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateApiKeyHttpRequest" /> class.
        /// </summary>
        /// <param name="scopes">scopes (required).</param>
        public CreateApiKeyHttpRequest(List<ApiScope> scopes = default(List<ApiScope>))
        {
            // to ensure "scopes" is required (not null)
            if (scopes == null)
            {
                throw new ArgumentNullException("scopes is a required property for CreateApiKeyHttpRequest and cannot be null");
            }
            this.Scopes = scopes;
        }

        /// <summary>
        /// Gets or Sets Scopes
        /// </summary>
        [DataMember(Name = "scopes", IsRequired = true, EmitDefaultValue = true)]
        public List<ApiScope> Scopes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateApiKeyHttpRequest {\n");
            sb.Append("  Scopes: ").Append(Scopes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
