/*
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Beater.Client.Client.FileParameter;
using OpenAPIDateConverter = Beater.Client.Client.OpenAPIDateConverter;

namespace Beater.Client.Model
{
    /// <summary>
    /// GatePolicy
    /// </summary>
    [DataContract(Name = "GatePolicy")]
    public partial class GatePolicy : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GatePolicy" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GatePolicy() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GatePolicy" /> class.
        /// </summary>
        /// <param name="alpha">alpha (required).</param>
        /// <param name="comparisonCount">comparisonCount (required).</param>
        /// <param name="maxRegression">maxRegression (required).</param>
        /// <param name="minSampleSize">minSampleSize (required).</param>
        public GatePolicy(double alpha = default(double), int comparisonCount = default(int), double maxRegression = default(double), int minSampleSize = default(int))
        {
            this.Alpha = alpha;
            this.ComparisonCount = comparisonCount;
            this.MaxRegression = maxRegression;
            this.MinSampleSize = minSampleSize;
        }

        /// <summary>
        /// Gets or Sets Alpha
        /// </summary>
        [DataMember(Name = "alpha", IsRequired = true, EmitDefaultValue = true)]
        public double Alpha { get; set; }

        /// <summary>
        /// Gets or Sets ComparisonCount
        /// </summary>
        [DataMember(Name = "comparison_count", IsRequired = true, EmitDefaultValue = true)]
        public int ComparisonCount { get; set; }

        /// <summary>
        /// Gets or Sets MaxRegression
        /// </summary>
        [DataMember(Name = "max_regression", IsRequired = true, EmitDefaultValue = true)]
        public double MaxRegression { get; set; }

        /// <summary>
        /// Gets or Sets MinSampleSize
        /// </summary>
        [DataMember(Name = "min_sample_size", IsRequired = true, EmitDefaultValue = true)]
        public int MinSampleSize { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GatePolicy {\n");
            sb.Append("  Alpha: ").Append(Alpha).Append("\n");
            sb.Append("  ComparisonCount: ").Append(ComparisonCount).Append("\n");
            sb.Append("  MaxRegression: ").Append(MaxRegression).Append("\n");
            sb.Append("  MinSampleSize: ").Append(MinSampleSize).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // ComparisonCount (int) minimum
            if (this.ComparisonCount < (int)0)
            {
                yield return new ValidationResult("Invalid value for ComparisonCount, must be a value greater than or equal to 0.", new [] { "ComparisonCount" });
            }

            // MinSampleSize (int) minimum
            if (this.MinSampleSize < (int)0)
            {
                yield return new ValidationResult("Invalid value for MinSampleSize, must be a value greater than or equal to 0.", new [] { "MinSampleSize" });
            }

            yield break;
        }
    }

}
