/*
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Beater.Client.Client.FileParameter;
using OpenAPIDateConverter = Beater.Client.Client.OpenAPIDateConverter;

namespace Beater.Client.Model
{
    /// <summary>
    /// MineScenariosRequest
    /// </summary>
    [DataContract(Name = "MineScenariosRequest")]
    public partial class MineScenariosRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MineScenariosRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MineScenariosRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MineScenariosRequest" /> class.
        /// </summary>
        /// <param name="jaccardThreshold">jaccardThreshold.</param>
        /// <param name="traceIds">traceIds (required).</param>
        public MineScenariosRequest(double? jaccardThreshold = default(double?), List<string> traceIds = default(List<string>))
        {
            // to ensure "traceIds" is required (not null)
            if (traceIds == null)
            {
                throw new ArgumentNullException("traceIds is a required property for MineScenariosRequest and cannot be null");
            }
            this.TraceIds = traceIds;
            this.JaccardThreshold = jaccardThreshold;
        }

        /// <summary>
        /// Gets or Sets JaccardThreshold
        /// </summary>
        [DataMember(Name = "jaccard_threshold", EmitDefaultValue = true)]
        public double? JaccardThreshold { get; set; }

        /// <summary>
        /// Gets or Sets TraceIds
        /// </summary>
        [DataMember(Name = "trace_ids", IsRequired = true, EmitDefaultValue = true)]
        public List<string> TraceIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MineScenariosRequest {\n");
            sb.Append("  JaccardThreshold: ").Append(JaccardThreshold).Append("\n");
            sb.Append("  TraceIds: ").Append(TraceIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
