/*
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Beater.Client.Client.FileParameter;
using OpenAPIDateConverter = Beater.Client.Client.OpenAPIDateConverter;

namespace Beater.Client.Model
{
    /// <summary>
    /// PromptVersionListResponse
    /// </summary>
    [DataContract(Name = "PromptVersionListResponse")]
    public partial class PromptVersionListResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PromptVersionListResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PromptVersionListResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PromptVersionListResponse" /> class.
        /// </summary>
        /// <param name="versions">versions (required).</param>
        public PromptVersionListResponse(List<PromptVersion> versions = default(List<PromptVersion>))
        {
            // to ensure "versions" is required (not null)
            if (versions == null)
            {
                throw new ArgumentNullException("versions is a required property for PromptVersionListResponse and cannot be null");
            }
            this.Versions = versions;
        }

        /// <summary>
        /// Gets or Sets Versions
        /// </summary>
        [DataMember(Name = "versions", IsRequired = true, EmitDefaultValue = true)]
        public List<PromptVersion> Versions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PromptVersionListResponse {\n");
            sb.Append("  Versions: ").Append(Versions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
