/*
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Beater.Client.Client.FileParameter;
using OpenAPIDateConverter = Beater.Client.Client.OpenAPIDateConverter;

namespace Beater.Client.Model
{
    /// <summary>
    /// RunExperimentRequest
    /// </summary>
    [DataContract(Name = "RunExperimentRequest")]
    public partial class RunExperimentRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RunExperimentRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RunExperimentRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RunExperimentRequest" /> class.
        /// </summary>
        /// <param name="baselineOutputs">baselineOutputs (required).</param>
        /// <param name="baselineReleaseId">baselineReleaseId (required).</param>
        /// <param name="candidateOutputs">candidateOutputs (required).</param>
        /// <param name="candidateReleaseId">candidateReleaseId (required).</param>
        /// <param name="evaluatorId">evaluatorId (required).</param>
        /// <param name="evaluatorVersionId">evaluatorVersionId (required).</param>
        /// <param name="gatePolicy">gatePolicy.</param>
        /// <param name="kind">kind (required).</param>
        public RunExperimentRequest(List<CaseOutputOverrideRequest> baselineOutputs = default(List<CaseOutputOverrideRequest>), string baselineReleaseId = default(string), List<CaseOutputOverrideRequest> candidateOutputs = default(List<CaseOutputOverrideRequest>), string candidateReleaseId = default(string), string evaluatorId = default(string), string evaluatorVersionId = default(string), GatePolicy gatePolicy = default(GatePolicy), EvaluatorKind kind = default(EvaluatorKind))
        {
            // to ensure "baselineOutputs" is required (not null)
            if (baselineOutputs == null)
            {
                throw new ArgumentNullException("baselineOutputs is a required property for RunExperimentRequest and cannot be null");
            }
            this.BaselineOutputs = baselineOutputs;
            // to ensure "baselineReleaseId" is required (not null)
            if (baselineReleaseId == null)
            {
                throw new ArgumentNullException("baselineReleaseId is a required property for RunExperimentRequest and cannot be null");
            }
            this.BaselineReleaseId = baselineReleaseId;
            // to ensure "candidateOutputs" is required (not null)
            if (candidateOutputs == null)
            {
                throw new ArgumentNullException("candidateOutputs is a required property for RunExperimentRequest and cannot be null");
            }
            this.CandidateOutputs = candidateOutputs;
            // to ensure "candidateReleaseId" is required (not null)
            if (candidateReleaseId == null)
            {
                throw new ArgumentNullException("candidateReleaseId is a required property for RunExperimentRequest and cannot be null");
            }
            this.CandidateReleaseId = candidateReleaseId;
            // to ensure "evaluatorId" is required (not null)
            if (evaluatorId == null)
            {
                throw new ArgumentNullException("evaluatorId is a required property for RunExperimentRequest and cannot be null");
            }
            this.EvaluatorId = evaluatorId;
            // to ensure "evaluatorVersionId" is required (not null)
            if (evaluatorVersionId == null)
            {
                throw new ArgumentNullException("evaluatorVersionId is a required property for RunExperimentRequest and cannot be null");
            }
            this.EvaluatorVersionId = evaluatorVersionId;
            // to ensure "kind" is required (not null)
            if (kind == null)
            {
                throw new ArgumentNullException("kind is a required property for RunExperimentRequest and cannot be null");
            }
            this.Kind = kind;
            this.GatePolicy = gatePolicy;
        }

        /// <summary>
        /// Gets or Sets BaselineOutputs
        /// </summary>
        [DataMember(Name = "baseline_outputs", IsRequired = true, EmitDefaultValue = true)]
        public List<CaseOutputOverrideRequest> BaselineOutputs { get; set; }

        /// <summary>
        /// Gets or Sets BaselineReleaseId
        /// </summary>
        [DataMember(Name = "baseline_release_id", IsRequired = true, EmitDefaultValue = true)]
        public string BaselineReleaseId { get; set; }

        /// <summary>
        /// Gets or Sets CandidateOutputs
        /// </summary>
        [DataMember(Name = "candidate_outputs", IsRequired = true, EmitDefaultValue = true)]
        public List<CaseOutputOverrideRequest> CandidateOutputs { get; set; }

        /// <summary>
        /// Gets or Sets CandidateReleaseId
        /// </summary>
        [DataMember(Name = "candidate_release_id", IsRequired = true, EmitDefaultValue = true)]
        public string CandidateReleaseId { get; set; }

        /// <summary>
        /// Gets or Sets EvaluatorId
        /// </summary>
        [DataMember(Name = "evaluator_id", IsRequired = true, EmitDefaultValue = true)]
        public string EvaluatorId { get; set; }

        /// <summary>
        /// Gets or Sets EvaluatorVersionId
        /// </summary>
        [DataMember(Name = "evaluator_version_id", IsRequired = true, EmitDefaultValue = true)]
        public string EvaluatorVersionId { get; set; }

        /// <summary>
        /// Gets or Sets GatePolicy
        /// </summary>
        [DataMember(Name = "gate_policy", EmitDefaultValue = true)]
        public GatePolicy GatePolicy { get; set; }

        /// <summary>
        /// Gets or Sets Kind
        /// </summary>
        [DataMember(Name = "kind", IsRequired = true, EmitDefaultValue = true)]
        public EvaluatorKind Kind { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RunExperimentRequest {\n");
            sb.Append("  BaselineOutputs: ").Append(BaselineOutputs).Append("\n");
            sb.Append("  BaselineReleaseId: ").Append(BaselineReleaseId).Append("\n");
            sb.Append("  CandidateOutputs: ").Append(CandidateOutputs).Append("\n");
            sb.Append("  CandidateReleaseId: ").Append(CandidateReleaseId).Append("\n");
            sb.Append("  EvaluatorId: ").Append(EvaluatorId).Append("\n");
            sb.Append("  EvaluatorVersionId: ").Append(EvaluatorVersionId).Append("\n");
            sb.Append("  GatePolicy: ").Append(GatePolicy).Append("\n");
            sb.Append("  Kind: ").Append(Kind).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
