/*
Beater API

Agent observability, evaluation, gating, and human-review APIs for Beater

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package beaterclient

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the JudgeAuditRecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JudgeAuditRecord{}

// JudgeAuditRecord struct for JudgeAuditRecord
type JudgeAuditRecord struct {
	Cached bool `json:"cached"`
	ChargedCost Money `json:"charged_cost"`
	CreatedAt time.Time `json:"created_at"`
	EvaluatorId string `json:"evaluator_id"`
	JudgeCallId string `json:"judge_call_id"`
	Model string `json:"model"`
	ProjectId string `json:"project_id"`
	Provider string `json:"provider"`
	ProviderCost Money `json:"provider_cost"`
	ProviderSecretId string `json:"provider_secret_id"`
	RequestHash string `json:"request_hash"`
	ResponseHash string `json:"response_hash"`
	Score float64 `json:"score"`
	TenantId string `json:"tenant_id"`
}

type _JudgeAuditRecord JudgeAuditRecord

// NewJudgeAuditRecord instantiates a new JudgeAuditRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJudgeAuditRecord(cached bool, chargedCost Money, createdAt time.Time, evaluatorId string, judgeCallId string, model string, projectId string, provider string, providerCost Money, providerSecretId string, requestHash string, responseHash string, score float64, tenantId string) *JudgeAuditRecord {
	this := JudgeAuditRecord{}
	this.Cached = cached
	this.ChargedCost = chargedCost
	this.CreatedAt = createdAt
	this.EvaluatorId = evaluatorId
	this.JudgeCallId = judgeCallId
	this.Model = model
	this.ProjectId = projectId
	this.Provider = provider
	this.ProviderCost = providerCost
	this.ProviderSecretId = providerSecretId
	this.RequestHash = requestHash
	this.ResponseHash = responseHash
	this.Score = score
	this.TenantId = tenantId
	return &this
}

// NewJudgeAuditRecordWithDefaults instantiates a new JudgeAuditRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJudgeAuditRecordWithDefaults() *JudgeAuditRecord {
	this := JudgeAuditRecord{}
	return &this
}

// GetCached returns the Cached field value
func (o *JudgeAuditRecord) GetCached() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Cached
}

// GetCachedOk returns a tuple with the Cached field value
// and a boolean to check if the value has been set.
func (o *JudgeAuditRecord) GetCachedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cached, true
}

// SetCached sets field value
func (o *JudgeAuditRecord) SetCached(v bool) {
	o.Cached = v
}

// GetChargedCost returns the ChargedCost field value
func (o *JudgeAuditRecord) GetChargedCost() Money {
	if o == nil {
		var ret Money
		return ret
	}

	return o.ChargedCost
}

// GetChargedCostOk returns a tuple with the ChargedCost field value
// and a boolean to check if the value has been set.
func (o *JudgeAuditRecord) GetChargedCostOk() (*Money, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChargedCost, true
}

// SetChargedCost sets field value
func (o *JudgeAuditRecord) SetChargedCost(v Money) {
	o.ChargedCost = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *JudgeAuditRecord) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *JudgeAuditRecord) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *JudgeAuditRecord) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetEvaluatorId returns the EvaluatorId field value
func (o *JudgeAuditRecord) GetEvaluatorId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EvaluatorId
}

// GetEvaluatorIdOk returns a tuple with the EvaluatorId field value
// and a boolean to check if the value has been set.
func (o *JudgeAuditRecord) GetEvaluatorIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EvaluatorId, true
}

// SetEvaluatorId sets field value
func (o *JudgeAuditRecord) SetEvaluatorId(v string) {
	o.EvaluatorId = v
}

// GetJudgeCallId returns the JudgeCallId field value
func (o *JudgeAuditRecord) GetJudgeCallId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JudgeCallId
}

// GetJudgeCallIdOk returns a tuple with the JudgeCallId field value
// and a boolean to check if the value has been set.
func (o *JudgeAuditRecord) GetJudgeCallIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JudgeCallId, true
}

// SetJudgeCallId sets field value
func (o *JudgeAuditRecord) SetJudgeCallId(v string) {
	o.JudgeCallId = v
}

// GetModel returns the Model field value
func (o *JudgeAuditRecord) GetModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *JudgeAuditRecord) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *JudgeAuditRecord) SetModel(v string) {
	o.Model = v
}

// GetProjectId returns the ProjectId field value
func (o *JudgeAuditRecord) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *JudgeAuditRecord) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *JudgeAuditRecord) SetProjectId(v string) {
	o.ProjectId = v
}

// GetProvider returns the Provider field value
func (o *JudgeAuditRecord) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *JudgeAuditRecord) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *JudgeAuditRecord) SetProvider(v string) {
	o.Provider = v
}

// GetProviderCost returns the ProviderCost field value
func (o *JudgeAuditRecord) GetProviderCost() Money {
	if o == nil {
		var ret Money
		return ret
	}

	return o.ProviderCost
}

// GetProviderCostOk returns a tuple with the ProviderCost field value
// and a boolean to check if the value has been set.
func (o *JudgeAuditRecord) GetProviderCostOk() (*Money, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderCost, true
}

// SetProviderCost sets field value
func (o *JudgeAuditRecord) SetProviderCost(v Money) {
	o.ProviderCost = v
}

// GetProviderSecretId returns the ProviderSecretId field value
func (o *JudgeAuditRecord) GetProviderSecretId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProviderSecretId
}

// GetProviderSecretIdOk returns a tuple with the ProviderSecretId field value
// and a boolean to check if the value has been set.
func (o *JudgeAuditRecord) GetProviderSecretIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderSecretId, true
}

// SetProviderSecretId sets field value
func (o *JudgeAuditRecord) SetProviderSecretId(v string) {
	o.ProviderSecretId = v
}

// GetRequestHash returns the RequestHash field value
func (o *JudgeAuditRecord) GetRequestHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestHash
}

// GetRequestHashOk returns a tuple with the RequestHash field value
// and a boolean to check if the value has been set.
func (o *JudgeAuditRecord) GetRequestHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestHash, true
}

// SetRequestHash sets field value
func (o *JudgeAuditRecord) SetRequestHash(v string) {
	o.RequestHash = v
}

// GetResponseHash returns the ResponseHash field value
func (o *JudgeAuditRecord) GetResponseHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResponseHash
}

// GetResponseHashOk returns a tuple with the ResponseHash field value
// and a boolean to check if the value has been set.
func (o *JudgeAuditRecord) GetResponseHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResponseHash, true
}

// SetResponseHash sets field value
func (o *JudgeAuditRecord) SetResponseHash(v string) {
	o.ResponseHash = v
}

// GetScore returns the Score field value
func (o *JudgeAuditRecord) GetScore() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Score
}

// GetScoreOk returns a tuple with the Score field value
// and a boolean to check if the value has been set.
func (o *JudgeAuditRecord) GetScoreOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Score, true
}

// SetScore sets field value
func (o *JudgeAuditRecord) SetScore(v float64) {
	o.Score = v
}

// GetTenantId returns the TenantId field value
func (o *JudgeAuditRecord) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *JudgeAuditRecord) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *JudgeAuditRecord) SetTenantId(v string) {
	o.TenantId = v
}

func (o JudgeAuditRecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JudgeAuditRecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cached"] = o.Cached
	toSerialize["charged_cost"] = o.ChargedCost
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["evaluator_id"] = o.EvaluatorId
	toSerialize["judge_call_id"] = o.JudgeCallId
	toSerialize["model"] = o.Model
	toSerialize["project_id"] = o.ProjectId
	toSerialize["provider"] = o.Provider
	toSerialize["provider_cost"] = o.ProviderCost
	toSerialize["provider_secret_id"] = o.ProviderSecretId
	toSerialize["request_hash"] = o.RequestHash
	toSerialize["response_hash"] = o.ResponseHash
	toSerialize["score"] = o.Score
	toSerialize["tenant_id"] = o.TenantId
	return toSerialize, nil
}

func (o *JudgeAuditRecord) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cached",
		"charged_cost",
		"created_at",
		"evaluator_id",
		"judge_call_id",
		"model",
		"project_id",
		"provider",
		"provider_cost",
		"provider_secret_id",
		"request_hash",
		"response_hash",
		"score",
		"tenant_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJudgeAuditRecord := _JudgeAuditRecord{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJudgeAuditRecord)

	if err != nil {
		return err
	}

	*o = JudgeAuditRecord(varJudgeAuditRecord)

	return err
}

type NullableJudgeAuditRecord struct {
	value *JudgeAuditRecord
	isSet bool
}

func (v NullableJudgeAuditRecord) Get() *JudgeAuditRecord {
	return v.value
}

func (v *NullableJudgeAuditRecord) Set(val *JudgeAuditRecord) {
	v.value = val
	v.isSet = true
}

func (v NullableJudgeAuditRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableJudgeAuditRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJudgeAuditRecord(val *JudgeAuditRecord) *NullableJudgeAuditRecord {
	return &NullableJudgeAuditRecord{value: val, isSet: true}
}

func (v NullableJudgeAuditRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJudgeAuditRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


