/*
Beater API

Agent observability, evaluation, gating, and human-review APIs for Beater

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package beaterclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreatedPrompt type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatedPrompt{}

// CreatedPrompt struct for CreatedPrompt
type CreatedPrompt struct {
	Prompt Prompt `json:"prompt"`
	Version PromptVersion `json:"version"`
}

type _CreatedPrompt CreatedPrompt

// NewCreatedPrompt instantiates a new CreatedPrompt object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatedPrompt(prompt Prompt, version PromptVersion) *CreatedPrompt {
	this := CreatedPrompt{}
	this.Prompt = prompt
	this.Version = version
	return &this
}

// NewCreatedPromptWithDefaults instantiates a new CreatedPrompt object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatedPromptWithDefaults() *CreatedPrompt {
	this := CreatedPrompt{}
	return &this
}

// GetPrompt returns the Prompt field value
func (o *CreatedPrompt) GetPrompt() Prompt {
	if o == nil {
		var ret Prompt
		return ret
	}

	return o.Prompt
}

// GetPromptOk returns a tuple with the Prompt field value
// and a boolean to check if the value has been set.
func (o *CreatedPrompt) GetPromptOk() (*Prompt, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prompt, true
}

// SetPrompt sets field value
func (o *CreatedPrompt) SetPrompt(v Prompt) {
	o.Prompt = v
}

// GetVersion returns the Version field value
func (o *CreatedPrompt) GetVersion() PromptVersion {
	if o == nil {
		var ret PromptVersion
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *CreatedPrompt) GetVersionOk() (*PromptVersion, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *CreatedPrompt) SetVersion(v PromptVersion) {
	o.Version = v
}

func (o CreatedPrompt) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatedPrompt) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["prompt"] = o.Prompt
	toSerialize["version"] = o.Version
	return toSerialize, nil
}

func (o *CreatedPrompt) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"prompt",
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreatedPrompt := _CreatedPrompt{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreatedPrompt)

	if err != nil {
		return err
	}

	*o = CreatedPrompt(varCreatedPrompt)

	return err
}

type NullableCreatedPrompt struct {
	value *CreatedPrompt
	isSet bool
}

func (v NullableCreatedPrompt) Get() *CreatedPrompt {
	return v.value
}

func (v *NullableCreatedPrompt) Set(val *CreatedPrompt) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatedPrompt) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatedPrompt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatedPrompt(val *CreatedPrompt) *NullableCreatedPrompt {
	return &NullableCreatedPrompt{value: val, isSet: true}
}

func (v NullableCreatedPrompt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatedPrompt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


