/*
Beater API

Agent observability, evaluation, gating, and human-review APIs for Beater

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package beaterclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ArchivedSpanRow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArchivedSpanRow{}

// ArchivedSpanRow struct for ArchivedSpanRow
type ArchivedSpanRow struct {
	AttributesJson string `json:"attributes_json"`
	CostAmountMicros NullableString `json:"cost_amount_micros,omitempty"`
	CostCurrency NullableString `json:"cost_currency,omitempty"`
	EndTime NullableString `json:"end_time,omitempty"`
	EnvironmentId string `json:"environment_id"`
	InputTokens NullableString `json:"input_tokens,omitempty"`
	InputUri NullableString `json:"input_uri,omitempty"`
	Kind string `json:"kind"`
	ModelName NullableString `json:"model_name,omitempty"`
	ModelProvider NullableString `json:"model_provider,omitempty"`
	Name string `json:"name"`
	OutputTokens NullableString `json:"output_tokens,omitempty"`
	OutputUri NullableString `json:"output_uri,omitempty"`
	ParentSpanId NullableString `json:"parent_span_id,omitempty"`
	ProjectId string `json:"project_id"`
	RawUri string `json:"raw_uri"`
	ReasoningTokens NullableString `json:"reasoning_tokens,omitempty"`
	Seq int64 `json:"seq"`
	SpanId string `json:"span_id"`
	StartTime string `json:"start_time"`
	Status string `json:"status"`
	TenantId string `json:"tenant_id"`
	TraceId string `json:"trace_id"`
	UnmappedJson string `json:"unmapped_json"`
}

type _ArchivedSpanRow ArchivedSpanRow

// NewArchivedSpanRow instantiates a new ArchivedSpanRow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArchivedSpanRow(attributesJson string, environmentId string, kind string, name string, projectId string, rawUri string, seq int64, spanId string, startTime string, status string, tenantId string, traceId string, unmappedJson string) *ArchivedSpanRow {
	this := ArchivedSpanRow{}
	this.AttributesJson = attributesJson
	this.EnvironmentId = environmentId
	this.Kind = kind
	this.Name = name
	this.ProjectId = projectId
	this.RawUri = rawUri
	this.Seq = seq
	this.SpanId = spanId
	this.StartTime = startTime
	this.Status = status
	this.TenantId = tenantId
	this.TraceId = traceId
	this.UnmappedJson = unmappedJson
	return &this
}

// NewArchivedSpanRowWithDefaults instantiates a new ArchivedSpanRow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArchivedSpanRowWithDefaults() *ArchivedSpanRow {
	this := ArchivedSpanRow{}
	return &this
}

// GetAttributesJson returns the AttributesJson field value
func (o *ArchivedSpanRow) GetAttributesJson() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AttributesJson
}

// GetAttributesJsonOk returns a tuple with the AttributesJson field value
// and a boolean to check if the value has been set.
func (o *ArchivedSpanRow) GetAttributesJsonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttributesJson, true
}

// SetAttributesJson sets field value
func (o *ArchivedSpanRow) SetAttributesJson(v string) {
	o.AttributesJson = v
}

// GetCostAmountMicros returns the CostAmountMicros field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ArchivedSpanRow) GetCostAmountMicros() string {
	if o == nil || IsNil(o.CostAmountMicros.Get()) {
		var ret string
		return ret
	}
	return *o.CostAmountMicros.Get()
}

// GetCostAmountMicrosOk returns a tuple with the CostAmountMicros field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ArchivedSpanRow) GetCostAmountMicrosOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CostAmountMicros.Get(), o.CostAmountMicros.IsSet()
}

// HasCostAmountMicros returns a boolean if a field has been set.
func (o *ArchivedSpanRow) HasCostAmountMicros() bool {
	if o != nil && o.CostAmountMicros.IsSet() {
		return true
	}

	return false
}

// SetCostAmountMicros gets a reference to the given NullableString and assigns it to the CostAmountMicros field.
func (o *ArchivedSpanRow) SetCostAmountMicros(v string) {
	o.CostAmountMicros.Set(&v)
}
// SetCostAmountMicrosNil sets the value for CostAmountMicros to be an explicit nil
func (o *ArchivedSpanRow) SetCostAmountMicrosNil() {
	o.CostAmountMicros.Set(nil)
}

// UnsetCostAmountMicros ensures that no value is present for CostAmountMicros, not even an explicit nil
func (o *ArchivedSpanRow) UnsetCostAmountMicros() {
	o.CostAmountMicros.Unset()
}

// GetCostCurrency returns the CostCurrency field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ArchivedSpanRow) GetCostCurrency() string {
	if o == nil || IsNil(o.CostCurrency.Get()) {
		var ret string
		return ret
	}
	return *o.CostCurrency.Get()
}

// GetCostCurrencyOk returns a tuple with the CostCurrency field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ArchivedSpanRow) GetCostCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CostCurrency.Get(), o.CostCurrency.IsSet()
}

// HasCostCurrency returns a boolean if a field has been set.
func (o *ArchivedSpanRow) HasCostCurrency() bool {
	if o != nil && o.CostCurrency.IsSet() {
		return true
	}

	return false
}

// SetCostCurrency gets a reference to the given NullableString and assigns it to the CostCurrency field.
func (o *ArchivedSpanRow) SetCostCurrency(v string) {
	o.CostCurrency.Set(&v)
}
// SetCostCurrencyNil sets the value for CostCurrency to be an explicit nil
func (o *ArchivedSpanRow) SetCostCurrencyNil() {
	o.CostCurrency.Set(nil)
}

// UnsetCostCurrency ensures that no value is present for CostCurrency, not even an explicit nil
func (o *ArchivedSpanRow) UnsetCostCurrency() {
	o.CostCurrency.Unset()
}

// GetEndTime returns the EndTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ArchivedSpanRow) GetEndTime() string {
	if o == nil || IsNil(o.EndTime.Get()) {
		var ret string
		return ret
	}
	return *o.EndTime.Get()
}

// GetEndTimeOk returns a tuple with the EndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ArchivedSpanRow) GetEndTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndTime.Get(), o.EndTime.IsSet()
}

// HasEndTime returns a boolean if a field has been set.
func (o *ArchivedSpanRow) HasEndTime() bool {
	if o != nil && o.EndTime.IsSet() {
		return true
	}

	return false
}

// SetEndTime gets a reference to the given NullableString and assigns it to the EndTime field.
func (o *ArchivedSpanRow) SetEndTime(v string) {
	o.EndTime.Set(&v)
}
// SetEndTimeNil sets the value for EndTime to be an explicit nil
func (o *ArchivedSpanRow) SetEndTimeNil() {
	o.EndTime.Set(nil)
}

// UnsetEndTime ensures that no value is present for EndTime, not even an explicit nil
func (o *ArchivedSpanRow) UnsetEndTime() {
	o.EndTime.Unset()
}

// GetEnvironmentId returns the EnvironmentId field value
func (o *ArchivedSpanRow) GetEnvironmentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EnvironmentId
}

// GetEnvironmentIdOk returns a tuple with the EnvironmentId field value
// and a boolean to check if the value has been set.
func (o *ArchivedSpanRow) GetEnvironmentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvironmentId, true
}

// SetEnvironmentId sets field value
func (o *ArchivedSpanRow) SetEnvironmentId(v string) {
	o.EnvironmentId = v
}

// GetInputTokens returns the InputTokens field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ArchivedSpanRow) GetInputTokens() string {
	if o == nil || IsNil(o.InputTokens.Get()) {
		var ret string
		return ret
	}
	return *o.InputTokens.Get()
}

// GetInputTokensOk returns a tuple with the InputTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ArchivedSpanRow) GetInputTokensOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.InputTokens.Get(), o.InputTokens.IsSet()
}

// HasInputTokens returns a boolean if a field has been set.
func (o *ArchivedSpanRow) HasInputTokens() bool {
	if o != nil && o.InputTokens.IsSet() {
		return true
	}

	return false
}

// SetInputTokens gets a reference to the given NullableString and assigns it to the InputTokens field.
func (o *ArchivedSpanRow) SetInputTokens(v string) {
	o.InputTokens.Set(&v)
}
// SetInputTokensNil sets the value for InputTokens to be an explicit nil
func (o *ArchivedSpanRow) SetInputTokensNil() {
	o.InputTokens.Set(nil)
}

// UnsetInputTokens ensures that no value is present for InputTokens, not even an explicit nil
func (o *ArchivedSpanRow) UnsetInputTokens() {
	o.InputTokens.Unset()
}

// GetInputUri returns the InputUri field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ArchivedSpanRow) GetInputUri() string {
	if o == nil || IsNil(o.InputUri.Get()) {
		var ret string
		return ret
	}
	return *o.InputUri.Get()
}

// GetInputUriOk returns a tuple with the InputUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ArchivedSpanRow) GetInputUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.InputUri.Get(), o.InputUri.IsSet()
}

// HasInputUri returns a boolean if a field has been set.
func (o *ArchivedSpanRow) HasInputUri() bool {
	if o != nil && o.InputUri.IsSet() {
		return true
	}

	return false
}

// SetInputUri gets a reference to the given NullableString and assigns it to the InputUri field.
func (o *ArchivedSpanRow) SetInputUri(v string) {
	o.InputUri.Set(&v)
}
// SetInputUriNil sets the value for InputUri to be an explicit nil
func (o *ArchivedSpanRow) SetInputUriNil() {
	o.InputUri.Set(nil)
}

// UnsetInputUri ensures that no value is present for InputUri, not even an explicit nil
func (o *ArchivedSpanRow) UnsetInputUri() {
	o.InputUri.Unset()
}

// GetKind returns the Kind field value
func (o *ArchivedSpanRow) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *ArchivedSpanRow) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *ArchivedSpanRow) SetKind(v string) {
	o.Kind = v
}

// GetModelName returns the ModelName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ArchivedSpanRow) GetModelName() string {
	if o == nil || IsNil(o.ModelName.Get()) {
		var ret string
		return ret
	}
	return *o.ModelName.Get()
}

// GetModelNameOk returns a tuple with the ModelName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ArchivedSpanRow) GetModelNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ModelName.Get(), o.ModelName.IsSet()
}

// HasModelName returns a boolean if a field has been set.
func (o *ArchivedSpanRow) HasModelName() bool {
	if o != nil && o.ModelName.IsSet() {
		return true
	}

	return false
}

// SetModelName gets a reference to the given NullableString and assigns it to the ModelName field.
func (o *ArchivedSpanRow) SetModelName(v string) {
	o.ModelName.Set(&v)
}
// SetModelNameNil sets the value for ModelName to be an explicit nil
func (o *ArchivedSpanRow) SetModelNameNil() {
	o.ModelName.Set(nil)
}

// UnsetModelName ensures that no value is present for ModelName, not even an explicit nil
func (o *ArchivedSpanRow) UnsetModelName() {
	o.ModelName.Unset()
}

// GetModelProvider returns the ModelProvider field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ArchivedSpanRow) GetModelProvider() string {
	if o == nil || IsNil(o.ModelProvider.Get()) {
		var ret string
		return ret
	}
	return *o.ModelProvider.Get()
}

// GetModelProviderOk returns a tuple with the ModelProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ArchivedSpanRow) GetModelProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ModelProvider.Get(), o.ModelProvider.IsSet()
}

// HasModelProvider returns a boolean if a field has been set.
func (o *ArchivedSpanRow) HasModelProvider() bool {
	if o != nil && o.ModelProvider.IsSet() {
		return true
	}

	return false
}

// SetModelProvider gets a reference to the given NullableString and assigns it to the ModelProvider field.
func (o *ArchivedSpanRow) SetModelProvider(v string) {
	o.ModelProvider.Set(&v)
}
// SetModelProviderNil sets the value for ModelProvider to be an explicit nil
func (o *ArchivedSpanRow) SetModelProviderNil() {
	o.ModelProvider.Set(nil)
}

// UnsetModelProvider ensures that no value is present for ModelProvider, not even an explicit nil
func (o *ArchivedSpanRow) UnsetModelProvider() {
	o.ModelProvider.Unset()
}

// GetName returns the Name field value
func (o *ArchivedSpanRow) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ArchivedSpanRow) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ArchivedSpanRow) SetName(v string) {
	o.Name = v
}

// GetOutputTokens returns the OutputTokens field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ArchivedSpanRow) GetOutputTokens() string {
	if o == nil || IsNil(o.OutputTokens.Get()) {
		var ret string
		return ret
	}
	return *o.OutputTokens.Get()
}

// GetOutputTokensOk returns a tuple with the OutputTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ArchivedSpanRow) GetOutputTokensOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OutputTokens.Get(), o.OutputTokens.IsSet()
}

// HasOutputTokens returns a boolean if a field has been set.
func (o *ArchivedSpanRow) HasOutputTokens() bool {
	if o != nil && o.OutputTokens.IsSet() {
		return true
	}

	return false
}

// SetOutputTokens gets a reference to the given NullableString and assigns it to the OutputTokens field.
func (o *ArchivedSpanRow) SetOutputTokens(v string) {
	o.OutputTokens.Set(&v)
}
// SetOutputTokensNil sets the value for OutputTokens to be an explicit nil
func (o *ArchivedSpanRow) SetOutputTokensNil() {
	o.OutputTokens.Set(nil)
}

// UnsetOutputTokens ensures that no value is present for OutputTokens, not even an explicit nil
func (o *ArchivedSpanRow) UnsetOutputTokens() {
	o.OutputTokens.Unset()
}

// GetOutputUri returns the OutputUri field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ArchivedSpanRow) GetOutputUri() string {
	if o == nil || IsNil(o.OutputUri.Get()) {
		var ret string
		return ret
	}
	return *o.OutputUri.Get()
}

// GetOutputUriOk returns a tuple with the OutputUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ArchivedSpanRow) GetOutputUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OutputUri.Get(), o.OutputUri.IsSet()
}

// HasOutputUri returns a boolean if a field has been set.
func (o *ArchivedSpanRow) HasOutputUri() bool {
	if o != nil && o.OutputUri.IsSet() {
		return true
	}

	return false
}

// SetOutputUri gets a reference to the given NullableString and assigns it to the OutputUri field.
func (o *ArchivedSpanRow) SetOutputUri(v string) {
	o.OutputUri.Set(&v)
}
// SetOutputUriNil sets the value for OutputUri to be an explicit nil
func (o *ArchivedSpanRow) SetOutputUriNil() {
	o.OutputUri.Set(nil)
}

// UnsetOutputUri ensures that no value is present for OutputUri, not even an explicit nil
func (o *ArchivedSpanRow) UnsetOutputUri() {
	o.OutputUri.Unset()
}

// GetParentSpanId returns the ParentSpanId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ArchivedSpanRow) GetParentSpanId() string {
	if o == nil || IsNil(o.ParentSpanId.Get()) {
		var ret string
		return ret
	}
	return *o.ParentSpanId.Get()
}

// GetParentSpanIdOk returns a tuple with the ParentSpanId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ArchivedSpanRow) GetParentSpanIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentSpanId.Get(), o.ParentSpanId.IsSet()
}

// HasParentSpanId returns a boolean if a field has been set.
func (o *ArchivedSpanRow) HasParentSpanId() bool {
	if o != nil && o.ParentSpanId.IsSet() {
		return true
	}

	return false
}

// SetParentSpanId gets a reference to the given NullableString and assigns it to the ParentSpanId field.
func (o *ArchivedSpanRow) SetParentSpanId(v string) {
	o.ParentSpanId.Set(&v)
}
// SetParentSpanIdNil sets the value for ParentSpanId to be an explicit nil
func (o *ArchivedSpanRow) SetParentSpanIdNil() {
	o.ParentSpanId.Set(nil)
}

// UnsetParentSpanId ensures that no value is present for ParentSpanId, not even an explicit nil
func (o *ArchivedSpanRow) UnsetParentSpanId() {
	o.ParentSpanId.Unset()
}

// GetProjectId returns the ProjectId field value
func (o *ArchivedSpanRow) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *ArchivedSpanRow) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *ArchivedSpanRow) SetProjectId(v string) {
	o.ProjectId = v
}

// GetRawUri returns the RawUri field value
func (o *ArchivedSpanRow) GetRawUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RawUri
}

// GetRawUriOk returns a tuple with the RawUri field value
// and a boolean to check if the value has been set.
func (o *ArchivedSpanRow) GetRawUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RawUri, true
}

// SetRawUri sets field value
func (o *ArchivedSpanRow) SetRawUri(v string) {
	o.RawUri = v
}

// GetReasoningTokens returns the ReasoningTokens field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ArchivedSpanRow) GetReasoningTokens() string {
	if o == nil || IsNil(o.ReasoningTokens.Get()) {
		var ret string
		return ret
	}
	return *o.ReasoningTokens.Get()
}

// GetReasoningTokensOk returns a tuple with the ReasoningTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ArchivedSpanRow) GetReasoningTokensOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReasoningTokens.Get(), o.ReasoningTokens.IsSet()
}

// HasReasoningTokens returns a boolean if a field has been set.
func (o *ArchivedSpanRow) HasReasoningTokens() bool {
	if o != nil && o.ReasoningTokens.IsSet() {
		return true
	}

	return false
}

// SetReasoningTokens gets a reference to the given NullableString and assigns it to the ReasoningTokens field.
func (o *ArchivedSpanRow) SetReasoningTokens(v string) {
	o.ReasoningTokens.Set(&v)
}
// SetReasoningTokensNil sets the value for ReasoningTokens to be an explicit nil
func (o *ArchivedSpanRow) SetReasoningTokensNil() {
	o.ReasoningTokens.Set(nil)
}

// UnsetReasoningTokens ensures that no value is present for ReasoningTokens, not even an explicit nil
func (o *ArchivedSpanRow) UnsetReasoningTokens() {
	o.ReasoningTokens.Unset()
}

// GetSeq returns the Seq field value
func (o *ArchivedSpanRow) GetSeq() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Seq
}

// GetSeqOk returns a tuple with the Seq field value
// and a boolean to check if the value has been set.
func (o *ArchivedSpanRow) GetSeqOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Seq, true
}

// SetSeq sets field value
func (o *ArchivedSpanRow) SetSeq(v int64) {
	o.Seq = v
}

// GetSpanId returns the SpanId field value
func (o *ArchivedSpanRow) GetSpanId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SpanId
}

// GetSpanIdOk returns a tuple with the SpanId field value
// and a boolean to check if the value has been set.
func (o *ArchivedSpanRow) GetSpanIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SpanId, true
}

// SetSpanId sets field value
func (o *ArchivedSpanRow) SetSpanId(v string) {
	o.SpanId = v
}

// GetStartTime returns the StartTime field value
func (o *ArchivedSpanRow) GetStartTime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value
// and a boolean to check if the value has been set.
func (o *ArchivedSpanRow) GetStartTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTime, true
}

// SetStartTime sets field value
func (o *ArchivedSpanRow) SetStartTime(v string) {
	o.StartTime = v
}

// GetStatus returns the Status field value
func (o *ArchivedSpanRow) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ArchivedSpanRow) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ArchivedSpanRow) SetStatus(v string) {
	o.Status = v
}

// GetTenantId returns the TenantId field value
func (o *ArchivedSpanRow) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *ArchivedSpanRow) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *ArchivedSpanRow) SetTenantId(v string) {
	o.TenantId = v
}

// GetTraceId returns the TraceId field value
func (o *ArchivedSpanRow) GetTraceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TraceId
}

// GetTraceIdOk returns a tuple with the TraceId field value
// and a boolean to check if the value has been set.
func (o *ArchivedSpanRow) GetTraceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TraceId, true
}

// SetTraceId sets field value
func (o *ArchivedSpanRow) SetTraceId(v string) {
	o.TraceId = v
}

// GetUnmappedJson returns the UnmappedJson field value
func (o *ArchivedSpanRow) GetUnmappedJson() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UnmappedJson
}

// GetUnmappedJsonOk returns a tuple with the UnmappedJson field value
// and a boolean to check if the value has been set.
func (o *ArchivedSpanRow) GetUnmappedJsonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnmappedJson, true
}

// SetUnmappedJson sets field value
func (o *ArchivedSpanRow) SetUnmappedJson(v string) {
	o.UnmappedJson = v
}

func (o ArchivedSpanRow) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArchivedSpanRow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["attributes_json"] = o.AttributesJson
	if o.CostAmountMicros.IsSet() {
		toSerialize["cost_amount_micros"] = o.CostAmountMicros.Get()
	}
	if o.CostCurrency.IsSet() {
		toSerialize["cost_currency"] = o.CostCurrency.Get()
	}
	if o.EndTime.IsSet() {
		toSerialize["end_time"] = o.EndTime.Get()
	}
	toSerialize["environment_id"] = o.EnvironmentId
	if o.InputTokens.IsSet() {
		toSerialize["input_tokens"] = o.InputTokens.Get()
	}
	if o.InputUri.IsSet() {
		toSerialize["input_uri"] = o.InputUri.Get()
	}
	toSerialize["kind"] = o.Kind
	if o.ModelName.IsSet() {
		toSerialize["model_name"] = o.ModelName.Get()
	}
	if o.ModelProvider.IsSet() {
		toSerialize["model_provider"] = o.ModelProvider.Get()
	}
	toSerialize["name"] = o.Name
	if o.OutputTokens.IsSet() {
		toSerialize["output_tokens"] = o.OutputTokens.Get()
	}
	if o.OutputUri.IsSet() {
		toSerialize["output_uri"] = o.OutputUri.Get()
	}
	if o.ParentSpanId.IsSet() {
		toSerialize["parent_span_id"] = o.ParentSpanId.Get()
	}
	toSerialize["project_id"] = o.ProjectId
	toSerialize["raw_uri"] = o.RawUri
	if o.ReasoningTokens.IsSet() {
		toSerialize["reasoning_tokens"] = o.ReasoningTokens.Get()
	}
	toSerialize["seq"] = o.Seq
	toSerialize["span_id"] = o.SpanId
	toSerialize["start_time"] = o.StartTime
	toSerialize["status"] = o.Status
	toSerialize["tenant_id"] = o.TenantId
	toSerialize["trace_id"] = o.TraceId
	toSerialize["unmapped_json"] = o.UnmappedJson
	return toSerialize, nil
}

func (o *ArchivedSpanRow) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"attributes_json",
		"environment_id",
		"kind",
		"name",
		"project_id",
		"raw_uri",
		"seq",
		"span_id",
		"start_time",
		"status",
		"tenant_id",
		"trace_id",
		"unmapped_json",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varArchivedSpanRow := _ArchivedSpanRow{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varArchivedSpanRow)

	if err != nil {
		return err
	}

	*o = ArchivedSpanRow(varArchivedSpanRow)

	return err
}

type NullableArchivedSpanRow struct {
	value *ArchivedSpanRow
	isSet bool
}

func (v NullableArchivedSpanRow) Get() *ArchivedSpanRow {
	return v.value
}

func (v *NullableArchivedSpanRow) Set(val *ArchivedSpanRow) {
	v.value = val
	v.isSet = true
}

func (v NullableArchivedSpanRow) IsSet() bool {
	return v.isSet
}

func (v *NullableArchivedSpanRow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArchivedSpanRow(val *ArchivedSpanRow) *NullableArchivedSpanRow {
	return &NullableArchivedSpanRow{value: val, isSet: true}
}

func (v NullableArchivedSpanRow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArchivedSpanRow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


