/*
Beater API

Agent observability, evaluation, gating, and human-review APIs for Beater

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package beaterclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ImportSourceHttpRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImportSourceHttpRequest{}

// ImportSourceHttpRequest Request body for the unified import endpoint. The `source` field selects a registered [`beater_ingest::SourceImporter`] (e.g. `temporal_history`, `native`); `payload` is that source's document (Temporal `History` JSON, a native span list, …). Everything flows through the same downstream ingest pipeline as OTLP — there are no source-specific routes.
type ImportSourceHttpRequest struct {
	Payload interface{} `json:"payload,omitempty"`
	// Registered importer key, e.g. `temporal_history` or `native`.
	Source string `json:"source"`
}

type _ImportSourceHttpRequest ImportSourceHttpRequest

// NewImportSourceHttpRequest instantiates a new ImportSourceHttpRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImportSourceHttpRequest(source string) *ImportSourceHttpRequest {
	this := ImportSourceHttpRequest{}
	this.Source = source
	return &this
}

// NewImportSourceHttpRequestWithDefaults instantiates a new ImportSourceHttpRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImportSourceHttpRequestWithDefaults() *ImportSourceHttpRequest {
	this := ImportSourceHttpRequest{}
	return &this
}

// GetPayload returns the Payload field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ImportSourceHttpRequest) GetPayload() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ImportSourceHttpRequest) GetPayloadOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Payload) {
		return nil, false
	}
	return &o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *ImportSourceHttpRequest) HasPayload() bool {
	if o != nil && !IsNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given interface{} and assigns it to the Payload field.
func (o *ImportSourceHttpRequest) SetPayload(v interface{}) {
	o.Payload = v
}

// GetSource returns the Source field value
func (o *ImportSourceHttpRequest) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *ImportSourceHttpRequest) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *ImportSourceHttpRequest) SetSource(v string) {
	o.Source = v
}

func (o ImportSourceHttpRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImportSourceHttpRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Payload != nil {
		toSerialize["payload"] = o.Payload
	}
	toSerialize["source"] = o.Source
	return toSerialize, nil
}

func (o *ImportSourceHttpRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"source",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImportSourceHttpRequest := _ImportSourceHttpRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varImportSourceHttpRequest)

	if err != nil {
		return err
	}

	*o = ImportSourceHttpRequest(varImportSourceHttpRequest)

	return err
}

type NullableImportSourceHttpRequest struct {
	value *ImportSourceHttpRequest
	isSet bool
}

func (v NullableImportSourceHttpRequest) Get() *ImportSourceHttpRequest {
	return v.value
}

func (v *NullableImportSourceHttpRequest) Set(val *ImportSourceHttpRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableImportSourceHttpRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableImportSourceHttpRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImportSourceHttpRequest(val *ImportSourceHttpRequest) *NullableImportSourceHttpRequest {
	return &NullableImportSourceHttpRequest{value: val, isSet: true}
}

func (v NullableImportSourceHttpRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImportSourceHttpRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


