/*
Beater API

Agent observability, evaluation, gating, and human-review APIs for Beater

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package beaterclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GatePolicy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatePolicy{}

// GatePolicy struct for GatePolicy
type GatePolicy struct {
	Alpha float64 `json:"alpha"`
	ComparisonCount int32 `json:"comparison_count"`
	MaxRegression float64 `json:"max_regression"`
	MinSampleSize int32 `json:"min_sample_size"`
}

type _GatePolicy GatePolicy

// NewGatePolicy instantiates a new GatePolicy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatePolicy(alpha float64, comparisonCount int32, maxRegression float64, minSampleSize int32) *GatePolicy {
	this := GatePolicy{}
	this.Alpha = alpha
	this.ComparisonCount = comparisonCount
	this.MaxRegression = maxRegression
	this.MinSampleSize = minSampleSize
	return &this
}

// NewGatePolicyWithDefaults instantiates a new GatePolicy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatePolicyWithDefaults() *GatePolicy {
	this := GatePolicy{}
	return &this
}

// GetAlpha returns the Alpha field value
func (o *GatePolicy) GetAlpha() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Alpha
}

// GetAlphaOk returns a tuple with the Alpha field value
// and a boolean to check if the value has been set.
func (o *GatePolicy) GetAlphaOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Alpha, true
}

// SetAlpha sets field value
func (o *GatePolicy) SetAlpha(v float64) {
	o.Alpha = v
}

// GetComparisonCount returns the ComparisonCount field value
func (o *GatePolicy) GetComparisonCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ComparisonCount
}

// GetComparisonCountOk returns a tuple with the ComparisonCount field value
// and a boolean to check if the value has been set.
func (o *GatePolicy) GetComparisonCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ComparisonCount, true
}

// SetComparisonCount sets field value
func (o *GatePolicy) SetComparisonCount(v int32) {
	o.ComparisonCount = v
}

// GetMaxRegression returns the MaxRegression field value
func (o *GatePolicy) GetMaxRegression() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.MaxRegression
}

// GetMaxRegressionOk returns a tuple with the MaxRegression field value
// and a boolean to check if the value has been set.
func (o *GatePolicy) GetMaxRegressionOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxRegression, true
}

// SetMaxRegression sets field value
func (o *GatePolicy) SetMaxRegression(v float64) {
	o.MaxRegression = v
}

// GetMinSampleSize returns the MinSampleSize field value
func (o *GatePolicy) GetMinSampleSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MinSampleSize
}

// GetMinSampleSizeOk returns a tuple with the MinSampleSize field value
// and a boolean to check if the value has been set.
func (o *GatePolicy) GetMinSampleSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinSampleSize, true
}

// SetMinSampleSize sets field value
func (o *GatePolicy) SetMinSampleSize(v int32) {
	o.MinSampleSize = v
}

func (o GatePolicy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatePolicy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["alpha"] = o.Alpha
	toSerialize["comparison_count"] = o.ComparisonCount
	toSerialize["max_regression"] = o.MaxRegression
	toSerialize["min_sample_size"] = o.MinSampleSize
	return toSerialize, nil
}

func (o *GatePolicy) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"alpha",
		"comparison_count",
		"max_regression",
		"min_sample_size",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGatePolicy := _GatePolicy{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGatePolicy)

	if err != nil {
		return err
	}

	*o = GatePolicy(varGatePolicy)

	return err
}

type NullableGatePolicy struct {
	value *GatePolicy
	isSet bool
}

func (v NullableGatePolicy) Get() *GatePolicy {
	return v.value
}

func (v *NullableGatePolicy) Set(val *GatePolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableGatePolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableGatePolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatePolicy(val *GatePolicy) *NullableGatePolicy {
	return &NullableGatePolicy{value: val, isSet: true}
}

func (v NullableGatePolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatePolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


