/*
Beater API

Agent observability, evaluation, gating, and human-review APIs for Beater

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package beaterclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateProviderSecretHttpRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateProviderSecretHttpRequest{}

// CreateProviderSecretHttpRequest struct for CreateProviderSecretHttpRequest
type CreateProviderSecretHttpRequest struct {
	DisplayName string `json:"display_name"`
	Provider string `json:"provider"`
	SecretValue string `json:"secret_value"`
}

type _CreateProviderSecretHttpRequest CreateProviderSecretHttpRequest

// NewCreateProviderSecretHttpRequest instantiates a new CreateProviderSecretHttpRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateProviderSecretHttpRequest(displayName string, provider string, secretValue string) *CreateProviderSecretHttpRequest {
	this := CreateProviderSecretHttpRequest{}
	this.DisplayName = displayName
	this.Provider = provider
	this.SecretValue = secretValue
	return &this
}

// NewCreateProviderSecretHttpRequestWithDefaults instantiates a new CreateProviderSecretHttpRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateProviderSecretHttpRequestWithDefaults() *CreateProviderSecretHttpRequest {
	this := CreateProviderSecretHttpRequest{}
	return &this
}

// GetDisplayName returns the DisplayName field value
func (o *CreateProviderSecretHttpRequest) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *CreateProviderSecretHttpRequest) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *CreateProviderSecretHttpRequest) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetProvider returns the Provider field value
func (o *CreateProviderSecretHttpRequest) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *CreateProviderSecretHttpRequest) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *CreateProviderSecretHttpRequest) SetProvider(v string) {
	o.Provider = v
}

// GetSecretValue returns the SecretValue field value
func (o *CreateProviderSecretHttpRequest) GetSecretValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecretValue
}

// GetSecretValueOk returns a tuple with the SecretValue field value
// and a boolean to check if the value has been set.
func (o *CreateProviderSecretHttpRequest) GetSecretValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecretValue, true
}

// SetSecretValue sets field value
func (o *CreateProviderSecretHttpRequest) SetSecretValue(v string) {
	o.SecretValue = v
}

func (o CreateProviderSecretHttpRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateProviderSecretHttpRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["display_name"] = o.DisplayName
	toSerialize["provider"] = o.Provider
	toSerialize["secret_value"] = o.SecretValue
	return toSerialize, nil
}

func (o *CreateProviderSecretHttpRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"display_name",
		"provider",
		"secret_value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateProviderSecretHttpRequest := _CreateProviderSecretHttpRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateProviderSecretHttpRequest)

	if err != nil {
		return err
	}

	*o = CreateProviderSecretHttpRequest(varCreateProviderSecretHttpRequest)

	return err
}

type NullableCreateProviderSecretHttpRequest struct {
	value *CreateProviderSecretHttpRequest
	isSet bool
}

func (v NullableCreateProviderSecretHttpRequest) Get() *CreateProviderSecretHttpRequest {
	return v.value
}

func (v *NullableCreateProviderSecretHttpRequest) Set(val *CreateProviderSecretHttpRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateProviderSecretHttpRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateProviderSecretHttpRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateProviderSecretHttpRequest(val *CreateProviderSecretHttpRequest) *NullableCreateProviderSecretHttpRequest {
	return &NullableCreateProviderSecretHttpRequest{value: val, isSet: true}
}

func (v NullableCreateProviderSecretHttpRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateProviderSecretHttpRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


