/*
Beater API

Agent observability, evaluation, gating, and human-review APIs for Beater

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package beaterclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PromptVersionDiff type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PromptVersionDiff{}

// PromptVersionDiff struct for PromptVersionDiff
type PromptVersionDiff struct {
	FromVersionId string `json:"from_version_id"`
	Lines []DiffLine `json:"lines"`
	ToVersionId string `json:"to_version_id"`
}

type _PromptVersionDiff PromptVersionDiff

// NewPromptVersionDiff instantiates a new PromptVersionDiff object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPromptVersionDiff(fromVersionId string, lines []DiffLine, toVersionId string) *PromptVersionDiff {
	this := PromptVersionDiff{}
	this.FromVersionId = fromVersionId
	this.Lines = lines
	this.ToVersionId = toVersionId
	return &this
}

// NewPromptVersionDiffWithDefaults instantiates a new PromptVersionDiff object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPromptVersionDiffWithDefaults() *PromptVersionDiff {
	this := PromptVersionDiff{}
	return &this
}

// GetFromVersionId returns the FromVersionId field value
func (o *PromptVersionDiff) GetFromVersionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FromVersionId
}

// GetFromVersionIdOk returns a tuple with the FromVersionId field value
// and a boolean to check if the value has been set.
func (o *PromptVersionDiff) GetFromVersionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FromVersionId, true
}

// SetFromVersionId sets field value
func (o *PromptVersionDiff) SetFromVersionId(v string) {
	o.FromVersionId = v
}

// GetLines returns the Lines field value
func (o *PromptVersionDiff) GetLines() []DiffLine {
	if o == nil {
		var ret []DiffLine
		return ret
	}

	return o.Lines
}

// GetLinesOk returns a tuple with the Lines field value
// and a boolean to check if the value has been set.
func (o *PromptVersionDiff) GetLinesOk() ([]DiffLine, bool) {
	if o == nil {
		return nil, false
	}
	return o.Lines, true
}

// SetLines sets field value
func (o *PromptVersionDiff) SetLines(v []DiffLine) {
	o.Lines = v
}

// GetToVersionId returns the ToVersionId field value
func (o *PromptVersionDiff) GetToVersionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ToVersionId
}

// GetToVersionIdOk returns a tuple with the ToVersionId field value
// and a boolean to check if the value has been set.
func (o *PromptVersionDiff) GetToVersionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ToVersionId, true
}

// SetToVersionId sets field value
func (o *PromptVersionDiff) SetToVersionId(v string) {
	o.ToVersionId = v
}

func (o PromptVersionDiff) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PromptVersionDiff) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["from_version_id"] = o.FromVersionId
	toSerialize["lines"] = o.Lines
	toSerialize["to_version_id"] = o.ToVersionId
	return toSerialize, nil
}

func (o *PromptVersionDiff) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"from_version_id",
		"lines",
		"to_version_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPromptVersionDiff := _PromptVersionDiff{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPromptVersionDiff)

	if err != nil {
		return err
	}

	*o = PromptVersionDiff(varPromptVersionDiff)

	return err
}

type NullablePromptVersionDiff struct {
	value *PromptVersionDiff
	isSet bool
}

func (v NullablePromptVersionDiff) Get() *PromptVersionDiff {
	return v.value
}

func (v *NullablePromptVersionDiff) Set(val *PromptVersionDiff) {
	v.value = val
	v.isSet = true
}

func (v NullablePromptVersionDiff) IsSet() bool {
	return v.isSet
}

func (v *NullablePromptVersionDiff) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePromptVersionDiff(val *PromptVersionDiff) *NullablePromptVersionDiff {
	return &NullablePromptVersionDiff{value: val, isSet: true}
}

func (v NullablePromptVersionDiff) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePromptVersionDiff) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


