/*
Beater API

Agent observability, evaluation, gating, and human-review APIs for Beater

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package beaterclient

import (
	"encoding/json"
	"fmt"
)

// DiffLineKind the model 'DiffLineKind'
type DiffLineKind string

// List of DiffLineKind
const (
	DIFFLINEKIND_UNCHANGED DiffLineKind = "unchanged"
	DIFFLINEKIND_ADDED DiffLineKind = "added"
	DIFFLINEKIND_REMOVED DiffLineKind = "removed"
)

// All allowed values of DiffLineKind enum
var AllowedDiffLineKindEnumValues = []DiffLineKind{
	"unchanged",
	"added",
	"removed",
}

func (v *DiffLineKind) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DiffLineKind(value)
	for _, existing := range AllowedDiffLineKindEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DiffLineKind", value)
}

// NewDiffLineKindFromValue returns a pointer to a valid DiffLineKind
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDiffLineKindFromValue(v string) (*DiffLineKind, error) {
	ev := DiffLineKind(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DiffLineKind: valid values are %v", v, AllowedDiffLineKindEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DiffLineKind) IsValid() bool {
	for _, existing := range AllowedDiffLineKindEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to DiffLineKind value
func (v DiffLineKind) Ptr() *DiffLineKind {
	return &v
}

type NullableDiffLineKind struct {
	value *DiffLineKind
	isSet bool
}

func (v NullableDiffLineKind) Get() *DiffLineKind {
	return v.value
}

func (v *NullableDiffLineKind) Set(val *DiffLineKind) {
	v.value = val
	v.isSet = true
}

func (v NullableDiffLineKind) IsSet() bool {
	return v.isSet
}

func (v *NullableDiffLineKind) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiffLineKind(val *DiffLineKind) *NullableDiffLineKind {
	return &NullableDiffLineKind{value: val, isSet: true}
}

func (v NullableDiffLineKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiffLineKind) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

