/* tslint:disable */
/* eslint-disable */
/**
 * Palette API
 * Agent observability, evaluation, gating, and human-review APIs for Palette
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateProviderSecretHttpRequest,
  ErrorResponse,
  ProviderSecretMetadata,
  RevokedProviderSecret,
} from '../models/index';
import {
    CreateProviderSecretHttpRequestFromJSON,
    CreateProviderSecretHttpRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ProviderSecretMetadataFromJSON,
    ProviderSecretMetadataToJSON,
    RevokedProviderSecretFromJSON,
    RevokedProviderSecretToJSON,
} from '../models/index';

export interface ProviderSecretsCreateRequest {
    tenantId: string;
    projectId: string;
    createProviderSecretHttpRequest: CreateProviderSecretHttpRequest;
    authorization?: string | null;
    xPaletteApiKey?: string | null;
    xPaletteProjectId?: string | null;
    xPaletteEnvironmentId?: string | null;
}

export interface ProviderSecretsListRequest {
    tenantId: string;
    projectId: string;
    authorization?: string | null;
    xPaletteApiKey?: string | null;
    xPaletteProjectId?: string | null;
    xPaletteEnvironmentId?: string | null;
}

export interface ProviderSecretsRevokeRequest {
    tenantId: string;
    projectId: string;
    providerSecretId: string;
    authorization?: string | null;
    xPaletteApiKey?: string | null;
    xPaletteProjectId?: string | null;
    xPaletteEnvironmentId?: string | null;
}

/**
 * 
 */
export class ProviderSecretsApi extends runtime.BaseAPI {

    /**
     */
    async providerSecretsCreateRaw(requestParameters: ProviderSecretsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProviderSecretMetadata>> {
        if (requestParameters['tenantId'] == null) {
            throw new runtime.RequiredError(
                'tenantId',
                'Required parameter "tenantId" was null or undefined when calling providerSecretsCreate().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling providerSecretsCreate().'
            );
        }

        if (requestParameters['createProviderSecretHttpRequest'] == null) {
            throw new runtime.RequiredError(
                'createProviderSecretHttpRequest',
                'Required parameter "createProviderSecretHttpRequest" was null or undefined when calling providerSecretsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xPaletteApiKey'] != null) {
            headerParameters['x-palette-api-key'] = String(requestParameters['xPaletteApiKey']);
        }

        if (requestParameters['xPaletteProjectId'] != null) {
            headerParameters['x-palette-project-id'] = String(requestParameters['xPaletteProjectId']);
        }

        if (requestParameters['xPaletteEnvironmentId'] != null) {
            headerParameters['x-palette-environment-id'] = String(requestParameters['xPaletteEnvironmentId']);
        }

        const response = await this.request({
            path: `/v1/provider-secrets/{tenant_id}/{project_id}`.replace(`{${"tenant_id"}}`, encodeURIComponent(String(requestParameters['tenantId']))).replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateProviderSecretHttpRequestToJSON(requestParameters['createProviderSecretHttpRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProviderSecretMetadataFromJSON(jsonValue));
    }

    /**
     */
    async providerSecretsCreate(requestParameters: ProviderSecretsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProviderSecretMetadata> {
        const response = await this.providerSecretsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async providerSecretsListRaw(requestParameters: ProviderSecretsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProviderSecretMetadata>>> {
        if (requestParameters['tenantId'] == null) {
            throw new runtime.RequiredError(
                'tenantId',
                'Required parameter "tenantId" was null or undefined when calling providerSecretsList().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling providerSecretsList().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xPaletteApiKey'] != null) {
            headerParameters['x-palette-api-key'] = String(requestParameters['xPaletteApiKey']);
        }

        if (requestParameters['xPaletteProjectId'] != null) {
            headerParameters['x-palette-project-id'] = String(requestParameters['xPaletteProjectId']);
        }

        if (requestParameters['xPaletteEnvironmentId'] != null) {
            headerParameters['x-palette-environment-id'] = String(requestParameters['xPaletteEnvironmentId']);
        }

        const response = await this.request({
            path: `/v1/provider-secrets/{tenant_id}/{project_id}`.replace(`{${"tenant_id"}}`, encodeURIComponent(String(requestParameters['tenantId']))).replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProviderSecretMetadataFromJSON));
    }

    /**
     */
    async providerSecretsList(requestParameters: ProviderSecretsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProviderSecretMetadata>> {
        const response = await this.providerSecretsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async providerSecretsRevokeRaw(requestParameters: ProviderSecretsRevokeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RevokedProviderSecret>> {
        if (requestParameters['tenantId'] == null) {
            throw new runtime.RequiredError(
                'tenantId',
                'Required parameter "tenantId" was null or undefined when calling providerSecretsRevoke().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling providerSecretsRevoke().'
            );
        }

        if (requestParameters['providerSecretId'] == null) {
            throw new runtime.RequiredError(
                'providerSecretId',
                'Required parameter "providerSecretId" was null or undefined when calling providerSecretsRevoke().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xPaletteApiKey'] != null) {
            headerParameters['x-palette-api-key'] = String(requestParameters['xPaletteApiKey']);
        }

        if (requestParameters['xPaletteProjectId'] != null) {
            headerParameters['x-palette-project-id'] = String(requestParameters['xPaletteProjectId']);
        }

        if (requestParameters['xPaletteEnvironmentId'] != null) {
            headerParameters['x-palette-environment-id'] = String(requestParameters['xPaletteEnvironmentId']);
        }

        const response = await this.request({
            path: `/v1/provider-secrets/{tenant_id}/{project_id}/{provider_secret_id}/revoke`.replace(`{${"tenant_id"}}`, encodeURIComponent(String(requestParameters['tenantId']))).replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId']))).replace(`{${"provider_secret_id"}}`, encodeURIComponent(String(requestParameters['providerSecretId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RevokedProviderSecretFromJSON(jsonValue));
    }

    /**
     */
    async providerSecretsRevoke(requestParameters: ProviderSecretsRevokeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RevokedProviderSecret> {
        const response = await this.providerSecretsRevokeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
