/* tslint:disable */
/* eslint-disable */
/**
 * Palette API
 * Agent observability, evaluation, gating, and human-review APIs for Palette
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateScenarioRequest,
  ListScenariosResponse,
  MineScenariosRequest,
  MineScenariosResponse,
  Scenario,
  Status,
} from '../models/index';
import {
    CreateScenarioRequestFromJSON,
    CreateScenarioRequestToJSON,
    ListScenariosResponseFromJSON,
    ListScenariosResponseToJSON,
    MineScenariosRequestFromJSON,
    MineScenariosRequestToJSON,
    MineScenariosResponseFromJSON,
    MineScenariosResponseToJSON,
    ScenarioFromJSON,
    ScenarioToJSON,
    StatusFromJSON,
    StatusToJSON,
} from '../models/index';

export interface ScenariosCreateRequest {
    tenantId: string;
    projectId: string;
    createScenarioRequest: CreateScenarioRequest;
    authorization?: string | null;
    xPaletteApiKey?: string | null;
    xPaletteProjectId?: string | null;
    xPaletteEnvironmentId?: string | null;
}

export interface ScenariosGetRequest {
    tenantId: string;
    projectId: string;
    scenarioId: string;
    authorization?: string | null;
    xPaletteApiKey?: string | null;
    xPaletteProjectId?: string | null;
    xPaletteEnvironmentId?: string | null;
}

export interface ScenariosListRequest {
    tenantId: string;
    projectId: string;
    pageSize?: number;
    pageToken?: string;
    authorization?: string | null;
    xPaletteApiKey?: string | null;
    xPaletteProjectId?: string | null;
    xPaletteEnvironmentId?: string | null;
}

export interface ScenariosMineRequest {
    tenantId: string;
    projectId: string;
    mineScenariosRequest: MineScenariosRequest;
    authorization?: string | null;
    xPaletteApiKey?: string | null;
    xPaletteProjectId?: string | null;
    xPaletteEnvironmentId?: string | null;
}

/**
 * 
 */
export class ScenariosApi extends runtime.BaseAPI {

    /**
     */
    async scenariosCreateRaw(requestParameters: ScenariosCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Scenario>> {
        if (requestParameters['tenantId'] == null) {
            throw new runtime.RequiredError(
                'tenantId',
                'Required parameter "tenantId" was null or undefined when calling scenariosCreate().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling scenariosCreate().'
            );
        }

        if (requestParameters['createScenarioRequest'] == null) {
            throw new runtime.RequiredError(
                'createScenarioRequest',
                'Required parameter "createScenarioRequest" was null or undefined when calling scenariosCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xPaletteApiKey'] != null) {
            headerParameters['x-palette-api-key'] = String(requestParameters['xPaletteApiKey']);
        }

        if (requestParameters['xPaletteProjectId'] != null) {
            headerParameters['x-palette-project-id'] = String(requestParameters['xPaletteProjectId']);
        }

        if (requestParameters['xPaletteEnvironmentId'] != null) {
            headerParameters['x-palette-environment-id'] = String(requestParameters['xPaletteEnvironmentId']);
        }

        const response = await this.request({
            path: `/v1/scenarios/{tenantId}/{projectId}`.replace(`{${"tenantId"}}`, encodeURIComponent(String(requestParameters['tenantId']))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateScenarioRequestToJSON(requestParameters['createScenarioRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScenarioFromJSON(jsonValue));
    }

    /**
     */
    async scenariosCreate(requestParameters: ScenariosCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Scenario> {
        const response = await this.scenariosCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async scenariosGetRaw(requestParameters: ScenariosGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Scenario>> {
        if (requestParameters['tenantId'] == null) {
            throw new runtime.RequiredError(
                'tenantId',
                'Required parameter "tenantId" was null or undefined when calling scenariosGet().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling scenariosGet().'
            );
        }

        if (requestParameters['scenarioId'] == null) {
            throw new runtime.RequiredError(
                'scenarioId',
                'Required parameter "scenarioId" was null or undefined when calling scenariosGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xPaletteApiKey'] != null) {
            headerParameters['x-palette-api-key'] = String(requestParameters['xPaletteApiKey']);
        }

        if (requestParameters['xPaletteProjectId'] != null) {
            headerParameters['x-palette-project-id'] = String(requestParameters['xPaletteProjectId']);
        }

        if (requestParameters['xPaletteEnvironmentId'] != null) {
            headerParameters['x-palette-environment-id'] = String(requestParameters['xPaletteEnvironmentId']);
        }

        const response = await this.request({
            path: `/v1/scenarios/{tenantId}/{projectId}/{scenarioId}`.replace(`{${"tenantId"}}`, encodeURIComponent(String(requestParameters['tenantId']))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))).replace(`{${"scenarioId"}}`, encodeURIComponent(String(requestParameters['scenarioId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScenarioFromJSON(jsonValue));
    }

    /**
     */
    async scenariosGet(requestParameters: ScenariosGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Scenario> {
        const response = await this.scenariosGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async scenariosListRaw(requestParameters: ScenariosListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListScenariosResponse>> {
        if (requestParameters['tenantId'] == null) {
            throw new runtime.RequiredError(
                'tenantId',
                'Required parameter "tenantId" was null or undefined when calling scenariosList().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling scenariosList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageToken'] != null) {
            queryParameters['pageToken'] = requestParameters['pageToken'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xPaletteApiKey'] != null) {
            headerParameters['x-palette-api-key'] = String(requestParameters['xPaletteApiKey']);
        }

        if (requestParameters['xPaletteProjectId'] != null) {
            headerParameters['x-palette-project-id'] = String(requestParameters['xPaletteProjectId']);
        }

        if (requestParameters['xPaletteEnvironmentId'] != null) {
            headerParameters['x-palette-environment-id'] = String(requestParameters['xPaletteEnvironmentId']);
        }

        const response = await this.request({
            path: `/v1/scenarios/{tenantId}/{projectId}`.replace(`{${"tenantId"}}`, encodeURIComponent(String(requestParameters['tenantId']))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListScenariosResponseFromJSON(jsonValue));
    }

    /**
     */
    async scenariosList(requestParameters: ScenariosListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListScenariosResponse> {
        const response = await this.scenariosListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async scenariosMineRaw(requestParameters: ScenariosMineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MineScenariosResponse>> {
        if (requestParameters['tenantId'] == null) {
            throw new runtime.RequiredError(
                'tenantId',
                'Required parameter "tenantId" was null or undefined when calling scenariosMine().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling scenariosMine().'
            );
        }

        if (requestParameters['mineScenariosRequest'] == null) {
            throw new runtime.RequiredError(
                'mineScenariosRequest',
                'Required parameter "mineScenariosRequest" was null or undefined when calling scenariosMine().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xPaletteApiKey'] != null) {
            headerParameters['x-palette-api-key'] = String(requestParameters['xPaletteApiKey']);
        }

        if (requestParameters['xPaletteProjectId'] != null) {
            headerParameters['x-palette-project-id'] = String(requestParameters['xPaletteProjectId']);
        }

        if (requestParameters['xPaletteEnvironmentId'] != null) {
            headerParameters['x-palette-environment-id'] = String(requestParameters['xPaletteEnvironmentId']);
        }

        const response = await this.request({
            path: `/v1/scenarios/{tenantId}/{projectId}/mine`.replace(`{${"tenantId"}}`, encodeURIComponent(String(requestParameters['tenantId']))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MineScenariosRequestToJSON(requestParameters['mineScenariosRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MineScenariosResponseFromJSON(jsonValue));
    }

    /**
     */
    async scenariosMine(requestParameters: ScenariosMineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MineScenariosResponse> {
        const response = await this.scenariosMineRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
