/**
 * Palette API
 * Agent observability, evaluation, gating, and human-review APIs for Palette
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * DatasetEvalReport.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_DatasetEvalReport_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_DatasetEvalReport_H_


#include "palette-client/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <vector>
#include "palette-client/model/EvalResult.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class EvalResult;


class  DatasetEvalReport
    : public ModelBase
{
public:
    DatasetEvalReport();
    virtual ~DatasetEvalReport();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// DatasetEvalReport members


    double getAggregateScore() const;
    bool aggregateScoreIsSet() const;
    void unsetAggregateScore();
    void setAggregateScore(double value);

    utility::datetime getCreatedAt() const;
    bool createdAtIsSet() const;
    void unsetCreatedAt();
    void setCreatedAt(const utility::datetime& value);

    utility::string_t getDatasetId() const;
    bool datasetIdIsSet() const;
    void unsetDatasetId();
    void setDatasetId(const utility::string_t& value);

    utility::string_t getDatasetVersionId() const;
    bool datasetVersionIdIsSet() const;
    void unsetDatasetVersionId();
    void setDatasetVersionId(const utility::string_t& value);

    utility::string_t getEvaluatorVersionId() const;
    bool evaluatorVersionIdIsSet() const;
    void unsetEvaluatorVersionId();
    void setEvaluatorVersionId(const utility::string_t& value);

    utility::string_t getProjectId() const;
    bool projectIdIsSet() const;
    void unsetProjectId();
    void setProjectId(const utility::string_t& value);

    utility::string_t getReportId() const;
    bool reportIdIsSet() const;
    void unsetReportId();
    void setReportId(const utility::string_t& value);

    int32_t getResultCount() const;
    bool resultCountIsSet() const;
    void unsetResultCount();
    void setResultCount(int32_t value);

    std::vector<std::shared_ptr<EvalResult>> getResults() const;
    bool resultsIsSet() const;
    void unsetResults();
    void setResults(const std::vector<std::shared_ptr<EvalResult>>& value);

    utility::string_t getTenantId() const;
    bool tenantIdIsSet() const;
    void unsetTenantId();
    void setTenantId(const utility::string_t& value);


protected:
    double m_AggregateScore;
    bool m_AggregateScoreIsSet;

    utility::datetime m_CreatedAt;
    bool m_CreatedAtIsSet;

    utility::string_t m_DatasetId;
    bool m_DatasetIdIsSet;

    utility::string_t m_DatasetVersionId;
    bool m_DatasetVersionIdIsSet;

    utility::string_t m_EvaluatorVersionId;
    bool m_EvaluatorVersionIdIsSet;

    utility::string_t m_ProjectId;
    bool m_ProjectIdIsSet;

    utility::string_t m_ReportId;
    bool m_ReportIdIsSet;

    int32_t m_ResultCount;
    bool m_ResultCountIsSet;

    std::vector<std::shared_ptr<EvalResult>> m_Results;
    bool m_ResultsIsSet;

    utility::string_t m_TenantId;
    bool m_TenantIdIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_DatasetEvalReport_H_ */
