/**
 * Palette API
 * Agent observability, evaluation, gating, and human-review APIs for Palette
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ReviewAnnotation.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_ReviewAnnotation_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_ReviewAnnotation_H_

#include <stdexcept>

#include "palette-client/ModelBase.h"

#include "palette-client/model/ReviewVerdict.h"
#include <cpprest/details/basic_types.h>
#include "palette-client/AnyType.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  ReviewAnnotation
    : public ModelBase
{
public:
    ReviewAnnotation();
    virtual ~ReviewAnnotation();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// ReviewAnnotation members


    utility::string_t getAnnotationId() const;
    bool annotationIdIsSet() const;
    void unsetAnnotationId();
    void setAnnotationId(const utility::string_t& value);

    utility::datetime getCreatedAt() const;
    bool createdAtIsSet() const;
    void unsetCreatedAt();
    void setCreatedAt(const utility::datetime& value);

    std::shared_ptr<AnyType> getPayload() const;
    bool payloadIsSet() const;
    void unsetPayload();
    void setPayload(const std::shared_ptr<AnyType>& value);

    utility::string_t getProjectId() const;
    bool projectIdIsSet() const;
    void unsetProjectId();
    void setProjectId(const utility::string_t& value);

    utility::string_t getQueueId() const;
    bool queueIdIsSet() const;
    void unsetQueueId();
    void setQueueId(const utility::string_t& value);

    utility::string_t getReviewerId() const;
    bool reviewerIdIsSet() const;
    void unsetReviewerId();
    void setReviewerId(const utility::string_t& value);

    utility::string_t getTaskId() const;
    bool taskIdIsSet() const;
    void unsetTaskId();
    void setTaskId(const utility::string_t& value);

    utility::string_t getTenantId() const;
    bool tenantIdIsSet() const;
    void unsetTenantId();
    void setTenantId(const utility::string_t& value);

    std::shared_ptr<ReviewVerdict> getVerdict() const;
    bool verdictIsSet() const;
    void unsetVerdict();
    void setVerdict(const std::shared_ptr<ReviewVerdict>& value);


protected:
    utility::string_t m_AnnotationId;
    bool m_AnnotationIdIsSet;

    utility::datetime m_CreatedAt;
    bool m_CreatedAtIsSet;

    std::shared_ptr<AnyType> m_Payload;
    bool m_PayloadIsSet;

    utility::string_t m_ProjectId;
    bool m_ProjectIdIsSet;

    utility::string_t m_QueueId;
    bool m_QueueIdIsSet;

    utility::string_t m_ReviewerId;
    bool m_ReviewerIdIsSet;

    utility::string_t m_TaskId;
    bool m_TaskIdIsSet;

    utility::string_t m_TenantId;
    bool m_TenantIdIsSet;

    std::shared_ptr<ReviewVerdict> m_Verdict;
    bool m_VerdictIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_ReviewAnnotation_H_ */
