/**
 * Palette API
 * Agent observability, evaluation, gating, and human-review APIs for Palette
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ReviewTaskListResponse.h
 *
 *
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_ReviewTaskListResponse_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_ReviewTaskListResponse_H_


#include "palette-client/ModelBase.h"

#include "palette-client/model/ReviewTask.h"
#include <cpprest/details/basic_types.h>
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class ReviewTask;


class  ReviewTaskListResponse
    : public ModelBase
{
public:
    ReviewTaskListResponse();
    virtual ~ReviewTaskListResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// ReviewTaskListResponse members


    utility::string_t getNextPageToken() const;
    bool nextPageTokenIsSet() const;
    void unsetNextPageToken();
    void setNextPageToken(const utility::string_t& value);

    std::vector<std::shared_ptr<ReviewTask>> getTasks() const;
    bool tasksIsSet() const;
    void unsetTasks();
    void setTasks(const std::vector<std::shared_ptr<ReviewTask>>& value);


protected:
    utility::string_t m_NextPageToken;
    bool m_NextPageTokenIsSet;

    std::vector<std::shared_ptr<ReviewTask>> m_Tasks;
    bool m_TasksIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_ReviewTaskListResponse_H_ */
