/*
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package ai.beater.client.api;

import ai.beater.client.ApiClient;
import ai.beater.client.ApiException;
import ai.beater.client.ApiResponse;
import ai.beater.client.Pair;

import ai.beater.client.model.CreateGateRequest;
import ai.beater.client.model.ErrorResponse;
import ai.beater.client.model.GateDefinition;
import ai.beater.client.model.GateRunReport;
import ai.beater.client.model.RunGateRequest;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class GatesApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public GatesApi() {
    this(new ApiClient());
  }

  public GatesApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * 
   * 
   * @param tenantId tenant_id (required)
   * @param projectId project_id (required)
   * @param createGateRequest  (required)
   * @param authorization Bearer API token for strict auth (optional)
   * @param xBeaterApiKey API key alternative for strict auth (optional)
   * @param xBeaterProjectId Strict-auth project scope (optional)
   * @param xBeaterEnvironmentId Strict-auth environment scope (optional)
   * @return GateDefinition
   * @throws ApiException if fails to make API call
   */
  public GateDefinition gatesCreateGate(String tenantId, String projectId, CreateGateRequest createGateRequest, String authorization, String xBeaterApiKey, String xBeaterProjectId, String xBeaterEnvironmentId) throws ApiException {
    ApiResponse<GateDefinition> localVarResponse = gatesCreateGateWithHttpInfo(tenantId, projectId, createGateRequest, authorization, xBeaterApiKey, xBeaterProjectId, xBeaterEnvironmentId);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param tenantId tenant_id (required)
   * @param projectId project_id (required)
   * @param createGateRequest  (required)
   * @param authorization Bearer API token for strict auth (optional)
   * @param xBeaterApiKey API key alternative for strict auth (optional)
   * @param xBeaterProjectId Strict-auth project scope (optional)
   * @param xBeaterEnvironmentId Strict-auth environment scope (optional)
   * @return ApiResponse&lt;GateDefinition&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GateDefinition> gatesCreateGateWithHttpInfo(String tenantId, String projectId, CreateGateRequest createGateRequest, String authorization, String xBeaterApiKey, String xBeaterProjectId, String xBeaterEnvironmentId) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = gatesCreateGateRequestBuilder(tenantId, projectId, createGateRequest, authorization, xBeaterApiKey, xBeaterProjectId, xBeaterEnvironmentId);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("gatesCreateGate", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<GateDefinition>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<GateDefinition>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<GateDefinition>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder gatesCreateGateRequestBuilder(String tenantId, String projectId, CreateGateRequest createGateRequest, String authorization, String xBeaterApiKey, String xBeaterProjectId, String xBeaterEnvironmentId) throws ApiException {
    // verify the required parameter 'tenantId' is set
    if (tenantId == null) {
      throw new ApiException(400, "Missing the required parameter 'tenantId' when calling gatesCreateGate");
    }
    // verify the required parameter 'projectId' is set
    if (projectId == null) {
      throw new ApiException(400, "Missing the required parameter 'projectId' when calling gatesCreateGate");
    }
    // verify the required parameter 'createGateRequest' is set
    if (createGateRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'createGateRequest' when calling gatesCreateGate");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/gates/{tenant_id}/{project_id}"
        .replace("{tenant_id}", ApiClient.urlEncode(tenantId.toString()))
        .replace("{project_id}", ApiClient.urlEncode(projectId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (authorization != null) {
      localVarRequestBuilder.header("authorization", authorization.toString());
    }
    if (xBeaterApiKey != null) {
      localVarRequestBuilder.header("x-beater-api-key", xBeaterApiKey.toString());
    }
    if (xBeaterProjectId != null) {
      localVarRequestBuilder.header("x-beater-project-id", xBeaterProjectId.toString());
    }
    if (xBeaterEnvironmentId != null) {
      localVarRequestBuilder.header("x-beater-environment-id", xBeaterEnvironmentId.toString());
    }
    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(createGateRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param tenantId tenant_id (required)
   * @param projectId project_id (required)
   * @param gateId gate_id (required)
   * @param runGateRequest  (required)
   * @param authorization Bearer API token for strict auth (optional)
   * @param xBeaterApiKey API key alternative for strict auth (optional)
   * @param xBeaterProjectId Strict-auth project scope (optional)
   * @param xBeaterEnvironmentId Strict-auth environment scope (optional)
   * @return GateRunReport
   * @throws ApiException if fails to make API call
   */
  public GateRunReport gatesRunGate(String tenantId, String projectId, String gateId, RunGateRequest runGateRequest, String authorization, String xBeaterApiKey, String xBeaterProjectId, String xBeaterEnvironmentId) throws ApiException {
    ApiResponse<GateRunReport> localVarResponse = gatesRunGateWithHttpInfo(tenantId, projectId, gateId, runGateRequest, authorization, xBeaterApiKey, xBeaterProjectId, xBeaterEnvironmentId);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param tenantId tenant_id (required)
   * @param projectId project_id (required)
   * @param gateId gate_id (required)
   * @param runGateRequest  (required)
   * @param authorization Bearer API token for strict auth (optional)
   * @param xBeaterApiKey API key alternative for strict auth (optional)
   * @param xBeaterProjectId Strict-auth project scope (optional)
   * @param xBeaterEnvironmentId Strict-auth environment scope (optional)
   * @return ApiResponse&lt;GateRunReport&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GateRunReport> gatesRunGateWithHttpInfo(String tenantId, String projectId, String gateId, RunGateRequest runGateRequest, String authorization, String xBeaterApiKey, String xBeaterProjectId, String xBeaterEnvironmentId) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = gatesRunGateRequestBuilder(tenantId, projectId, gateId, runGateRequest, authorization, xBeaterApiKey, xBeaterProjectId, xBeaterEnvironmentId);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("gatesRunGate", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<GateRunReport>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<GateRunReport>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<GateRunReport>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder gatesRunGateRequestBuilder(String tenantId, String projectId, String gateId, RunGateRequest runGateRequest, String authorization, String xBeaterApiKey, String xBeaterProjectId, String xBeaterEnvironmentId) throws ApiException {
    // verify the required parameter 'tenantId' is set
    if (tenantId == null) {
      throw new ApiException(400, "Missing the required parameter 'tenantId' when calling gatesRunGate");
    }
    // verify the required parameter 'projectId' is set
    if (projectId == null) {
      throw new ApiException(400, "Missing the required parameter 'projectId' when calling gatesRunGate");
    }
    // verify the required parameter 'gateId' is set
    if (gateId == null) {
      throw new ApiException(400, "Missing the required parameter 'gateId' when calling gatesRunGate");
    }
    // verify the required parameter 'runGateRequest' is set
    if (runGateRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'runGateRequest' when calling gatesRunGate");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/gates/{tenant_id}/{project_id}/{gate_id}/run"
        .replace("{tenant_id}", ApiClient.urlEncode(tenantId.toString()))
        .replace("{project_id}", ApiClient.urlEncode(projectId.toString()))
        .replace("{gate_id}", ApiClient.urlEncode(gateId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (authorization != null) {
      localVarRequestBuilder.header("authorization", authorization.toString());
    }
    if (xBeaterApiKey != null) {
      localVarRequestBuilder.header("x-beater-api-key", xBeaterApiKey.toString());
    }
    if (xBeaterProjectId != null) {
      localVarRequestBuilder.header("x-beater-project-id", xBeaterProjectId.toString());
    }
    if (xBeaterEnvironmentId != null) {
      localVarRequestBuilder.header("x-beater-environment-id", xBeaterEnvironmentId.toString());
    }
    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(runGateRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
