/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.beater.client.kotlin.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ai.beater.client.kotlin.models.DeadLetterReplayReport
import ai.beater.client.kotlin.models.ErrorResponse
import ai.beater.client.kotlin.models.ImportSourceHttpRequest
import ai.beater.client.kotlin.models.IngestOutcome
import ai.beater.client.kotlin.models.IngestQueueStatus
import ai.beater.client.kotlin.models.NativeIngestRequest
import ai.beater.client.kotlin.models.OtlpIngestOutcome
import ai.beater.client.kotlin.models.TraceIngestedDrainReport
import ai.beater.client.kotlin.models.TraceIngestedReconcileReport
import ai.beater.client.kotlin.models.TraceWriteDrainReport

import com.squareup.moshi.Json

import ai.beater.client.kotlin.infrastructure.ApiClient
import ai.beater.client.kotlin.infrastructure.ApiResponse
import ai.beater.client.kotlin.infrastructure.ClientException
import ai.beater.client.kotlin.infrastructure.ClientError
import ai.beater.client.kotlin.infrastructure.ServerException
import ai.beater.client.kotlin.infrastructure.ServerError
import ai.beater.client.kotlin.infrastructure.MultiValueMap
import ai.beater.client.kotlin.infrastructure.PartConfig
import ai.beater.client.kotlin.infrastructure.RequestConfig
import ai.beater.client.kotlin.infrastructure.RequestMethod
import ai.beater.client.kotlin.infrastructure.ResponseType
import ai.beater.client.kotlin.infrastructure.Success
import ai.beater.client.kotlin.infrastructure.toMultiValue

class IngestApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    /**
     * 
     * 
     * @param tenantId tenant_id
     * @param projectId project_id
     * @param limit  (optional)
     * @param authorization Bearer API token for strict auth (optional)
     * @param xBeaterApiKey API key alternative for strict auth (optional)
     * @param xBeaterProjectId Strict-auth project scope (optional)
     * @param xBeaterEnvironmentId Strict-auth environment scope (optional)
     * @return TraceIngestedDrainReport
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun drainTraceIngested(tenantId: kotlin.String, projectId: kotlin.String, limit: kotlin.Int? = null, authorization: kotlin.String? = null, xBeaterApiKey: kotlin.String? = null, xBeaterProjectId: kotlin.String? = null, xBeaterEnvironmentId: kotlin.String? = null) : TraceIngestedDrainReport {
        val localVarResponse = drainTraceIngestedWithHttpInfo(tenantId = tenantId, projectId = projectId, limit = limit, authorization = authorization, xBeaterApiKey = xBeaterApiKey, xBeaterProjectId = xBeaterProjectId, xBeaterEnvironmentId = xBeaterEnvironmentId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as TraceIngestedDrainReport
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * 
     * 
     * @param tenantId tenant_id
     * @param projectId project_id
     * @param limit  (optional)
     * @param authorization Bearer API token for strict auth (optional)
     * @param xBeaterApiKey API key alternative for strict auth (optional)
     * @param xBeaterProjectId Strict-auth project scope (optional)
     * @param xBeaterEnvironmentId Strict-auth environment scope (optional)
     * @return ApiResponse<TraceIngestedDrainReport?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun drainTraceIngestedWithHttpInfo(tenantId: kotlin.String, projectId: kotlin.String, limit: kotlin.Int?, authorization: kotlin.String?, xBeaterApiKey: kotlin.String?, xBeaterProjectId: kotlin.String?, xBeaterEnvironmentId: kotlin.String?) : ApiResponse<TraceIngestedDrainReport?> {
        val localVariableConfig = drainTraceIngestedRequestConfig(tenantId = tenantId, projectId = projectId, limit = limit, authorization = authorization, xBeaterApiKey = xBeaterApiKey, xBeaterProjectId = xBeaterProjectId, xBeaterEnvironmentId = xBeaterEnvironmentId)

        return request<Unit, TraceIngestedDrainReport>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation drainTraceIngested
     *
     * @param tenantId tenant_id
     * @param projectId project_id
     * @param limit  (optional)
     * @param authorization Bearer API token for strict auth (optional)
     * @param xBeaterApiKey API key alternative for strict auth (optional)
     * @param xBeaterProjectId Strict-auth project scope (optional)
     * @param xBeaterEnvironmentId Strict-auth environment scope (optional)
     * @return RequestConfig
     */
    fun drainTraceIngestedRequestConfig(tenantId: kotlin.String, projectId: kotlin.String, limit: kotlin.Int?, authorization: kotlin.String?, xBeaterApiKey: kotlin.String?, xBeaterProjectId: kotlin.String?, xBeaterEnvironmentId: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization?.apply { localVariableHeaders["authorization"] = this.toString() }
        xBeaterApiKey?.apply { localVariableHeaders["x-beater-api-key"] = this.toString() }
        xBeaterProjectId?.apply { localVariableHeaders["x-beater-project-id"] = this.toString() }
        xBeaterEnvironmentId?.apply { localVariableHeaders["x-beater-environment-id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/ingest/{tenant_id}/{project_id}/trace-ingested/drain".replace("{"+"tenant_id"+"}", encodeURIComponent(tenantId.toString())).replace("{"+"project_id"+"}", encodeURIComponent(projectId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * 
     * 
     * @param tenantId tenant_id
     * @param projectId project_id
     * @param limit  (optional)
     * @param authorization Bearer API token for strict auth (optional)
     * @param xBeaterApiKey API key alternative for strict auth (optional)
     * @param xBeaterProjectId Strict-auth project scope (optional)
     * @param xBeaterEnvironmentId Strict-auth environment scope (optional)
     * @return TraceWriteDrainReport
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun drainTraceWrites(tenantId: kotlin.String, projectId: kotlin.String, limit: kotlin.Int? = null, authorization: kotlin.String? = null, xBeaterApiKey: kotlin.String? = null, xBeaterProjectId: kotlin.String? = null, xBeaterEnvironmentId: kotlin.String? = null) : TraceWriteDrainReport {
        val localVarResponse = drainTraceWritesWithHttpInfo(tenantId = tenantId, projectId = projectId, limit = limit, authorization = authorization, xBeaterApiKey = xBeaterApiKey, xBeaterProjectId = xBeaterProjectId, xBeaterEnvironmentId = xBeaterEnvironmentId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as TraceWriteDrainReport
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * 
     * 
     * @param tenantId tenant_id
     * @param projectId project_id
     * @param limit  (optional)
     * @param authorization Bearer API token for strict auth (optional)
     * @param xBeaterApiKey API key alternative for strict auth (optional)
     * @param xBeaterProjectId Strict-auth project scope (optional)
     * @param xBeaterEnvironmentId Strict-auth environment scope (optional)
     * @return ApiResponse<TraceWriteDrainReport?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun drainTraceWritesWithHttpInfo(tenantId: kotlin.String, projectId: kotlin.String, limit: kotlin.Int?, authorization: kotlin.String?, xBeaterApiKey: kotlin.String?, xBeaterProjectId: kotlin.String?, xBeaterEnvironmentId: kotlin.String?) : ApiResponse<TraceWriteDrainReport?> {
        val localVariableConfig = drainTraceWritesRequestConfig(tenantId = tenantId, projectId = projectId, limit = limit, authorization = authorization, xBeaterApiKey = xBeaterApiKey, xBeaterProjectId = xBeaterProjectId, xBeaterEnvironmentId = xBeaterEnvironmentId)

        return request<Unit, TraceWriteDrainReport>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation drainTraceWrites
     *
     * @param tenantId tenant_id
     * @param projectId project_id
     * @param limit  (optional)
     * @param authorization Bearer API token for strict auth (optional)
     * @param xBeaterApiKey API key alternative for strict auth (optional)
     * @param xBeaterProjectId Strict-auth project scope (optional)
     * @param xBeaterEnvironmentId Strict-auth environment scope (optional)
     * @return RequestConfig
     */
    fun drainTraceWritesRequestConfig(tenantId: kotlin.String, projectId: kotlin.String, limit: kotlin.Int?, authorization: kotlin.String?, xBeaterApiKey: kotlin.String?, xBeaterProjectId: kotlin.String?, xBeaterEnvironmentId: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization?.apply { localVariableHeaders["authorization"] = this.toString() }
        xBeaterApiKey?.apply { localVariableHeaders["x-beater-api-key"] = this.toString() }
        xBeaterProjectId?.apply { localVariableHeaders["x-beater-project-id"] = this.toString() }
        xBeaterEnvironmentId?.apply { localVariableHeaders["x-beater-environment-id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/ingest/{tenant_id}/{project_id}/trace-writes/drain".replace("{"+"tenant_id"+"}", encodeURIComponent(tenantId.toString())).replace("{"+"project_id"+"}", encodeURIComponent(projectId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * 
     * 
     * @param tenantId tenant_id
     * @param projectId project_id
     * @param authorization Bearer API token for strict auth (optional)
     * @param xBeaterApiKey API key alternative for strict auth (optional)
     * @param xBeaterProjectId Strict-auth project scope (optional)
     * @param xBeaterEnvironmentId Strict-auth environment scope (optional)
     * @return IngestQueueStatus
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getIngestQueueStatus(tenantId: kotlin.String, projectId: kotlin.String, authorization: kotlin.String? = null, xBeaterApiKey: kotlin.String? = null, xBeaterProjectId: kotlin.String? = null, xBeaterEnvironmentId: kotlin.String? = null) : IngestQueueStatus {
        val localVarResponse = getIngestQueueStatusWithHttpInfo(tenantId = tenantId, projectId = projectId, authorization = authorization, xBeaterApiKey = xBeaterApiKey, xBeaterProjectId = xBeaterProjectId, xBeaterEnvironmentId = xBeaterEnvironmentId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IngestQueueStatus
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * 
     * 
     * @param tenantId tenant_id
     * @param projectId project_id
     * @param authorization Bearer API token for strict auth (optional)
     * @param xBeaterApiKey API key alternative for strict auth (optional)
     * @param xBeaterProjectId Strict-auth project scope (optional)
     * @param xBeaterEnvironmentId Strict-auth environment scope (optional)
     * @return ApiResponse<IngestQueueStatus?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getIngestQueueStatusWithHttpInfo(tenantId: kotlin.String, projectId: kotlin.String, authorization: kotlin.String?, xBeaterApiKey: kotlin.String?, xBeaterProjectId: kotlin.String?, xBeaterEnvironmentId: kotlin.String?) : ApiResponse<IngestQueueStatus?> {
        val localVariableConfig = getIngestQueueStatusRequestConfig(tenantId = tenantId, projectId = projectId, authorization = authorization, xBeaterApiKey = xBeaterApiKey, xBeaterProjectId = xBeaterProjectId, xBeaterEnvironmentId = xBeaterEnvironmentId)

        return request<Unit, IngestQueueStatus>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getIngestQueueStatus
     *
     * @param tenantId tenant_id
     * @param projectId project_id
     * @param authorization Bearer API token for strict auth (optional)
     * @param xBeaterApiKey API key alternative for strict auth (optional)
     * @param xBeaterProjectId Strict-auth project scope (optional)
     * @param xBeaterEnvironmentId Strict-auth environment scope (optional)
     * @return RequestConfig
     */
    fun getIngestQueueStatusRequestConfig(tenantId: kotlin.String, projectId: kotlin.String, authorization: kotlin.String?, xBeaterApiKey: kotlin.String?, xBeaterProjectId: kotlin.String?, xBeaterEnvironmentId: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization?.apply { localVariableHeaders["authorization"] = this.toString() }
        xBeaterApiKey?.apply { localVariableHeaders["x-beater-api-key"] = this.toString() }
        xBeaterProjectId?.apply { localVariableHeaders["x-beater-project-id"] = this.toString() }
        xBeaterEnvironmentId?.apply { localVariableHeaders["x-beater-environment-id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/ingest/{tenant_id}/{project_id}/queue".replace("{"+"tenant_id"+"}", encodeURIComponent(tenantId.toString())).replace("{"+"project_id"+"}", encodeURIComponent(projectId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * 
     * 
     * @param tenantId tenant_id
     * @param projectId project_id
     * @param environmentId environment_id
     * @param importSourceHttpRequest 
     * @param durability  (optional)
     * @param authorization Bearer API token for strict auth (optional)
     * @param xBeaterApiKey API key alternative for strict auth (optional)
     * @return IngestOutcome
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun importSource(tenantId: kotlin.String, projectId: kotlin.String, environmentId: kotlin.String, importSourceHttpRequest: ImportSourceHttpRequest, durability: kotlin.String? = null, authorization: kotlin.String? = null, xBeaterApiKey: kotlin.String? = null) : IngestOutcome {
        val localVarResponse = importSourceWithHttpInfo(tenantId = tenantId, projectId = projectId, environmentId = environmentId, importSourceHttpRequest = importSourceHttpRequest, durability = durability, authorization = authorization, xBeaterApiKey = xBeaterApiKey)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IngestOutcome
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * 
     * 
     * @param tenantId tenant_id
     * @param projectId project_id
     * @param environmentId environment_id
     * @param importSourceHttpRequest 
     * @param durability  (optional)
     * @param authorization Bearer API token for strict auth (optional)
     * @param xBeaterApiKey API key alternative for strict auth (optional)
     * @return ApiResponse<IngestOutcome?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun importSourceWithHttpInfo(tenantId: kotlin.String, projectId: kotlin.String, environmentId: kotlin.String, importSourceHttpRequest: ImportSourceHttpRequest, durability: kotlin.String?, authorization: kotlin.String?, xBeaterApiKey: kotlin.String?) : ApiResponse<IngestOutcome?> {
        val localVariableConfig = importSourceRequestConfig(tenantId = tenantId, projectId = projectId, environmentId = environmentId, importSourceHttpRequest = importSourceHttpRequest, durability = durability, authorization = authorization, xBeaterApiKey = xBeaterApiKey)

        return request<ImportSourceHttpRequest, IngestOutcome>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation importSource
     *
     * @param tenantId tenant_id
     * @param projectId project_id
     * @param environmentId environment_id
     * @param importSourceHttpRequest 
     * @param durability  (optional)
     * @param authorization Bearer API token for strict auth (optional)
     * @param xBeaterApiKey API key alternative for strict auth (optional)
     * @return RequestConfig
     */
    fun importSourceRequestConfig(tenantId: kotlin.String, projectId: kotlin.String, environmentId: kotlin.String, importSourceHttpRequest: ImportSourceHttpRequest, durability: kotlin.String?, authorization: kotlin.String?, xBeaterApiKey: kotlin.String?) : RequestConfig<ImportSourceHttpRequest> {
        val localVariableBody = importSourceHttpRequest
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (durability != null) {
                    put("durability", listOf(durability.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization?.apply { localVariableHeaders["authorization"] = this.toString() }
        xBeaterApiKey?.apply { localVariableHeaders["x-beater-api-key"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/import/{tenant_id}/{project_id}/{environment_id}".replace("{"+"tenant_id"+"}", encodeURIComponent(tenantId.toString())).replace("{"+"project_id"+"}", encodeURIComponent(projectId.toString())).replace("{"+"environment_id"+"}", encodeURIComponent(environmentId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * 
     * 
     * @param nativeIngestRequest 
     * @param durability  (optional)
     * @param authorization Bearer API token for strict auth (optional)
     * @param xBeaterApiKey API key alternative for strict auth (optional)
     * @param xBeaterProjectId Strict-auth project scope (optional)
     * @param xBeaterEnvironmentId Strict-auth environment scope (optional)
     * @return IngestOutcome
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun ingestNative(nativeIngestRequest: NativeIngestRequest, durability: kotlin.String? = null, authorization: kotlin.String? = null, xBeaterApiKey: kotlin.String? = null, xBeaterProjectId: kotlin.String? = null, xBeaterEnvironmentId: kotlin.String? = null) : IngestOutcome {
        val localVarResponse = ingestNativeWithHttpInfo(nativeIngestRequest = nativeIngestRequest, durability = durability, authorization = authorization, xBeaterApiKey = xBeaterApiKey, xBeaterProjectId = xBeaterProjectId, xBeaterEnvironmentId = xBeaterEnvironmentId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IngestOutcome
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * 
     * 
     * @param nativeIngestRequest 
     * @param durability  (optional)
     * @param authorization Bearer API token for strict auth (optional)
     * @param xBeaterApiKey API key alternative for strict auth (optional)
     * @param xBeaterProjectId Strict-auth project scope (optional)
     * @param xBeaterEnvironmentId Strict-auth environment scope (optional)
     * @return ApiResponse<IngestOutcome?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun ingestNativeWithHttpInfo(nativeIngestRequest: NativeIngestRequest, durability: kotlin.String?, authorization: kotlin.String?, xBeaterApiKey: kotlin.String?, xBeaterProjectId: kotlin.String?, xBeaterEnvironmentId: kotlin.String?) : ApiResponse<IngestOutcome?> {
        val localVariableConfig = ingestNativeRequestConfig(nativeIngestRequest = nativeIngestRequest, durability = durability, authorization = authorization, xBeaterApiKey = xBeaterApiKey, xBeaterProjectId = xBeaterProjectId, xBeaterEnvironmentId = xBeaterEnvironmentId)

        return request<NativeIngestRequest, IngestOutcome>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation ingestNative
     *
     * @param nativeIngestRequest 
     * @param durability  (optional)
     * @param authorization Bearer API token for strict auth (optional)
     * @param xBeaterApiKey API key alternative for strict auth (optional)
     * @param xBeaterProjectId Strict-auth project scope (optional)
     * @param xBeaterEnvironmentId Strict-auth environment scope (optional)
     * @return RequestConfig
     */
    fun ingestNativeRequestConfig(nativeIngestRequest: NativeIngestRequest, durability: kotlin.String?, authorization: kotlin.String?, xBeaterApiKey: kotlin.String?, xBeaterProjectId: kotlin.String?, xBeaterEnvironmentId: kotlin.String?) : RequestConfig<NativeIngestRequest> {
        val localVariableBody = nativeIngestRequest
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (durability != null) {
                    put("durability", listOf(durability.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization?.apply { localVariableHeaders["authorization"] = this.toString() }
        xBeaterApiKey?.apply { localVariableHeaders["x-beater-api-key"] = this.toString() }
        xBeaterProjectId?.apply { localVariableHeaders["x-beater-project-id"] = this.toString() }
        xBeaterEnvironmentId?.apply { localVariableHeaders["x-beater-environment-id"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/traces/native",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * 
     * 
     * @param tenantId tenant_id
     * @param projectId project_id
     * @param environmentId environment_id
     * @param durability  (optional)
     * @param authorization Bearer API token for strict auth (optional)
     * @param xBeaterApiKey API key alternative for strict auth (optional)
     * @param xBeaterProjectId Strict-auth project scope (optional)
     * @param xBeaterEnvironmentId Strict-auth environment scope (optional)
     * @return OtlpIngestOutcome
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun ingestOtlp(tenantId: kotlin.String, projectId: kotlin.String, environmentId: kotlin.String, durability: kotlin.String? = null, authorization: kotlin.String? = null, xBeaterApiKey: kotlin.String? = null, xBeaterProjectId: kotlin.String? = null, xBeaterEnvironmentId: kotlin.String? = null) : OtlpIngestOutcome {
        val localVarResponse = ingestOtlpWithHttpInfo(tenantId = tenantId, projectId = projectId, environmentId = environmentId, durability = durability, authorization = authorization, xBeaterApiKey = xBeaterApiKey, xBeaterProjectId = xBeaterProjectId, xBeaterEnvironmentId = xBeaterEnvironmentId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as OtlpIngestOutcome
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * 
     * 
     * @param tenantId tenant_id
     * @param projectId project_id
     * @param environmentId environment_id
     * @param durability  (optional)
     * @param authorization Bearer API token for strict auth (optional)
     * @param xBeaterApiKey API key alternative for strict auth (optional)
     * @param xBeaterProjectId Strict-auth project scope (optional)
     * @param xBeaterEnvironmentId Strict-auth environment scope (optional)
     * @return ApiResponse<OtlpIngestOutcome?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun ingestOtlpWithHttpInfo(tenantId: kotlin.String, projectId: kotlin.String, environmentId: kotlin.String, durability: kotlin.String?, authorization: kotlin.String?, xBeaterApiKey: kotlin.String?, xBeaterProjectId: kotlin.String?, xBeaterEnvironmentId: kotlin.String?) : ApiResponse<OtlpIngestOutcome?> {
        val localVariableConfig = ingestOtlpRequestConfig(tenantId = tenantId, projectId = projectId, environmentId = environmentId, durability = durability, authorization = authorization, xBeaterApiKey = xBeaterApiKey, xBeaterProjectId = xBeaterProjectId, xBeaterEnvironmentId = xBeaterEnvironmentId)

        return request<Unit, OtlpIngestOutcome>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation ingestOtlp
     *
     * @param tenantId tenant_id
     * @param projectId project_id
     * @param environmentId environment_id
     * @param durability  (optional)
     * @param authorization Bearer API token for strict auth (optional)
     * @param xBeaterApiKey API key alternative for strict auth (optional)
     * @param xBeaterProjectId Strict-auth project scope (optional)
     * @param xBeaterEnvironmentId Strict-auth environment scope (optional)
     * @return RequestConfig
     */
    fun ingestOtlpRequestConfig(tenantId: kotlin.String, projectId: kotlin.String, environmentId: kotlin.String, durability: kotlin.String?, authorization: kotlin.String?, xBeaterApiKey: kotlin.String?, xBeaterProjectId: kotlin.String?, xBeaterEnvironmentId: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (durability != null) {
                    put("durability", listOf(durability.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization?.apply { localVariableHeaders["authorization"] = this.toString() }
        xBeaterApiKey?.apply { localVariableHeaders["x-beater-api-key"] = this.toString() }
        xBeaterProjectId?.apply { localVariableHeaders["x-beater-project-id"] = this.toString() }
        xBeaterEnvironmentId?.apply { localVariableHeaders["x-beater-environment-id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/otlp/{tenant_id}/{project_id}/{environment_id}/v1/traces".replace("{"+"tenant_id"+"}", encodeURIComponent(tenantId.toString())).replace("{"+"project_id"+"}", encodeURIComponent(projectId.toString())).replace("{"+"environment_id"+"}", encodeURIComponent(environmentId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * 
     * 
     * @param tenantId tenant_id
     * @param projectId project_id
     * @param traceId trace_id
     * @param authorization Bearer API token for strict auth (optional)
     * @param xBeaterApiKey API key alternative for strict auth (optional)
     * @param xBeaterProjectId Strict-auth project scope (optional)
     * @param xBeaterEnvironmentId Strict-auth environment scope (optional)
     * @return TraceIngestedReconcileReport
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun reconcileTrace(tenantId: kotlin.String, projectId: kotlin.String, traceId: kotlin.String, authorization: kotlin.String? = null, xBeaterApiKey: kotlin.String? = null, xBeaterProjectId: kotlin.String? = null, xBeaterEnvironmentId: kotlin.String? = null) : TraceIngestedReconcileReport {
        val localVarResponse = reconcileTraceWithHttpInfo(tenantId = tenantId, projectId = projectId, traceId = traceId, authorization = authorization, xBeaterApiKey = xBeaterApiKey, xBeaterProjectId = xBeaterProjectId, xBeaterEnvironmentId = xBeaterEnvironmentId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as TraceIngestedReconcileReport
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * 
     * 
     * @param tenantId tenant_id
     * @param projectId project_id
     * @param traceId trace_id
     * @param authorization Bearer API token for strict auth (optional)
     * @param xBeaterApiKey API key alternative for strict auth (optional)
     * @param xBeaterProjectId Strict-auth project scope (optional)
     * @param xBeaterEnvironmentId Strict-auth environment scope (optional)
     * @return ApiResponse<TraceIngestedReconcileReport?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun reconcileTraceWithHttpInfo(tenantId: kotlin.String, projectId: kotlin.String, traceId: kotlin.String, authorization: kotlin.String?, xBeaterApiKey: kotlin.String?, xBeaterProjectId: kotlin.String?, xBeaterEnvironmentId: kotlin.String?) : ApiResponse<TraceIngestedReconcileReport?> {
        val localVariableConfig = reconcileTraceRequestConfig(tenantId = tenantId, projectId = projectId, traceId = traceId, authorization = authorization, xBeaterApiKey = xBeaterApiKey, xBeaterProjectId = xBeaterProjectId, xBeaterEnvironmentId = xBeaterEnvironmentId)

        return request<Unit, TraceIngestedReconcileReport>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation reconcileTrace
     *
     * @param tenantId tenant_id
     * @param projectId project_id
     * @param traceId trace_id
     * @param authorization Bearer API token for strict auth (optional)
     * @param xBeaterApiKey API key alternative for strict auth (optional)
     * @param xBeaterProjectId Strict-auth project scope (optional)
     * @param xBeaterEnvironmentId Strict-auth environment scope (optional)
     * @return RequestConfig
     */
    fun reconcileTraceRequestConfig(tenantId: kotlin.String, projectId: kotlin.String, traceId: kotlin.String, authorization: kotlin.String?, xBeaterApiKey: kotlin.String?, xBeaterProjectId: kotlin.String?, xBeaterEnvironmentId: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization?.apply { localVariableHeaders["authorization"] = this.toString() }
        xBeaterApiKey?.apply { localVariableHeaders["x-beater-api-key"] = this.toString() }
        xBeaterProjectId?.apply { localVariableHeaders["x-beater-project-id"] = this.toString() }
        xBeaterEnvironmentId?.apply { localVariableHeaders["x-beater-environment-id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/ingest/{tenant_id}/{project_id}/traces/{trace_id}/reconcile".replace("{"+"tenant_id"+"}", encodeURIComponent(tenantId.toString())).replace("{"+"project_id"+"}", encodeURIComponent(projectId.toString())).replace("{"+"trace_id"+"}", encodeURIComponent(traceId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * 
     * 
     * @param tenantId tenant_id
     * @param projectId project_id
     * @param messageId message_id
     * @param resetAttempts  (optional)
     * @param authorization Bearer API token for strict auth (optional)
     * @param xBeaterApiKey API key alternative for strict auth (optional)
     * @param xBeaterProjectId Strict-auth project scope (optional)
     * @param xBeaterEnvironmentId Strict-auth environment scope (optional)
     * @return DeadLetterReplayReport
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun replayDeadLetter(tenantId: kotlin.String, projectId: kotlin.String, messageId: kotlin.String, resetAttempts: kotlin.Boolean? = null, authorization: kotlin.String? = null, xBeaterApiKey: kotlin.String? = null, xBeaterProjectId: kotlin.String? = null, xBeaterEnvironmentId: kotlin.String? = null) : DeadLetterReplayReport {
        val localVarResponse = replayDeadLetterWithHttpInfo(tenantId = tenantId, projectId = projectId, messageId = messageId, resetAttempts = resetAttempts, authorization = authorization, xBeaterApiKey = xBeaterApiKey, xBeaterProjectId = xBeaterProjectId, xBeaterEnvironmentId = xBeaterEnvironmentId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as DeadLetterReplayReport
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * 
     * 
     * @param tenantId tenant_id
     * @param projectId project_id
     * @param messageId message_id
     * @param resetAttempts  (optional)
     * @param authorization Bearer API token for strict auth (optional)
     * @param xBeaterApiKey API key alternative for strict auth (optional)
     * @param xBeaterProjectId Strict-auth project scope (optional)
     * @param xBeaterEnvironmentId Strict-auth environment scope (optional)
     * @return ApiResponse<DeadLetterReplayReport?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun replayDeadLetterWithHttpInfo(tenantId: kotlin.String, projectId: kotlin.String, messageId: kotlin.String, resetAttempts: kotlin.Boolean?, authorization: kotlin.String?, xBeaterApiKey: kotlin.String?, xBeaterProjectId: kotlin.String?, xBeaterEnvironmentId: kotlin.String?) : ApiResponse<DeadLetterReplayReport?> {
        val localVariableConfig = replayDeadLetterRequestConfig(tenantId = tenantId, projectId = projectId, messageId = messageId, resetAttempts = resetAttempts, authorization = authorization, xBeaterApiKey = xBeaterApiKey, xBeaterProjectId = xBeaterProjectId, xBeaterEnvironmentId = xBeaterEnvironmentId)

        return request<Unit, DeadLetterReplayReport>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation replayDeadLetter
     *
     * @param tenantId tenant_id
     * @param projectId project_id
     * @param messageId message_id
     * @param resetAttempts  (optional)
     * @param authorization Bearer API token for strict auth (optional)
     * @param xBeaterApiKey API key alternative for strict auth (optional)
     * @param xBeaterProjectId Strict-auth project scope (optional)
     * @param xBeaterEnvironmentId Strict-auth environment scope (optional)
     * @return RequestConfig
     */
    fun replayDeadLetterRequestConfig(tenantId: kotlin.String, projectId: kotlin.String, messageId: kotlin.String, resetAttempts: kotlin.Boolean?, authorization: kotlin.String?, xBeaterApiKey: kotlin.String?, xBeaterProjectId: kotlin.String?, xBeaterEnvironmentId: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (resetAttempts != null) {
                    put("reset_attempts", listOf(resetAttempts.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization?.apply { localVariableHeaders["authorization"] = this.toString() }
        xBeaterApiKey?.apply { localVariableHeaders["x-beater-api-key"] = this.toString() }
        xBeaterProjectId?.apply { localVariableHeaders["x-beater-project-id"] = this.toString() }
        xBeaterEnvironmentId?.apply { localVariableHeaders["x-beater-environment-id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/ingest/{tenant_id}/{project_id}/dead-letters/{message_id}/replay".replace("{"+"tenant_id"+"}", encodeURIComponent(tenantId.toString())).replace("{"+"project_id"+"}", encodeURIComponent(projectId.toString())).replace("{"+"message_id"+"}", encodeURIComponent(messageId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
