/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.beater.client.kotlin.models

import ai.beater.client.kotlin.models.Money

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param baselineEvidence 
 * @param baselineOutput 
 * @param baselineScore 
 * @param candidateEvidence 
 * @param candidateOutput 
 * @param candidateScore 
 * @param caseId 
 * @param delta 
 * @param baselineCached 
 * @param baselineCost 
 * @param baselineJudgeCallId 
 * @param baselineTrace 
 * @param candidateCached 
 * @param candidateCost 
 * @param candidateJudgeCallId 
 * @param candidateTrace 
 * @param reference 
 */


data class CaseExperimentScore (

    @Json(name = "baseline_evidence")
    val baselineEvidence: kotlin.Any?,

    @Json(name = "baseline_output")
    val baselineOutput: kotlin.Any?,

    @Json(name = "baseline_score")
    val baselineScore: kotlin.Double,

    @Json(name = "candidate_evidence")
    val candidateEvidence: kotlin.Any?,

    @Json(name = "candidate_output")
    val candidateOutput: kotlin.Any?,

    @Json(name = "candidate_score")
    val candidateScore: kotlin.Double,

    @Json(name = "case_id")
    val caseId: kotlin.String,

    @Json(name = "delta")
    val delta: kotlin.Double,

    @Json(name = "baseline_cached")
    val baselineCached: kotlin.Boolean? = null,

    @Json(name = "baseline_cost")
    val baselineCost: Money? = null,

    @Json(name = "baseline_judge_call_id")
    val baselineJudgeCallId: kotlin.String? = null,

    @Json(name = "baseline_trace")
    val baselineTrace: kotlin.Any? = null,

    @Json(name = "candidate_cached")
    val candidateCached: kotlin.Boolean? = null,

    @Json(name = "candidate_cost")
    val candidateCost: Money? = null,

    @Json(name = "candidate_judge_call_id")
    val candidateJudgeCallId: kotlin.String? = null,

    @Json(name = "candidate_trace")
    val candidateTrace: kotlin.Any? = null,

    @Json(name = "reference")
    val reference: kotlin.Any? = null

) {


}

