/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.beater.client.kotlin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Request body for the unified import endpoint. The `source` field selects a registered [`beater_ingest::SourceImporter`] (e.g. `temporal_history`, `native`); `payload` is that source's document (Temporal `History` JSON, a native span list, …). Everything flows through the same downstream ingest pipeline as OTLP — there are no source-specific routes.
 *
 * @param source Registered importer key, e.g. `temporal_history` or `native`.
 * @param payload 
 */


data class ImportSourceHttpRequest (

    /* Registered importer key, e.g. `temporal_history` or `native`. */
    @Json(name = "source")
    val source: kotlin.String,

    @Json(name = "payload")
    val payload: kotlin.Any? = null

) {


}

