/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.beater.client.kotlin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param acceptedRaw 
 * @param acceptedSpans 
 * @param duplicateRaw 
 * @param duplicateSpans 
 */


data class WriteAck (

    @Json(name = "accepted_raw")
    val acceptedRaw: kotlin.Int,

    @Json(name = "accepted_spans")
    val acceptedSpans: kotlin.Int,

    @Json(name = "duplicate_raw")
    val duplicateRaw: kotlin.Int,

    @Json(name = "duplicate_spans")
    val duplicateSpans: kotlin.Int

) {


}

