=begin
#Beater API

#Agent observability, evaluation, gating, and human-review APIs for Beater

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BeaterClient::EvaluatorKindOneOf7
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe BeaterClient::EvaluatorKindOneOf7 do
  let(:instance) { BeaterClient::EvaluatorKindOneOf7.new }

  describe 'test an instance of EvaluatorKindOneOf7' do
    it 'should create an instance of EvaluatorKindOneOf7' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(BeaterClient::EvaluatorKindOneOf7)
    end
  end

  describe 'test attribute "dom_contains"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["browser_task_success"])
      # validator.allowable_values.each do |value|
      #   expect { instance.type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "url_contains"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
