# coding: utf-8

"""
    Beater API

    Agent observability, evaluation, gating, and human-review APIs for Beater

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from beater_client.models.evaluator_kind_one_of import EvaluatorKindOneOf
from beater_client.models.evaluator_kind_one_of1 import EvaluatorKindOneOf1
from beater_client.models.evaluator_kind_one_of2 import EvaluatorKindOneOf2
from beater_client.models.evaluator_kind_one_of3 import EvaluatorKindOneOf3
from beater_client.models.evaluator_kind_one_of4 import EvaluatorKindOneOf4
from beater_client.models.evaluator_kind_one_of5 import EvaluatorKindOneOf5
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

EVALUATORKIND_ONE_OF_SCHEMAS = ["EvaluatorKindOneOf", "EvaluatorKindOneOf1", "EvaluatorKindOneOf2", "EvaluatorKindOneOf3", "EvaluatorKindOneOf4", "EvaluatorKindOneOf5"]

class EvaluatorKind(BaseModel):
    """
    EvaluatorKind
    """
    # data type: EvaluatorKindOneOf
    oneof_schema_1_validator: Optional[EvaluatorKindOneOf] = None
    # data type: EvaluatorKindOneOf1
    oneof_schema_2_validator: Optional[EvaluatorKindOneOf1] = None
    # data type: EvaluatorKindOneOf2
    oneof_schema_3_validator: Optional[EvaluatorKindOneOf2] = None
    # data type: EvaluatorKindOneOf3
    oneof_schema_4_validator: Optional[EvaluatorKindOneOf3] = None
    # data type: EvaluatorKindOneOf4
    oneof_schema_5_validator: Optional[EvaluatorKindOneOf4] = None
    # data type: EvaluatorKindOneOf5
    oneof_schema_6_validator: Optional[EvaluatorKindOneOf5] = None
    actual_instance: Optional[Union[EvaluatorKindOneOf, EvaluatorKindOneOf1, EvaluatorKindOneOf2, EvaluatorKindOneOf3, EvaluatorKindOneOf4, EvaluatorKindOneOf5]] = None
    one_of_schemas: Set[str] = { "EvaluatorKindOneOf", "EvaluatorKindOneOf1", "EvaluatorKindOneOf2", "EvaluatorKindOneOf3", "EvaluatorKindOneOf4", "EvaluatorKindOneOf5" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = EvaluatorKind.model_construct()
        error_messages = []
        match = 0
        # validate data type: EvaluatorKindOneOf
        if not isinstance(v, EvaluatorKindOneOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EvaluatorKindOneOf`")
        else:
            match += 1
        # validate data type: EvaluatorKindOneOf1
        if not isinstance(v, EvaluatorKindOneOf1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EvaluatorKindOneOf1`")
        else:
            match += 1
        # validate data type: EvaluatorKindOneOf2
        if not isinstance(v, EvaluatorKindOneOf2):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EvaluatorKindOneOf2`")
        else:
            match += 1
        # validate data type: EvaluatorKindOneOf3
        if not isinstance(v, EvaluatorKindOneOf3):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EvaluatorKindOneOf3`")
        else:
            match += 1
        # validate data type: EvaluatorKindOneOf4
        if not isinstance(v, EvaluatorKindOneOf4):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EvaluatorKindOneOf4`")
        else:
            match += 1
        # validate data type: EvaluatorKindOneOf5
        if not isinstance(v, EvaluatorKindOneOf5):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EvaluatorKindOneOf5`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in EvaluatorKind with oneOf schemas: EvaluatorKindOneOf, EvaluatorKindOneOf1, EvaluatorKindOneOf2, EvaluatorKindOneOf3, EvaluatorKindOneOf4, EvaluatorKindOneOf5. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in EvaluatorKind with oneOf schemas: EvaluatorKindOneOf, EvaluatorKindOneOf1, EvaluatorKindOneOf2, EvaluatorKindOneOf3, EvaluatorKindOneOf4, EvaluatorKindOneOf5. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into EvaluatorKindOneOf
        try:
            instance.actual_instance = EvaluatorKindOneOf.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EvaluatorKindOneOf1
        try:
            instance.actual_instance = EvaluatorKindOneOf1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EvaluatorKindOneOf2
        try:
            instance.actual_instance = EvaluatorKindOneOf2.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EvaluatorKindOneOf3
        try:
            instance.actual_instance = EvaluatorKindOneOf3.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EvaluatorKindOneOf4
        try:
            instance.actual_instance = EvaluatorKindOneOf4.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EvaluatorKindOneOf5
        try:
            instance.actual_instance = EvaluatorKindOneOf5.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into EvaluatorKind with oneOf schemas: EvaluatorKindOneOf, EvaluatorKindOneOf1, EvaluatorKindOneOf2, EvaluatorKindOneOf3, EvaluatorKindOneOf4, EvaluatorKindOneOf5. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into EvaluatorKind with oneOf schemas: EvaluatorKindOneOf, EvaluatorKindOneOf1, EvaluatorKindOneOf2, EvaluatorKindOneOf3, EvaluatorKindOneOf4, EvaluatorKindOneOf5. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], EvaluatorKindOneOf, EvaluatorKindOneOf1, EvaluatorKindOneOf2, EvaluatorKindOneOf3, EvaluatorKindOneOf4, EvaluatorKindOneOf5]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


