/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.beater.client.kotlin.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.beater.client.kotlin.models.EnqueueReviewTaskFromTraceHttpRequest

class EnqueueReviewTaskFromTraceHttpRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EnqueueReviewTaskFromTraceHttpRequest
        //val modelInstance = EnqueueReviewTaskFromTraceHttpRequest()

        // to test the property `traceId`
        should("test traceId") {
            // uncomment below to test the property
            //modelInstance.traceId shouldBe ("TODO")
        }

        // to test the property `datasetCaseId`
        should("test datasetCaseId") {
            // uncomment below to test the property
            //modelInstance.datasetCaseId shouldBe ("TODO")
        }

        // to test the property `datasetId`
        should("test datasetId") {
            // uncomment below to test the property
            //modelInstance.datasetId shouldBe ("TODO")
        }

        // to test the property `priority`
        should("test priority") {
            // uncomment below to test the property
            //modelInstance.priority shouldBe ("TODO")
        }

        // to test the property `spanId`
        should("test spanId") {
            // uncomment below to test the property
            //modelInstance.spanId shouldBe ("TODO")
        }

        // to test the property `taskId`
        should("test taskId") {
            // uncomment below to test the property
            //modelInstance.taskId shouldBe ("TODO")
        }

    }
}
