/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.beater.client.kotlin.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.beater.client.kotlin.models.EvaluatorKindOneOf10

class EvaluatorKindOneOf10Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of EvaluatorKindOneOf10
        //val modelInstance = EvaluatorKindOneOf10()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

    }
}
