/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.beater.client.kotlin.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.beater.client.kotlin.models.TraceIngestedReconcileReport

class TraceIngestedReconcileReportTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TraceIngestedReconcileReport
        //val modelInstance = TraceIngestedReconcileReport()

        // to test the property `downstreamAccepted`
        should("test downstreamAccepted") {
            // uncomment below to test the property
            //modelInstance.downstreamAccepted shouldBe ("TODO")
        }

        // to test the property `downstreamDuplicate`
        should("test downstreamDuplicate") {
            // uncomment below to test the property
            //modelInstance.downstreamDuplicate shouldBe ("TODO")
        }

        // to test the property `downstreamQueued`
        should("test downstreamQueued") {
            // uncomment below to test the property
            //modelInstance.downstreamQueued shouldBe ("TODO")
        }

        // to test the property `projectId`
        should("test projectId") {
            // uncomment below to test the property
            //modelInstance.projectId shouldBe ("TODO")
        }

        // to test the property `spanCount`
        should("test spanCount") {
            // uncomment below to test the property
            //modelInstance.spanCount shouldBe ("TODO")
        }

        // to test the property `tenantId`
        should("test tenantId") {
            // uncomment below to test the property
            //modelInstance.tenantId shouldBe ("TODO")
        }

        // to test the property `traceId`
        should("test traceId") {
            // uncomment below to test the property
            //modelInstance.traceId shouldBe ("TODO")
        }

    }
}
