/*
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.beater.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OtlpIngestOutcome
 */
class OtlpIngestOutcomeTest {
    private final OtlpIngestOutcome model = new OtlpIngestOutcome();

    /**
     * Model tests for OtlpIngestOutcome
     */
    @Test
    void testOtlpIngestOutcome() {
        // TODO: test OtlpIngestOutcome
    }

    /**
     * Test the property 'acceptedRaw'
     */
    @Test
    void acceptedRawTest() {
        // TODO: test acceptedRaw
    }

    /**
     * Test the property 'acceptedSpans'
     */
    @Test
    void acceptedSpansTest() {
        // TODO: test acceptedSpans
    }

    /**
     * Test the property 'downstreamQueued'
     */
    @Test
    void downstreamQueuedTest() {
        // TODO: test downstreamQueued
    }

    /**
     * Test the property 'duplicateRaw'
     */
    @Test
    void duplicateRawTest() {
        // TODO: test duplicateRaw
    }

    /**
     * Test the property 'duplicateSpans'
     */
    @Test
    void duplicateSpansTest() {
        // TODO: test duplicateSpans
    }

}
