/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.beater.client.kotlin.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.beater.client.kotlin.apis.PromptsApi
import ai.beater.client.kotlin.models.AddPromptVersionRequest
import ai.beater.client.kotlin.models.CreatePromptRequest
import ai.beater.client.kotlin.models.CreatedPrompt
import ai.beater.client.kotlin.models.ErrorResponse
import ai.beater.client.kotlin.models.Prompt
import ai.beater.client.kotlin.models.PromptListResponse
import ai.beater.client.kotlin.models.PromptVersion
import ai.beater.client.kotlin.models.PromptVersionDiff
import ai.beater.client.kotlin.models.PromptVersionListResponse

class PromptsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PromptsApi
        //val apiInstance = PromptsApi()

        // to test addPromptVersion
        should("test addPromptVersion") {
            // uncomment below to test addPromptVersion
            //val tenantId : kotlin.String = tenantId_example // kotlin.String | tenant_id
            //val projectId : kotlin.String = projectId_example // kotlin.String | project_id
            //val promptId : kotlin.String = promptId_example // kotlin.String | prompt_id
            //val addPromptVersionRequest : AddPromptVersionRequest =  // AddPromptVersionRequest | 
            //val authorization : kotlin.String = authorization_example // kotlin.String | Bearer API token for strict auth
            //val xBeaterApiKey : kotlin.String = xBeaterApiKey_example // kotlin.String | API key alternative for strict auth
            //val xBeaterProjectId : kotlin.String = xBeaterProjectId_example // kotlin.String | Strict-auth project scope
            //val xBeaterEnvironmentId : kotlin.String = xBeaterEnvironmentId_example // kotlin.String | Strict-auth environment scope
            //val result : PromptVersion = apiInstance.addPromptVersion(tenantId, projectId, promptId, addPromptVersionRequest, authorization, xBeaterApiKey, xBeaterProjectId, xBeaterEnvironmentId)
            //result shouldBe ("TODO")
        }

        // to test createPrompt
        should("test createPrompt") {
            // uncomment below to test createPrompt
            //val tenantId : kotlin.String = tenantId_example // kotlin.String | tenant_id
            //val projectId : kotlin.String = projectId_example // kotlin.String | project_id
            //val createPromptRequest : CreatePromptRequest =  // CreatePromptRequest | 
            //val authorization : kotlin.String = authorization_example // kotlin.String | Bearer API token for strict auth
            //val xBeaterApiKey : kotlin.String = xBeaterApiKey_example // kotlin.String | API key alternative for strict auth
            //val xBeaterProjectId : kotlin.String = xBeaterProjectId_example // kotlin.String | Strict-auth project scope
            //val xBeaterEnvironmentId : kotlin.String = xBeaterEnvironmentId_example // kotlin.String | Strict-auth environment scope
            //val result : CreatedPrompt = apiInstance.createPrompt(tenantId, projectId, createPromptRequest, authorization, xBeaterApiKey, xBeaterProjectId, xBeaterEnvironmentId)
            //result shouldBe ("TODO")
        }

        // to test diffPromptVersions
        should("test diffPromptVersions") {
            // uncomment below to test diffPromptVersions
            //val tenantId : kotlin.String = tenantId_example // kotlin.String | tenant_id
            //val projectId : kotlin.String = projectId_example // kotlin.String | project_id
            //val promptId : kotlin.String = promptId_example // kotlin.String | prompt_id
            //val from : kotlin.String = from_example // kotlin.String | 
            //val to : kotlin.String = to_example // kotlin.String | 
            //val authorization : kotlin.String = authorization_example // kotlin.String | Bearer API token for strict auth
            //val xBeaterApiKey : kotlin.String = xBeaterApiKey_example // kotlin.String | API key alternative for strict auth
            //val xBeaterProjectId : kotlin.String = xBeaterProjectId_example // kotlin.String | Strict-auth project scope
            //val xBeaterEnvironmentId : kotlin.String = xBeaterEnvironmentId_example // kotlin.String | Strict-auth environment scope
            //val result : PromptVersionDiff = apiInstance.diffPromptVersions(tenantId, projectId, promptId, from, to, authorization, xBeaterApiKey, xBeaterProjectId, xBeaterEnvironmentId)
            //result shouldBe ("TODO")
        }

        // to test getPrompt
        should("test getPrompt") {
            // uncomment below to test getPrompt
            //val tenantId : kotlin.String = tenantId_example // kotlin.String | tenant_id
            //val projectId : kotlin.String = projectId_example // kotlin.String | project_id
            //val promptId : kotlin.String = promptId_example // kotlin.String | prompt_id
            //val authorization : kotlin.String = authorization_example // kotlin.String | Bearer API token for strict auth
            //val xBeaterApiKey : kotlin.String = xBeaterApiKey_example // kotlin.String | API key alternative for strict auth
            //val xBeaterProjectId : kotlin.String = xBeaterProjectId_example // kotlin.String | Strict-auth project scope
            //val xBeaterEnvironmentId : kotlin.String = xBeaterEnvironmentId_example // kotlin.String | Strict-auth environment scope
            //val result : Prompt = apiInstance.getPrompt(tenantId, projectId, promptId, authorization, xBeaterApiKey, xBeaterProjectId, xBeaterEnvironmentId)
            //result shouldBe ("TODO")
        }

        // to test listPromptVersions
        should("test listPromptVersions") {
            // uncomment below to test listPromptVersions
            //val tenantId : kotlin.String = tenantId_example // kotlin.String | tenant_id
            //val projectId : kotlin.String = projectId_example // kotlin.String | project_id
            //val promptId : kotlin.String = promptId_example // kotlin.String | prompt_id
            //val authorization : kotlin.String = authorization_example // kotlin.String | Bearer API token for strict auth
            //val xBeaterApiKey : kotlin.String = xBeaterApiKey_example // kotlin.String | API key alternative for strict auth
            //val xBeaterProjectId : kotlin.String = xBeaterProjectId_example // kotlin.String | Strict-auth project scope
            //val xBeaterEnvironmentId : kotlin.String = xBeaterEnvironmentId_example // kotlin.String | Strict-auth environment scope
            //val result : PromptVersionListResponse = apiInstance.listPromptVersions(tenantId, projectId, promptId, authorization, xBeaterApiKey, xBeaterProjectId, xBeaterEnvironmentId)
            //result shouldBe ("TODO")
        }

        // to test listPrompts
        should("test listPrompts") {
            // uncomment below to test listPrompts
            //val tenantId : kotlin.String = tenantId_example // kotlin.String | tenant_id
            //val projectId : kotlin.String = projectId_example // kotlin.String | project_id
            //val authorization : kotlin.String = authorization_example // kotlin.String | Bearer API token for strict auth
            //val xBeaterApiKey : kotlin.String = xBeaterApiKey_example // kotlin.String | API key alternative for strict auth
            //val xBeaterProjectId : kotlin.String = xBeaterProjectId_example // kotlin.String | Strict-auth project scope
            //val xBeaterEnvironmentId : kotlin.String = xBeaterEnvironmentId_example // kotlin.String | Strict-auth environment scope
            //val result : PromptListResponse = apiInstance.listPrompts(tenantId, projectId, authorization, xBeaterApiKey, xBeaterProjectId, xBeaterEnvironmentId)
            //result shouldBe ("TODO")
        }

    }
}
