/*
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConnectorTool : A single executable tool within a toolkit, carrying the metadata an agent needs to actually *call* it: the input JSON Schema, tags, and toolkit. This is the raw material for the prompting scaffold in [`crate::skill`].
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectorTool {
    /// What the tool does.
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    /// JSON Schema of the tool's `arguments`, verbatim from Composio. The agent loop uses this to construct valid calls; [`crate::skill`] renders it.
    #[serde(rename = "input_schema", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub input_schema: Option<Option<serde_json::Value>>,
    /// Human display name.
    #[serde(rename = "name")]
    pub name: String,
    /// `true` when the tool executes without a connected account.
    #[serde(rename = "no_auth", skip_serializing_if = "Option::is_none")]
    pub no_auth: Option<bool>,
    /// Tool slug passed to [`ComposioClient::execute`] (e.g. `GITHUB_CREATE_AN_ISSUE`).
    #[serde(rename = "slug")]
    pub slug: String,
    /// Free-form tags Composio assigns (categories, importance, …).
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    /// Owning toolkit slug (e.g. `github`), when known.
    #[serde(rename = "toolkit", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub toolkit: Option<Option<String>>,
}

impl ConnectorTool {
    /// A single executable tool within a toolkit, carrying the metadata an agent needs to actually *call* it: the input JSON Schema, tags, and toolkit. This is the raw material for the prompting scaffold in [`crate::skill`].
    pub fn new(name: String, slug: String) -> ConnectorTool {
        ConnectorTool {
            description: None,
            input_schema: None,
            name,
            no_auth: None,
            slug,
            tags: None,
            toolkit: None,
        }
    }
}

