/*
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EvaluatorSpec {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "kind")]
    pub kind: Box<models::EvaluatorKind>,
    #[serde(rename = "lane")]
    pub lane: models::EvaluatorLane,
}

impl EvaluatorSpec {
    pub fn new(id: String, kind: models::EvaluatorKind, lane: models::EvaluatorLane) -> EvaluatorSpec {
        EvaluatorSpec {
            id,
            kind: Box::new(kind),
            lane,
        }
    }
}

