/*
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Prompt {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "project_id")]
    pub project_id: String,
    #[serde(rename = "prompt_id")]
    pub prompt_id: String,
    #[serde(rename = "tenant_id")]
    pub tenant_id: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl Prompt {
    pub fn new(created_at: String, name: String, project_id: String, prompt_id: String, tenant_id: String, updated_at: String) -> Prompt {
        Prompt {
            created_at,
            description: None,
            name,
            project_id,
            prompt_id,
            tenant_id,
            updated_at,
        }
    }
}

