/*
 * Palette API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Palette
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TemperaEvidenceReceipt {
    #[serde(rename = "created")]
    pub created: bool,
    #[serde(rename = "declared_content_sha256")]
    pub declared_content_sha256: String,
    #[serde(rename = "external_id")]
    pub external_id: String,
    #[serde(rename = "kind")]
    pub kind: models::ExternalEvalEvidenceKind,
    #[serde(rename = "project_id")]
    pub project_id: String,
    #[serde(rename = "public_key_sha256")]
    pub public_key_sha256: String,
    #[serde(rename = "schema_version")]
    pub schema_version: String,
    #[serde(rename = "signature_sha256")]
    pub signature_sha256: String,
    #[serde(rename = "signed_payload_sha256")]
    pub signed_payload_sha256: String,
    #[serde(rename = "source_schema_version")]
    pub source_schema_version: String,
    #[serde(rename = "stored_at")]
    pub stored_at: String,
    #[serde(rename = "summary")]
    pub summary: Box<models::TemperaEvidenceSummary>,
    #[serde(rename = "tenant_id")]
    pub tenant_id: String,
}

impl TemperaEvidenceReceipt {
    pub fn new(created: bool, declared_content_sha256: String, external_id: String, kind: models::ExternalEvalEvidenceKind, project_id: String, public_key_sha256: String, schema_version: String, signature_sha256: String, signed_payload_sha256: String, source_schema_version: String, stored_at: String, summary: models::TemperaEvidenceSummary, tenant_id: String) -> TemperaEvidenceReceipt {
        TemperaEvidenceReceipt {
            created,
            declared_content_sha256,
            external_id,
            kind,
            project_id,
            public_key_sha256,
            schema_version,
            signature_sha256,
            signed_payload_sha256,
            source_schema_version,
            stored_at,
            summary: Box::new(summary),
            tenant_id,
        }
    }
}

