/*
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageSummary {
    #[serde(rename = "project_id")]
    pub project_id: String,
    #[serde(rename = "tenant_id")]
    pub tenant_id: String,
    #[serde(rename = "totals")]
    pub totals: std::collections::HashMap<String, models::UsageTotal>,
}

impl UsageSummary {
    pub fn new(project_id: String, tenant_id: String, totals: std::collections::HashMap<String, models::UsageTotal>) -> UsageSummary {
        UsageSummary {
            project_id,
            tenant_id,
            totals,
        }
    }
}

