/*
 * Palette API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Palette
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WriteAck {
    #[serde(rename = "acceptedRaw")]
    pub accepted_raw: i32,
    #[serde(rename = "acceptedSpans")]
    pub accepted_spans: i32,
    #[serde(rename = "duplicateRaw")]
    pub duplicate_raw: i32,
    #[serde(rename = "duplicateSpans")]
    pub duplicate_spans: i32,
}

impl WriteAck {
    pub fn new(accepted_raw: i32, accepted_spans: i32, duplicate_raw: i32, duplicate_spans: i32) -> WriteAck {
        WriteAck {
            accepted_raw,
            accepted_spans,
            duplicate_raw,
            duplicate_spans,
        }
    }
}

