/*
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Beater.Client.Model;
using Beater.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Beater.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EvaluatorKindOneOf1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EvaluatorKindOneOf1Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EvaluatorKindOneOf1
        //private EvaluatorKindOneOf1 instance;

        public EvaluatorKindOneOf1Tests()
        {
            // TODO uncomment below to create an instance of EvaluatorKindOneOf1
            //instance = new EvaluatorKindOneOf1();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EvaluatorKindOneOf1
        /// </summary>
        [Fact]
        public void EvaluatorKindOneOf1InstanceTest()
        {
            // TODO uncomment below to test "IsType" EvaluatorKindOneOf1
            //Assert.IsType<EvaluatorKindOneOf1>(instance);
        }

        /// <summary>
        /// Test the property 'Pattern'
        /// </summary>
        [Fact]
        public void PatternTest()
        {
            // TODO unit test for the property 'Pattern'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
    }
}
