/*
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Beater.Client.Model;
using Beater.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Beater.Client.Test.Model
{
    /// <summary>
    ///  Class for testing InvokeConnectorRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InvokeConnectorRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InvokeConnectorRequest
        //private InvokeConnectorRequest instance;

        public InvokeConnectorRequestTests()
        {
            // TODO uncomment below to create an instance of InvokeConnectorRequest
            //instance = new InvokeConnectorRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InvokeConnectorRequest
        /// </summary>
        [Fact]
        public void InvokeConnectorRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" InvokeConnectorRequest
            //Assert.IsType<InvokeConnectorRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Arguments'
        /// </summary>
        [Fact]
        public void ArgumentsTest()
        {
            // TODO unit test for the property 'Arguments'
        }

        /// <summary>
        /// Test the property 'Tool'
        /// </summary>
        [Fact]
        public void ToolTest()
        {
            // TODO unit test for the property 'Tool'
        }
    }
}
