/*
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Beater.Client.Model;
using Beater.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Beater.Client.Test.Model
{
    /// <summary>
    ///  Class for testing MineScenariosRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MineScenariosRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MineScenariosRequest
        //private MineScenariosRequest instance;

        public MineScenariosRequestTests()
        {
            // TODO uncomment below to create an instance of MineScenariosRequest
            //instance = new MineScenariosRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MineScenariosRequest
        /// </summary>
        [Fact]
        public void MineScenariosRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" MineScenariosRequest
            //Assert.IsType<MineScenariosRequest>(instance);
        }

        /// <summary>
        /// Test the property 'JaccardThreshold'
        /// </summary>
        [Fact]
        public void JaccardThresholdTest()
        {
            // TODO unit test for the property 'JaccardThreshold'
        }

        /// <summary>
        /// Test the property 'TraceIds'
        /// </summary>
        [Fact]
        public void TraceIdsTest()
        {
            // TODO unit test for the property 'TraceIds'
        }
    }
}
