/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "beater-client/model/ApiScope.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

namespace
{
using EnumUnderlyingType = utility::string_t;

ApiScope::eApiScope toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(U("trace_write")))
        return ApiScope::eApiScope::ApiScope_TRACE_WRITE;
    if (val == utility::conversions::to_string_t(U("trace_read")))
        return ApiScope::eApiScope::ApiScope_TRACE_READ;
    if (val == utility::conversions::to_string_t(U("dataset_write")))
        return ApiScope::eApiScope::ApiScope_DATASET_WRITE;
    if (val == utility::conversions::to_string_t(U("scenario_write")))
        return ApiScope::eApiScope::ApiScope_SCENARIO_WRITE;
    if (val == utility::conversions::to_string_t(U("scenario_read")))
        return ApiScope::eApiScope::ApiScope_SCENARIO_READ;
    if (val == utility::conversions::to_string_t(U("eval_run")))
        return ApiScope::eApiScope::ApiScope_EVAL_RUN;
    if (val == utility::conversions::to_string_t(U("pii_unmask")))
        return ApiScope::eApiScope::ApiScope_PII_UNMASK;
    if (val == utility::conversions::to_string_t(U("admin")))
        return ApiScope::eApiScope::ApiScope_ADMIN;
    return {};
}

EnumUnderlyingType fromEnum(ApiScope::eApiScope e)
{
    switch (e)
    {
    case ApiScope::eApiScope::ApiScope_TRACE_WRITE:
        return U("trace_write");
    case ApiScope::eApiScope::ApiScope_TRACE_READ:
        return U("trace_read");
    case ApiScope::eApiScope::ApiScope_DATASET_WRITE:
        return U("dataset_write");
    case ApiScope::eApiScope::ApiScope_SCENARIO_WRITE:
        return U("scenario_write");
    case ApiScope::eApiScope::ApiScope_SCENARIO_READ:
        return U("scenario_read");
    case ApiScope::eApiScope::ApiScope_EVAL_RUN:
        return U("eval_run");
    case ApiScope::eApiScope::ApiScope_PII_UNMASK:
        return U("pii_unmask");
    case ApiScope::eApiScope::ApiScope_ADMIN:
        return U("admin");
    default:
        break;
    }
    return {};
}
}

ApiScope::ApiScope()
{
}

ApiScope::~ApiScope()
{
}

void ApiScope::validate()
{
    // TODO: implement validation
}

web::json::value ApiScope::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool ApiScope::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void ApiScope::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool ApiScope::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

ApiScope::eApiScope ApiScope::getValue() const
{
   return m_value;
}

void ApiScope::setValue(ApiScope::eApiScope const value)
{
   m_value = value;
}

}
}
}
}


