/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "beater-client/model/EvaluateAlertRequest.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

EvaluateAlertRequest::EvaluateAlertRequest()
{
    m_InputIsSet = false;
    m_PolicyIsSet = false;
}

EvaluateAlertRequest::~EvaluateAlertRequest()
{
}

void EvaluateAlertRequest::validate()
{
    // TODO: implement validation
}

web::json::value EvaluateAlertRequest::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_InputIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("input"))] = ModelBase::toJson(m_Input);
    }
    if(m_PolicyIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("policy"))] = ModelBase::toJson(m_Policy);
    }

    return val;
}

bool EvaluateAlertRequest::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(U("input"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("input")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<AlertInput> refVal_setInput;
            ok &= ModelBase::fromJson(fieldValue, refVal_setInput);
            setInput(refVal_setInput);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("policy"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("policy")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<AlertPolicy> refVal_setPolicy;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPolicy);
            setPolicy(refVal_setPolicy);
            
        }
    }
    return ok;
}

void EvaluateAlertRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_InputIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("input")), m_Input));
    }
    if(m_PolicyIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("policy")), m_Policy));
    }
}

bool EvaluateAlertRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("input"))))
    {
        std::shared_ptr<AlertInput> refVal_setInput;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("input"))), refVal_setInput );
        setInput(refVal_setInput);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("policy"))))
    {
        std::shared_ptr<AlertPolicy> refVal_setPolicy;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("policy"))), refVal_setPolicy );
        setPolicy(refVal_setPolicy);
    }
    return ok;
}


std::shared_ptr<AlertInput> EvaluateAlertRequest::getInput() const
{
    return m_Input;
}


void EvaluateAlertRequest::setInput(const std::shared_ptr<AlertInput>& value)
{
    m_Input = value;
    m_InputIsSet = true;
}

bool EvaluateAlertRequest::inputIsSet() const
{
    return m_InputIsSet;
}

void EvaluateAlertRequest::unsetInput()
{
    m_InputIsSet = false;
}
std::shared_ptr<AlertPolicy> EvaluateAlertRequest::getPolicy() const
{
    return m_Policy;
}


void EvaluateAlertRequest::setPolicy(const std::shared_ptr<AlertPolicy>& value)
{
    m_Policy = value;
    m_PolicyIsSet = true;
}

bool EvaluateAlertRequest::policyIsSet() const
{
    return m_PolicyIsSet;
}

void EvaluateAlertRequest::unsetPolicy()
{
    m_PolicyIsSet = false;
}

}
}
}
}


