/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "beater-client/model/PromptVersionListResponse.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

PromptVersionListResponse::PromptVersionListResponse()
{
    m_VersionsIsSet = false;
}

PromptVersionListResponse::~PromptVersionListResponse()
{
}

void PromptVersionListResponse::validate()
{
    // TODO: implement validation
}

web::json::value PromptVersionListResponse::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_VersionsIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("versions"))] = ModelBase::toJson(m_Versions);
    }

    return val;
}

bool PromptVersionListResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(U("versions"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("versions")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<PromptVersion>> refVal_setVersions;
            ok &= ModelBase::fromJson(fieldValue, refVal_setVersions);
            setVersions(refVal_setVersions);
            
        }
    }
    return ok;
}

void PromptVersionListResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_VersionsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("versions")), m_Versions));
    }
}

bool PromptVersionListResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("versions"))))
    {
        std::vector<std::shared_ptr<PromptVersion>> refVal_setVersions;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("versions"))), refVal_setVersions );
        setVersions(refVal_setVersions);
    }
    return ok;
}


std::vector<std::shared_ptr<PromptVersion>> PromptVersionListResponse::getVersions() const
{
    return m_Versions;
}


void PromptVersionListResponse::setVersions(const std::vector<std::shared_ptr<PromptVersion>>& value)
{
    m_Versions = value;
    m_VersionsIsSet = true;
}

bool PromptVersionListResponse::versionsIsSet() const
{
    return m_VersionsIsSet;
}

void PromptVersionListResponse::unsetVersions()
{
    m_VersionsIsSet = false;
}

}
}
}
}


