/**
 * Palette API
 * Agent observability, evaluation, gating, and human-review APIs for Palette
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "palette-client/model/RunJudgeExperimentRequest.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

RunJudgeExperimentRequest::RunJudgeExperimentRequest()
{
    m_BaselineOutputsIsSet = false;
    m_BaselineReleaseId = utility::conversions::to_string_t("");
    m_BaselineReleaseIdIsSet = false;
    m_CandidateOutputsIsSet = false;
    m_CandidateReleaseId = utility::conversions::to_string_t("");
    m_CandidateReleaseIdIsSet = false;
    m_EvaluatorId = utility::conversions::to_string_t("");
    m_EvaluatorIdIsSet = false;
    m_EvaluatorVersionId = utility::conversions::to_string_t("");
    m_EvaluatorVersionIdIsSet = false;
    m_GatePolicyIsSet = false;
    m_KindIsSet = false;
    m_ProviderSecretId = utility::conversions::to_string_t("");
    m_ProviderSecretIdIsSet = false;
}

RunJudgeExperimentRequest::~RunJudgeExperimentRequest()
{
}

void RunJudgeExperimentRequest::validate()
{
    // TODO: implement validation
}

web::json::value RunJudgeExperimentRequest::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_BaselineOutputsIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("baselineOutputs"))] = ModelBase::toJson(m_BaselineOutputs);
    }
    if(m_BaselineReleaseIdIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("baselineReleaseId"))] = ModelBase::toJson(m_BaselineReleaseId);
    }
    if(m_CandidateOutputsIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("candidateOutputs"))] = ModelBase::toJson(m_CandidateOutputs);
    }
    if(m_CandidateReleaseIdIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("candidateReleaseId"))] = ModelBase::toJson(m_CandidateReleaseId);
    }
    if(m_EvaluatorIdIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("evaluatorId"))] = ModelBase::toJson(m_EvaluatorId);
    }
    if(m_EvaluatorVersionIdIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("evaluatorVersionId"))] = ModelBase::toJson(m_EvaluatorVersionId);
    }
    if(m_GatePolicyIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("gatePolicy"))] = ModelBase::toJson(m_GatePolicy);
    }
    if(m_KindIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("kind"))] = ModelBase::toJson(m_Kind);
    }
    if(m_ProviderSecretIdIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("providerSecretId"))] = ModelBase::toJson(m_ProviderSecretId);
    }

    return val;
}

bool RunJudgeExperimentRequest::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(U("baselineOutputs"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("baselineOutputs")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<CaseOutputOverrideRequest>> refVal_setBaselineOutputs;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBaselineOutputs);
            setBaselineOutputs(refVal_setBaselineOutputs);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("baselineReleaseId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("baselineReleaseId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setBaselineReleaseId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBaselineReleaseId);
            setBaselineReleaseId(refVal_setBaselineReleaseId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("candidateOutputs"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("candidateOutputs")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<CaseOutputOverrideRequest>> refVal_setCandidateOutputs;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCandidateOutputs);
            setCandidateOutputs(refVal_setCandidateOutputs);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("candidateReleaseId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("candidateReleaseId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCandidateReleaseId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCandidateReleaseId);
            setCandidateReleaseId(refVal_setCandidateReleaseId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("evaluatorId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("evaluatorId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEvaluatorId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEvaluatorId);
            setEvaluatorId(refVal_setEvaluatorId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("evaluatorVersionId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("evaluatorVersionId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEvaluatorVersionId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEvaluatorVersionId);
            setEvaluatorVersionId(refVal_setEvaluatorVersionId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("gatePolicy"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("gatePolicy")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<GatePolicy> refVal_setGatePolicy;
            ok &= ModelBase::fromJson(fieldValue, refVal_setGatePolicy);
            setGatePolicy(refVal_setGatePolicy);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("kind"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("kind")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<EvaluatorKind> refVal_setKind;
            ok &= ModelBase::fromJson(fieldValue, refVal_setKind);
            setKind(refVal_setKind);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("providerSecretId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("providerSecretId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setProviderSecretId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProviderSecretId);
            setProviderSecretId(refVal_setProviderSecretId);
            
        }
    }
    return ok;
}

void RunJudgeExperimentRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_BaselineOutputsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("baselineOutputs")), m_BaselineOutputs));
    }
    if(m_BaselineReleaseIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("baselineReleaseId")), m_BaselineReleaseId));
    }
    if(m_CandidateOutputsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("candidateOutputs")), m_CandidateOutputs));
    }
    if(m_CandidateReleaseIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("candidateReleaseId")), m_CandidateReleaseId));
    }
    if(m_EvaluatorIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("evaluatorId")), m_EvaluatorId));
    }
    if(m_EvaluatorVersionIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("evaluatorVersionId")), m_EvaluatorVersionId));
    }
    if(m_GatePolicyIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("gatePolicy")), m_GatePolicy));
    }
    if(m_KindIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("kind")), m_Kind));
    }
    if(m_ProviderSecretIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("providerSecretId")), m_ProviderSecretId));
    }
}

bool RunJudgeExperimentRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("baselineOutputs"))))
    {
        std::vector<std::shared_ptr<CaseOutputOverrideRequest>> refVal_setBaselineOutputs;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("baselineOutputs"))), refVal_setBaselineOutputs );
        setBaselineOutputs(refVal_setBaselineOutputs);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("baselineReleaseId"))))
    {
        utility::string_t refVal_setBaselineReleaseId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("baselineReleaseId"))), refVal_setBaselineReleaseId );
        setBaselineReleaseId(refVal_setBaselineReleaseId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("candidateOutputs"))))
    {
        std::vector<std::shared_ptr<CaseOutputOverrideRequest>> refVal_setCandidateOutputs;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("candidateOutputs"))), refVal_setCandidateOutputs );
        setCandidateOutputs(refVal_setCandidateOutputs);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("candidateReleaseId"))))
    {
        utility::string_t refVal_setCandidateReleaseId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("candidateReleaseId"))), refVal_setCandidateReleaseId );
        setCandidateReleaseId(refVal_setCandidateReleaseId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("evaluatorId"))))
    {
        utility::string_t refVal_setEvaluatorId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("evaluatorId"))), refVal_setEvaluatorId );
        setEvaluatorId(refVal_setEvaluatorId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("evaluatorVersionId"))))
    {
        utility::string_t refVal_setEvaluatorVersionId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("evaluatorVersionId"))), refVal_setEvaluatorVersionId );
        setEvaluatorVersionId(refVal_setEvaluatorVersionId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("gatePolicy"))))
    {
        std::shared_ptr<GatePolicy> refVal_setGatePolicy;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("gatePolicy"))), refVal_setGatePolicy );
        setGatePolicy(refVal_setGatePolicy);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("kind"))))
    {
        std::shared_ptr<EvaluatorKind> refVal_setKind;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("kind"))), refVal_setKind );
        setKind(refVal_setKind);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("providerSecretId"))))
    {
        utility::string_t refVal_setProviderSecretId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("providerSecretId"))), refVal_setProviderSecretId );
        setProviderSecretId(refVal_setProviderSecretId);
    }
    return ok;
}


std::vector<std::shared_ptr<CaseOutputOverrideRequest>> RunJudgeExperimentRequest::getBaselineOutputs() const
{
    return m_BaselineOutputs;
}


void RunJudgeExperimentRequest::setBaselineOutputs(const std::vector<std::shared_ptr<CaseOutputOverrideRequest>>& value)
{
    m_BaselineOutputs = value;
    m_BaselineOutputsIsSet = true;
}

bool RunJudgeExperimentRequest::baselineOutputsIsSet() const
{
    return m_BaselineOutputsIsSet;
}

void RunJudgeExperimentRequest::unsetBaselineOutputs()
{
    m_BaselineOutputsIsSet = false;
}
utility::string_t RunJudgeExperimentRequest::getBaselineReleaseId() const
{
    return m_BaselineReleaseId;
}


void RunJudgeExperimentRequest::setBaselineReleaseId(const utility::string_t& value)
{
    m_BaselineReleaseId = value;
    m_BaselineReleaseIdIsSet = true;
}

bool RunJudgeExperimentRequest::baselineReleaseIdIsSet() const
{
    return m_BaselineReleaseIdIsSet;
}

void RunJudgeExperimentRequest::unsetBaselineReleaseId()
{
    m_BaselineReleaseIdIsSet = false;
}
std::vector<std::shared_ptr<CaseOutputOverrideRequest>> RunJudgeExperimentRequest::getCandidateOutputs() const
{
    return m_CandidateOutputs;
}


void RunJudgeExperimentRequest::setCandidateOutputs(const std::vector<std::shared_ptr<CaseOutputOverrideRequest>>& value)
{
    m_CandidateOutputs = value;
    m_CandidateOutputsIsSet = true;
}

bool RunJudgeExperimentRequest::candidateOutputsIsSet() const
{
    return m_CandidateOutputsIsSet;
}

void RunJudgeExperimentRequest::unsetCandidateOutputs()
{
    m_CandidateOutputsIsSet = false;
}
utility::string_t RunJudgeExperimentRequest::getCandidateReleaseId() const
{
    return m_CandidateReleaseId;
}


void RunJudgeExperimentRequest::setCandidateReleaseId(const utility::string_t& value)
{
    m_CandidateReleaseId = value;
    m_CandidateReleaseIdIsSet = true;
}

bool RunJudgeExperimentRequest::candidateReleaseIdIsSet() const
{
    return m_CandidateReleaseIdIsSet;
}

void RunJudgeExperimentRequest::unsetCandidateReleaseId()
{
    m_CandidateReleaseIdIsSet = false;
}
utility::string_t RunJudgeExperimentRequest::getEvaluatorId() const
{
    return m_EvaluatorId;
}


void RunJudgeExperimentRequest::setEvaluatorId(const utility::string_t& value)
{
    m_EvaluatorId = value;
    m_EvaluatorIdIsSet = true;
}

bool RunJudgeExperimentRequest::evaluatorIdIsSet() const
{
    return m_EvaluatorIdIsSet;
}

void RunJudgeExperimentRequest::unsetEvaluatorId()
{
    m_EvaluatorIdIsSet = false;
}
utility::string_t RunJudgeExperimentRequest::getEvaluatorVersionId() const
{
    return m_EvaluatorVersionId;
}


void RunJudgeExperimentRequest::setEvaluatorVersionId(const utility::string_t& value)
{
    m_EvaluatorVersionId = value;
    m_EvaluatorVersionIdIsSet = true;
}

bool RunJudgeExperimentRequest::evaluatorVersionIdIsSet() const
{
    return m_EvaluatorVersionIdIsSet;
}

void RunJudgeExperimentRequest::unsetEvaluatorVersionId()
{
    m_EvaluatorVersionIdIsSet = false;
}
std::shared_ptr<GatePolicy> RunJudgeExperimentRequest::getGatePolicy() const
{
    return m_GatePolicy;
}


void RunJudgeExperimentRequest::setGatePolicy(const std::shared_ptr<GatePolicy>& value)
{
    m_GatePolicy = value;
    m_GatePolicyIsSet = true;
}

bool RunJudgeExperimentRequest::gatePolicyIsSet() const
{
    return m_GatePolicyIsSet;
}

void RunJudgeExperimentRequest::unsetGatePolicy()
{
    m_GatePolicyIsSet = false;
}
std::shared_ptr<EvaluatorKind> RunJudgeExperimentRequest::getKind() const
{
    return m_Kind;
}


void RunJudgeExperimentRequest::setKind(const std::shared_ptr<EvaluatorKind>& value)
{
    m_Kind = value;
    m_KindIsSet = true;
}

bool RunJudgeExperimentRequest::kindIsSet() const
{
    return m_KindIsSet;
}

void RunJudgeExperimentRequest::unsetKind()
{
    m_KindIsSet = false;
}
utility::string_t RunJudgeExperimentRequest::getProviderSecretId() const
{
    return m_ProviderSecretId;
}


void RunJudgeExperimentRequest::setProviderSecretId(const utility::string_t& value)
{
    m_ProviderSecretId = value;
    m_ProviderSecretIdIsSet = true;
}

bool RunJudgeExperimentRequest::providerSecretIdIsSet() const
{
    return m_ProviderSecretIdIsSet;
}

void RunJudgeExperimentRequest::unsetProviderSecretId()
{
    m_ProviderSecretIdIsSet = false;
}

}
}
}
}


