/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "beater-client/model/StatisticalTest.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

namespace
{
using EnumUnderlyingType = utility::string_t;

StatisticalTest::eStatisticalTest toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(U("paired_t")))
        return StatisticalTest::eStatisticalTest::StatisticalTest_PAIRED_T;
    if (val == utility::conversions::to_string_t(U("mcnemar_exact")))
        return StatisticalTest::eStatisticalTest::StatisticalTest_MCNEMAR_EXACT;
    return {};
}

EnumUnderlyingType fromEnum(StatisticalTest::eStatisticalTest e)
{
    switch (e)
    {
    case StatisticalTest::eStatisticalTest::StatisticalTest_PAIRED_T:
        return U("paired_t");
    case StatisticalTest::eStatisticalTest::StatisticalTest_MCNEMAR_EXACT:
        return U("mcnemar_exact");
    default:
        break;
    }
    return {};
}
}

StatisticalTest::StatisticalTest()
{
}

StatisticalTest::~StatisticalTest()
{
}

void StatisticalTest::validate()
{
    // TODO: implement validation
}

web::json::value StatisticalTest::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool StatisticalTest::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void StatisticalTest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool StatisticalTest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

StatisticalTest::eStatisticalTest StatisticalTest::getValue() const
{
   return m_value;
}

void StatisticalTest::setValue(StatisticalTest::eStatisticalTest const value)
{
   m_value = value;
}

}
}
}
}


