/*
 * Palette API
 * Agent observability, evaluation, gating, and human-review APIs for Palette
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.palette.client.api;

import ai.palette.client.ApiException;
import ai.palette.client.model.ArchiveManifest;
import ai.palette.client.model.ArchiveQueryResponse;
import ai.palette.client.model.ErrorResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for ArchiveApi
 */
@Disabled
public class ArchiveApiTest {

    private final ArchiveApi api = new ArchiveApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void archiveArchiveTraceTest() throws ApiException {
        String tenantId = null;
        String projectId = null;
        String traceId = null;
        String authorization = null;
        String xPaletteApiKey = null;
        String xPaletteProjectId = null;
        String xPaletteEnvironmentId = null;
        ArchiveManifest response = 
        api.archiveArchiveTrace(tenantId, projectId, traceId, authorization, xPaletteApiKey, xPaletteProjectId, xPaletteEnvironmentId);
        
        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void archiveQuerySpansTest() throws ApiException {
        String tenantId = null;
        String projectId = null;
        String environmentId = null;
        String traceId = null;
        String spanId = null;
        String kind = null;
        String status = null;
        Integer limit = null;
        String authorization = null;
        String xPaletteApiKey = null;
        String xPaletteProjectId = null;
        String xPaletteEnvironmentId = null;
        ArchiveQueryResponse response = 
        api.archiveQuerySpans(tenantId, projectId, environmentId, traceId, spanId, kind, status, limit, authorization, xPaletteApiKey, xPaletteProjectId, xPaletteEnvironmentId);
        
        // TODO: test validations
    }
    
}
