/*
 * Palette API
 * Agent observability, evaluation, gating, and human-review APIs for Palette
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.palette.client.api;

import ai.palette.client.ApiException;
import ai.palette.client.model.CreateScenarioRequest;
import ai.palette.client.model.ErrorResponse;
import ai.palette.client.model.ListScenariosResponse;
import ai.palette.client.model.MineScenariosRequest;
import ai.palette.client.model.MineScenariosResponse;
import ai.palette.client.model.Scenario;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for ScenariosApi
 */
@Disabled
public class ScenariosApiTest {

    private final ScenariosApi api = new ScenariosApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void scenariosCreateTest() throws ApiException {
        String tenantId = null;
        String projectId = null;
        CreateScenarioRequest createScenarioRequest = null;
        String authorization = null;
        String xPaletteApiKey = null;
        String xPaletteProjectId = null;
        String xPaletteEnvironmentId = null;
        Scenario response = 
        api.scenariosCreate(tenantId, projectId, createScenarioRequest, authorization, xPaletteApiKey, xPaletteProjectId, xPaletteEnvironmentId);
        
        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void scenariosGetTest() throws ApiException {
        String tenantId = null;
        String projectId = null;
        String scenarioId = null;
        String authorization = null;
        String xPaletteApiKey = null;
        String xPaletteProjectId = null;
        String xPaletteEnvironmentId = null;
        Scenario response = 
        api.scenariosGet(tenantId, projectId, scenarioId, authorization, xPaletteApiKey, xPaletteProjectId, xPaletteEnvironmentId);
        
        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void scenariosListTest() throws ApiException {
        String tenantId = null;
        String projectId = null;
        Integer limit = null;
        String cursor = null;
        String authorization = null;
        String xPaletteApiKey = null;
        String xPaletteProjectId = null;
        String xPaletteEnvironmentId = null;
        ListScenariosResponse response = 
        api.scenariosList(tenantId, projectId, limit, cursor, authorization, xPaletteApiKey, xPaletteProjectId, xPaletteEnvironmentId);
        
        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void scenariosMineTest() throws ApiException {
        String tenantId = null;
        String projectId = null;
        MineScenariosRequest mineScenariosRequest = null;
        String authorization = null;
        String xPaletteApiKey = null;
        String xPaletteProjectId = null;
        String xPaletteEnvironmentId = null;
        MineScenariosResponse response = 
        api.scenariosMine(tenantId, projectId, mineScenariosRequest, authorization, xPaletteApiKey, xPaletteProjectId, xPaletteEnvironmentId);
        
        // TODO: test validations
    }
    
}
