/*
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.beater.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.beater.client.ApiClient;
/**
 * The anti-overfitting (generalization-gap) assessment.
 */
@JsonPropertyOrder({
  OverfitResponse.JSON_PROPERTY_GAP,
  OverfitResponse.JSON_PROPERTY_GAP_CI_HIGH,
  OverfitResponse.JSON_PROPERTY_GAP_CI_LOW,
  OverfitResponse.JSON_PROPERTY_HOLDOUT_LIFT,
  OverfitResponse.JSON_PROPERTY_OPTIMIZE_LIFT,
  OverfitResponse.JSON_PROPERTY_OVERFIT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class OverfitResponse {
  public static final String JSON_PROPERTY_GAP = "gap";
  @javax.annotation.Nonnull
  private Double gap;

  public static final String JSON_PROPERTY_GAP_CI_HIGH = "gap_ci_high";
  @javax.annotation.Nonnull
  private Double gapCiHigh;

  public static final String JSON_PROPERTY_GAP_CI_LOW = "gap_ci_low";
  @javax.annotation.Nonnull
  private Double gapCiLow;

  public static final String JSON_PROPERTY_HOLDOUT_LIFT = "holdout_lift";
  @javax.annotation.Nonnull
  private Double holdoutLift;

  public static final String JSON_PROPERTY_OPTIMIZE_LIFT = "optimize_lift";
  @javax.annotation.Nonnull
  private Double optimizeLift;

  public static final String JSON_PROPERTY_OVERFIT = "overfit";
  @javax.annotation.Nonnull
  private Boolean overfit;

  public OverfitResponse() { 
  }

  public OverfitResponse gap(@javax.annotation.Nonnull Double gap) {
    this.gap = gap;
    return this;
  }

  /**
   * &#x60;optimize_lift − holdout_lift&#x60;.
   * @return gap
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_GAP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Double getGap() {
    return gap;
  }


  @JsonProperty(JSON_PROPERTY_GAP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGap(@javax.annotation.Nonnull Double gap) {
    this.gap = gap;
  }


  public OverfitResponse gapCiHigh(@javax.annotation.Nonnull Double gapCiHigh) {
    this.gapCiHigh = gapCiHigh;
    return this;
  }

  /**
   * Upper bound of the bootstrap CI for &#x60;gap&#x60;.
   * @return gapCiHigh
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_GAP_CI_HIGH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Double getGapCiHigh() {
    return gapCiHigh;
  }


  @JsonProperty(JSON_PROPERTY_GAP_CI_HIGH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGapCiHigh(@javax.annotation.Nonnull Double gapCiHigh) {
    this.gapCiHigh = gapCiHigh;
  }


  public OverfitResponse gapCiLow(@javax.annotation.Nonnull Double gapCiLow) {
    this.gapCiLow = gapCiLow;
    return this;
  }

  /**
   * Lower bound of the bootstrap CI for &#x60;gap&#x60;.
   * @return gapCiLow
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_GAP_CI_LOW)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Double getGapCiLow() {
    return gapCiLow;
  }


  @JsonProperty(JSON_PROPERTY_GAP_CI_LOW)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGapCiLow(@javax.annotation.Nonnull Double gapCiLow) {
    this.gapCiLow = gapCiLow;
  }


  public OverfitResponse holdoutLift(@javax.annotation.Nonnull Double holdoutLift) {
    this.holdoutLift = holdoutLift;
    return this;
  }

  /**
   * Mean paired lift on the held-out split.
   * @return holdoutLift
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_HOLDOUT_LIFT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Double getHoldoutLift() {
    return holdoutLift;
  }


  @JsonProperty(JSON_PROPERTY_HOLDOUT_LIFT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHoldoutLift(@javax.annotation.Nonnull Double holdoutLift) {
    this.holdoutLift = holdoutLift;
  }


  public OverfitResponse optimizeLift(@javax.annotation.Nonnull Double optimizeLift) {
    this.optimizeLift = optimizeLift;
    return this;
  }

  /**
   * Mean paired lift &#x60;(candidate − baseline)&#x60; on the optimization split.
   * @return optimizeLift
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_OPTIMIZE_LIFT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Double getOptimizeLift() {
    return optimizeLift;
  }


  @JsonProperty(JSON_PROPERTY_OPTIMIZE_LIFT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOptimizeLift(@javax.annotation.Nonnull Double optimizeLift) {
    this.optimizeLift = optimizeLift;
  }


  public OverfitResponse overfit(@javax.annotation.Nonnull Boolean overfit) {
    this.overfit = overfit;
    return this;
  }

  /**
   * &#x60;true&#x60; when the gap&#39;s CI lower bound exceeds tolerance — the candidate&#39;s optimization-set advantage is significantly not reproduced on held-out data.
   * @return overfit
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_OVERFIT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getOverfit() {
    return overfit;
  }


  @JsonProperty(JSON_PROPERTY_OVERFIT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOverfit(@javax.annotation.Nonnull Boolean overfit) {
    this.overfit = overfit;
  }


  /**
   * Return true if this OverfitResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OverfitResponse overfitResponse = (OverfitResponse) o;
    return Objects.equals(this.gap, overfitResponse.gap) &&
        Objects.equals(this.gapCiHigh, overfitResponse.gapCiHigh) &&
        Objects.equals(this.gapCiLow, overfitResponse.gapCiLow) &&
        Objects.equals(this.holdoutLift, overfitResponse.holdoutLift) &&
        Objects.equals(this.optimizeLift, overfitResponse.optimizeLift) &&
        Objects.equals(this.overfit, overfitResponse.overfit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gap, gapCiHigh, gapCiLow, holdoutLift, optimizeLift, overfit);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OverfitResponse {\n");
    sb.append("    gap: ").append(toIndentedString(gap)).append("\n");
    sb.append("    gapCiHigh: ").append(toIndentedString(gapCiHigh)).append("\n");
    sb.append("    gapCiLow: ").append(toIndentedString(gapCiLow)).append("\n");
    sb.append("    holdoutLift: ").append(toIndentedString(holdoutLift)).append("\n");
    sb.append("    optimizeLift: ").append(toIndentedString(optimizeLift)).append("\n");
    sb.append("    overfit: ").append(toIndentedString(overfit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `gap` to the URL query string
    if (getGap() != null) {
      joiner.add(String.format("%sgap%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getGap()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `gap_ci_high` to the URL query string
    if (getGapCiHigh() != null) {
      joiner.add(String.format("%sgap_ci_high%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getGapCiHigh()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `gap_ci_low` to the URL query string
    if (getGapCiLow() != null) {
      joiner.add(String.format("%sgap_ci_low%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getGapCiLow()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `holdout_lift` to the URL query string
    if (getHoldoutLift() != null) {
      joiner.add(String.format("%sholdout_lift%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getHoldoutLift()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `optimize_lift` to the URL query string
    if (getOptimizeLift() != null) {
      joiner.add(String.format("%soptimize_lift%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getOptimizeLift()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `overfit` to the URL query string
    if (getOverfit() != null) {
      joiner.add(String.format("%soverfit%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getOverfit()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

