/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CalibrationItem.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_CalibrationItem_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_CalibrationItem_H_

#include <stdexcept>

#include "beater-client/ModelBase.h"

#include "beater-client/AnyType.h"
#include "beater-client/model/CalibrationLabel.h"
#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  CalibrationItem
    : public ModelBase
{
public:
    CalibrationItem();
    virtual ~CalibrationItem();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// CalibrationItem members


    bool isAgreed() const;
    bool agreedIsSet() const;
    void unsetAgreed();
    void setAgreed(bool value);

    utility::string_t getDatasetCaseId() const;
    bool datasetCaseIdIsSet() const;
    void unsetDataset_case_id();
    void setDatasetCaseId(const utility::string_t& value);

    std::shared_ptr<AnyType> getEvidence() const;
    bool evidenceIsSet() const;
    void unsetEvidence();
    void setEvidence(const std::shared_ptr<AnyType>& value);

    std::shared_ptr<CalibrationLabel> getHumanLabel() const;
    bool humanLabelIsSet() const;
    void unsetHuman_label();
    void setHumanLabel(const std::shared_ptr<CalibrationLabel>& value);

    std::shared_ptr<CalibrationLabel> getJudgeLabel() const;
    bool judgeLabelIsSet() const;
    void unsetJudge_label();
    void setJudgeLabel(const std::shared_ptr<CalibrationLabel>& value);

    utility::string_t getJudgeResultLabel() const;
    bool judgeResultLabelIsSet() const;
    void unsetJudge_result_label();
    void setJudgeResultLabel(const utility::string_t& value);

    double getJudgeScore() const;
    bool judgeScoreIsSet() const;
    void unsetJudge_score();
    void setJudgeScore(double value);


protected:
    bool m_Agreed;
    bool m_AgreedIsSet;

    utility::string_t m_Dataset_case_id;
    bool m_Dataset_case_idIsSet;

    std::shared_ptr<AnyType> m_Evidence;
    bool m_EvidenceIsSet;

    std::shared_ptr<CalibrationLabel> m_Human_label;
    bool m_Human_labelIsSet;

    std::shared_ptr<CalibrationLabel> m_Judge_label;
    bool m_Judge_labelIsSet;

    utility::string_t m_Judge_result_label;
    bool m_Judge_result_labelIsSet;

    double m_Judge_score;
    bool m_Judge_scoreIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_CalibrationItem_H_ */
