/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OtlpIngestOutcome.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_OtlpIngestOutcome_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_OtlpIngestOutcome_H_


#include "beater-client/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {



class  OtlpIngestOutcome
    : public ModelBase
{
public:
    OtlpIngestOutcome();
    virtual ~OtlpIngestOutcome();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// OtlpIngestOutcome members


    int32_t getAcceptedRaw() const;
    bool acceptedRawIsSet() const;
    void unsetAccepted_raw();
    void setAcceptedRaw(int32_t value);

    int32_t getAcceptedSpans() const;
    bool acceptedSpansIsSet() const;
    void unsetAccepted_spans();
    void setAcceptedSpans(int32_t value);

    bool isDownstreamQueued() const;
    bool downstreamQueuedIsSet() const;
    void unsetDownstream_queued();
    void setDownstreamQueued(bool value);

    int32_t getDuplicateRaw() const;
    bool duplicateRawIsSet() const;
    void unsetDuplicate_raw();
    void setDuplicateRaw(int32_t value);

    int32_t getDuplicateSpans() const;
    bool duplicateSpansIsSet() const;
    void unsetDuplicate_spans();
    void setDuplicateSpans(int32_t value);


protected:
    int32_t m_Accepted_raw;
    bool m_Accepted_rawIsSet;

    int32_t m_Accepted_spans;
    bool m_Accepted_spansIsSet;

    bool m_Downstream_queued;
    bool m_Downstream_queuedIsSet;

    int32_t m_Duplicate_raw;
    bool m_Duplicate_rawIsSet;

    int32_t m_Duplicate_spans;
    bool m_Duplicate_spansIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_OtlpIngestOutcome_H_ */
